import json
from pathlib import Path
root=Path(__file__).parent
boards=[
('01','Baumfamilien','20 Baumstudien: Silhouette, Schichtung, Wurzeln und Blickachsen',[
'Goldene Eiche, gesamte unregelmäßige Krone','Eiche mit sichtbarer Verzweigung aus Augenhöhe','Orange Ahornkrone vor heller Mauer','Schattiger Kronenkern und warme Blattspitzen','Birke mit hellem Stamm am sicheren Nebenweg','Lindenfamilie in limettengrün','Linde über einer Steinbank, freie Sicht darunter','Kiefer mit gestaffelten horizontalen Kronen','Schlanke Zypresse als Turmrahmung','Rosa Blütenbaum, zurückhaltende Akzentfarbe','Doppelbaumgruppe ohne identische Silhouette','Junger Baum neben altem verzweigtem Stamm','Drei Kronenhöhen als Tiefenstaffelung','Wurzeln am Weg außerhalb der Gehfläche','Astgabel und kleine Zweige im Detail','Goldene Blattgruppe aus drei Lichtwerten','Lime Blattgruppe bei gleicher Materialwirkung','Rosa Blattgruppe bei gleicher Materialwirkung','Bäume rahmen ein rotes Tor ohne es zu verdecken','Fünf ausgewählte Familien als Größenvergleich']),
('02','Boden und Küste','20 Material- und Landschaftsstudien',[
'Warmer Kalksteinweg mit ruhigen großen Fugen','Sandweg mit klarer Graskante','Moosige Mauerkante außerhalb einer Wortfläche','Ockerfarbener Fels mit drei Absätzen','Küstenschichtung vor ruhigem blauem Meer','Breite sichere Treppe ohne Sprung','Niedrige Grasinsel mit dichtem Rand','Farnfamilie mit klaren Blattgruppen','Schilf am unbetretbaren Wasserrand','Helles Steinplateau mit Geländer','Kleine überquerbare Wurzel außerhalb der Rätselmitte','Ruhige Meerfläche mit weicher Schaumkante','Laubhäufchen nur außerhalb lesbarer Platten','Sandsteinbogen auf tatsächlichen Trägern','Gras und Kies als sichere Nebenroute','Bruchkante mit kleinem Sockelabsatz','Runder Platz mit zwei klaren Ausgängen','Kalkstein und Sand in einem Raum','Nebenweg mit Aussicht statt Sackgassenstrafe','Vergleich fünf ruhiger Bodenmaterialien']),
('03','Architektur und Mechanik','20 original gestaltete Bauobjekte',[
'Roter Gittertorrahmen mit hellem Steinsockel','Tor geschlossen, Kabel dunkel','Tor halb geöffnet, Durchgang noch gesperrt','Tor vollständig geöffnet, Kabel mint','Niedriger Rundbogen am Ankunftspunkt','Brunnen mit ruhigem Wasser und Messauslass','Füllhebel aus Kupfer neben dem Brunnen','Ablassbecken mit eindeutiger Minusmarkierung','Satzplatz mit kleinen Häuserfassaden','Terrakottadach mit modellierten Reihen','Steinbank als Beobachtungslandmarke','Kabelkanal eingelassen im Stein','Startstein mit rundem Beginn','Schlussstein mit eigener Prüfmarke','Rücknahmestein am sicheren Rand','Turm mit genau acht getrennten Fenstern','Turm mit vier hellen und vier dunklen Fenstern','Steingeländer mit sichtbaren Pfosten','Mauerabschluss mit abgestuften Kappen','Eine Materialfamilie Stein Kupfer Rostrot Wasser']),
('04','Verbengarten','20 Raum- und Zustandsansichten aus Ego-Perspektive',[
'Ankunft bei160cm Augenhöhe, orange Kronen und rotes Tor','Probe mit vier Wortplatten und zwei Auswahlplätzen','Wortplatte ruhig lesbar ohne Blattüberdeckung','Wortkontext bewusst geöffnet','Eine ausgewählte und eine freie Probeplatte','Zwei ausgewählte Platten, weitere Auswahl begrenzt','Falsche Auswahl mit Formmarkierung und Rücknahmeweg','Erfolgreiche Probe öffnet kleines Tor','Hauptfeld drei Reihen mit je drei Platten','Sicherer Außenweg neben dem Feld','Runder Beginn vor Reihe eins','Erster mittiger Verbenschritt','Randkontakt auf neutraler Fuge','Zweiter Schritt in der nächsten Reihe','Vorzeitige spätere Reihe bleibt ohne Fortschritt','Falsches Wort mit dauerhaft anderem Symbol','Rücknahme des letzten Schritts','Vollständiger Weg vor Schlussbestätigung','Gelöstes Gartentor und eine Turmlampe','Neuer Kontext als freiwillige Transferaufgabe']),
('05','Satzplatz','20 Ansichten für Satzglieder und Reihenfolge',[
'Rosa und lime Bäume um einen hellen kleinen Platz','Vier Wortgruppen in einer vollständigen Bank','Vier leere Sockel vor einem geschlossenen Tor','Erste Wortgruppe auf dem ersten Sockel','Verb auf zweiter Satzgliedposition','Drei Wortgruppen, ein freier Sockel','Vollständiger Aussagesatz vor Prüfung','Gültiger Satz beginnt mit dem Subjekt','Gültiger Satz beginnt mit dem Objekt','Gültiger Satz beginnt mit der Zeitangabe','Ungewöhnlicher gültiger Satz bleibt zugelassen','Verb auf erster Position als Frage markiert','Verb auf dritter Position mit Positionshinweis','Doppelter Satzteil wird nicht kopiert','Gezielte Rücknahme des letzten Teils','Wortkontext groß lesbar im ruhigen Fokus','Vier ausgewählte Sockel und mint Verbindung','Toröffnung nach getrennter Bestätigung','Abkürzung zurück zum Knotenplatz','Anderer Beispielsatz in freiwilliger Übung']),
('06','Bruchleitungen','20 Mengen-, Pfad- und Beckenstudien',[
'Wasserterrasse mit einem klaren1-Liter-Becken','Leere Anlage mit zehn gleichen Markierungen','Runder Start und drei getrennte Leitungsäste','RouteA mit drei Teilmengen zum Ganzen','RouteB endet unterhalb der Vollmarke','RouteC endet bei sieben Zehnteln','Eine Hälfte entspricht fünf Zehnteln','Ein Fünftel entspricht zwei Zehnteln','Drei Zehntel als ruhiger Wasserstand','Getrennte Astgeometrie ohne Querabkürzung','Eine ausgewählte Kante und nächster Knoten','Unvollständiger Ast vor einer Prüfung','Rückwärtsnehmen einer zuletzt gesetzten Kante','Mengenanzeige bei vier Fünfteln','Mengenanzeige bei sieben Zehnteln','Volles Becken nach richtiger Gesamtmenge','Gate bleibt während Bewegung noch gesperrt','Offener Weg nach bestätigtem Becken','Andere Skala für freiwillige Zwölftelaufgabe','Vergleich halbes Viertel- und Zehntelbecken']),
('07','Mess-Eimer','20 präzise Objekt- und Handlungsvorlagen',[
'Ein kleiner Mess-Eimer mit Aufschrift1L','Zylindrischer Innenraum statt großer Tank','Gleichmäßige Zehntelskala mit Null und Voll','Eimer leer auf einem niedrigen Sockel','Ein Zehntel Wasser, einhundert Milliliter','Zwei Zehntel Wasser unter dem Ziel','Drei Zehntel Wasser als Zielmenge','Vier Zehntel Wasser über dem Ziel','Voller Eimer mit zehn Zehnteln','Runder geschlossener Metallrand im Detail','Ein plausibler dünner Tragegriff','Transparentes Gefäß mit sichtbarer Wasserlinie','Aufnehmen am Sockel','Getragener Eimer vollständig im unteren Blick','Gut lesbare ergänzende Skala am Bildrand','Füllen am Brunnen in einer Portion','Ablassen einer Portion am Nebenbecken','Eimer falsch auf Platte, wieder aufnehmbar','Richtige Menge auf Platte öffnet das Tor','Pause unterbricht einen noch unbestätigten Hub']),
('08','Felsfenster','20 Beobachtungs- und Suchstudien',[
'Sichere Küstenschleife mit vier erreichbaren Reliefs','Fundrelief ein Zehntel auf einem Fels','Fundrelief ein Fünftel an einer Mauer','Fundrelief zwei Fünftel an einem Träger','Fundrelief eine Hälfte an einer Bank','Entdeckte Reliefs als getrennte Skizzenliste','Genau drei leere Auswahlplätze','Drei ausgewählte Funde vor Mengenprüfung','Eine falsche Dreiermenge unter dem Ganzen','Eine falsche Dreiermenge über dem Ganzen','Richtige Menge, Blickausrichtung noch offen','Steinbank kennzeichnet großzügigen Standbereich','Drei Formen auf unterschiedlich entfernten Trägern','Getrennte Formen aus falschem Blick','Zusammenpassende Kurve vom Aussichtspunkt','Kontrastumrisse ohne Kamerateleport','Blickhilfe als bewusste eigene Aktion','Letzte Verbindung wird manuell bestätigt','Mintkabel läuft zum Turm nach Erfolg','Vier helle Signale am Prototypabschluss']),
('09','Inselzusammenhang','20 Übersichten und Blickbeziehungen',[
'Originale Insel mit Garten Satzplatz Wasser und Küste','Insel mit acht unterschiedlichen geplanten Zonen','Garten zu Satzplatz durch ein lesbares Tor','Satzplatz zu Wasser durch einen Bogen','Wasser zu Küste mit Meerblick','Küste zu Turm mit markanter Bank','Turm als Fernlandmarke aus dem Garten','Turm als Fernlandmarke vom Satzplatz','Turm als Fernlandmarke von der Wasserterrasse','Knotenplatz mit rückkehrbarem Seitenweg','Geöffnete Abkürzung verbindet frühere Räume','Heckenlabyrinth als geplanter späterer Raum','Spiegelgarten als geplanter späterer Raum','Klangwald als geplanter späterer Raum','Leuchtturm-Innenraum als geplanter späterer Raum','Ruhige Höhenschichtung ohne unpassierbare Sprünge','Uferweg um eine Felsgruppe','Platz mit klarer Haupt- und Nebenroute','Landschaftsmassen statt weißem Fliesenflur','Vier gebaute und vier geplante Bereiche unterscheiden']),
('10','Ego-Bedienung','20 Bedien- und Blickstudien',[
'Freier Ego-Blick ohne Avatar in der Bildmitte','Kleine unaufdringliche Zielmarke','Ein klarer Hinweis für nahes Objekt','Wortkontext mit großer lesbarer Schrift','Bestätigen und Zurück als getrennte Flächen','Pointer wählt eine konkrete Wortplatte','Kameradrag verändert keine Antwort','Vier Satzsockel als große Auswahlflächen','Start und Rücknahme auf einer Rätseltafel','Leitungsknoten mit genügend Abstand','Touchbereich links bewegt, rechts schaut','Touchaktion eindeutig vom Blickbereich getrennt','Pause mit Weiter und Sichtfeld','Fokus hält die Weltbewegung sicher an','Rückkehr ohne gehaltene alte Bewegung','Zehntelskala ohne widersprüchliche Literangabe','Felsfund und Lösungsauswahl als getrennte Handlungen','Gut lesbare Hilfe ohne ganze Antwort','Abschlussansicht mit genau vier Signalen','Ruhiges Logbuch für Entdeckungen und gelöste Regeln']),
('11','Fehler und Wiederaufnahme','20 Vorher-Nachher-Zustandspaare',[
'Ungewählte Platte mit neutralem Rand','Gewählte richtige Platte mit eigenem Symbol','Gewählte falsche Platte mit Fehlersymbol','Volle Auswahl bleibt begrenzt','Teilversuch bleibt vor Prüfung sichtbar','Letzter Schritt wird gezielt zurückgenommen','Bestätigte Lösung bleibt nach Rücknahme offen','Falsche Wassermenge öffnet nichts','Eimeraufnahme aus einer Fehlposition','Korrigierte Wassermenge öffnet das Tor','Unterbrochener Drag erhält letzten Knoten','Fokusverlust beendet Bewegung','Pause verwirft unbestätigte Portion','Gespeicherte Funde bleiben in der Skizzenliste','Gültige Bruchvorwahl bleibt bei Rückkehr erhalten','Sicherer Start nach ungültiger Spielerposition','Wiederholt gedrücktes Ende erzeugt kein zweites Signal','Fehler wird lokal erklärt statt aggressivem Blinken','Seitenweg lässt Rückkehr zu früheren Räumen zu','Vor und nach einem vollständig gelösten Gebiet']),
('12','Licht und Materialqualität','20 Farb-, Schatten- und Detailstudien',[
'Goldener Garten am stabilen klaren Vormittag','Seitliches Licht auf gut lesbaren Wortflächen','Orange Kronen vor ruhigem blauem Himmel','Lime Kronen vor warmem Kalkstein','Rosa Akzentkrone ohne violette Gesamtwelt','Kühles Meer kontrastiert mit heller Küste','Weiche Schattenkerne unter dichtem Baumlaub','Relief mit dunkler Vertiefung und hellem Rand','Rostrote Mechanik im neutralen Stein','Kupferleitung dunkel vor Lösung','Kupferleitung mit zurückhaltendem mint Signal','Helles Haus mit modelliertem Dachabsatz','Fels mit großen Formen und sekundären Bruchflächen','Zylindrisches Wassergefäß ohne große Spiegelblendung','Becken mit klarer ruhiger Wasserhöhe','Steinoberfläche ohne störende Schrifttextur','Vegetationsrahmen lässt Hauptweg offen','Vergleich kleiner und größerer Blickwinkel','Nahdetail und Fernsilhouette derselben Baumfamilie','Vier konsistente Bereichspaletten nebeneinander'])]
base='''Use case: stylized-concept. Asset type: production reference contact sheet for an original first-person educational puzzle island. The two input screenshots are STYLE REFERENCES ONLY: warm golden foliage, sculpted irregular trees, ivory and ochre limestone, red iron gates, blue sea, tiny restrained mint solved cables, clear sunny painterly 3D forms. Do not copy the exact island or game assets. NOT pixel art, NOT Pokemon, NOT blocky engine cubes, NOT realistic gritty dark fantasy. Landscape concept sheet with exactly20 distinct panels arranged5 columns by4 rows, equal gutters, numbered01 through20 in reading order with small plain labels. Close asset studies where specified; world panels at160cm first-person eye height/FOV75 unless explicitly an island overview. Consistent visual identity across every panel. No large title, no watermark, no extra NPCs, no decorative fake educational text. Preserve readability of physical spaces. Numerical correctness and final UI will be rebuilt from authored data; this sheet is only concept art. '''
# Separate prompts per board, never substitute one repeated picture for distinct studies.
data=[]
for bid,title,purpose,items in boards:
 prompt=base+'\nBoard theme: '+title+'. '+purpose+'.\nPanels:\n'+'\n'.join(f'{i+1:02d}. {name}' for i,name in enumerate(items))
 data.append({'id':bid,'title':title,'purpose':purpose,'motifs':[{'id':f'{bid}.{i+1:02d}','description':name} for i,name in enumerate(items)],'prompt':prompt,'path':f'boards/{bid}.png','status':'planned'})
(root/'katalog.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
md=['# Bildkatalog: 240 zusätzliche Produktionsmotive','\nZwölf Tafeln, jeweils20 Motive. Zusammen mit den bisherigen21 Motiven ergeben sich261 Konzeptansichten. Die Zahl bezeichnet Bildfelder, keine fertig modellierten Assets. Zielbilder bestimmen Formen; exakte Schrift, Mathematik, Mengen und Kollisionsgeometrie kommen aus dem Bauvertrag.\n']
for b in data:
 md += [f'## Tafel {b["id"]}: {b["title"]}',f'![{b["title"]}]({b["path"]})',b['purpose'],'']
 md += [f'- **{m["id"]}**: {m["description"]}.' for m in b['motifs']]
 md+=['\nÜbernahme: passende Familien auswählen; nicht jede Ansicht als anderes Modell bauen. Prüfen: Silhouette, Material, Blickfreiheit und dargestellter Zustand. Zahlen, Gategap, Signalanzahl und UI bleiben gesonderte Daten-/Engineprüfungen.\n']
(root/'bildkatalog.md').write_text('\n'.join(md)+'\n')
