(() => {
'use strict';
const API_URL='https://europe-west1-hausaufgabe-staging.cloudfunctions.net/vocabRushApi';
const SETS_KEY='gradecrew-vocabrush-sets-v1';
const NAME_KEY='gradecrew-vocabrush-name-v1';
const PLAYER_KEY='gradecrew-vocabrush-player-v1';
const {TOPICS,GRADE_HINTS,availableTopics,recommendedTopics,createCurriculumEngine,createVocabEngine}=window.VocabRush;
const $=id=>document.getElementById(id);
const views=['homeView','setupView','setEditorView','highscoreView','joinView','teacherView','waitingView','gameView','resultView'].map($);
const ids=['quickJoinCode','quickJoinBtn','setupForm','setupEyebrow','setupTitle','setupSubtitle','curriculumSetup','customSetup','gradeHint','topicGrid','setList','newSetBtn','wrongPenalty','lockSeconds','speedBonus','teacherRules','leaderboardMode','rulesHint','scorePreview','setupError','setupSubmit','backToSetup','setTitle','photoImportBtn','pasteImportBtn','photoInput','pasteArea','parsePasteBtn','importStatus','itemCount','itemEditor','addRowBtn','setError','saveSetBtn','highscoreName','highscoreGrade','highscoreTopic','highscoreError','startHighscoreBtn','refreshBoardBtn','boardLabel','highscoreBoard','joinCode','joinName','joinError','joinBtn','teacherSummary','roomCode','qrBox','copyLinkBtn','playerCount','roomBadge','playerList','teacherRulesSummary','startLiveBtn','liveBoardStatus','liveBoard','waitingName','waitingCode','countdown','roundLabel','playerLabel','roundCodeLabel','timerFill','timer','correctCount','streakCount','scoreCount','taskNumber','taskTopic','taskPrompt','answers','penaltyLock','penaltyTime','feedback','resultSummary','resultCorrect','resultAccuracy','resultStreak','resultScore','resultBoardCard','resultBoard','resultActionText','sameRoundBtn','newRoundBtn','homeBtn'];
const el={};ids.forEach(id=>el[id]=$(id));
const state={mode:'practice',config:null,seed:0,engine:null,task:null,source:'curriculum',setId:null,editorItems:[],roomCode:null,hostToken:null,playerId:null,playerToken:null,playerName:'',attemptId:null,attemptToken:null,startedAt:0,endsAt:0,timerId:null,pollId:null,progressId:null,lockId:null,countdownId:null,questionStartedAt:0,questionIndex:0,locked:false,finished:false,correct:0,total:0,streak:0,bestStreak:0,score:0};
function show(view){views.forEach(v=>v.hidden=v!==view);window.scrollTo({top:0,behavior:'instant'});}function stopAsync(){[state.timerId,state.pollId,state.progressId,state.lockId,state.countdownId].forEach(clearInterval);state.timerId=state.pollId=state.progressId=state.lockId=state.countdownId=null;}
function randomSeed(){if(crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0];}return Math.floor(Math.random()*0xffffffff)>>>0;}
function playerKey(){let k=localStorage.getItem(PLAYER_KEY);if(!k){k=crypto?.randomUUID?.().replace(/-/g,'')||`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;localStorage.setItem(PLAYER_KEY,k);}return k;}
async function api(action,payload={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload}),signal:c.signal});const b=await r.json().catch(()=>null);if(!r.ok||!b?.ok)throw new Error(b?.error?.message||`Backend ${r.status}`);return b.data;}catch(e){if(e?.name==='AbortError')throw new Error('Die Verbindung dauert zu lange.');throw e;}finally{clearTimeout(t);}}
function getSets(){try{const x=JSON.parse(localStorage.getItem(SETS_KEY)||'[]');return Array.isArray(x)?x:[];}catch{return[];}}function saveSets(sets){localStorage.setItem(SETS_KEY,JSON.stringify(sets.slice(0,30)));}function activeSource(){return document.querySelector('input[name="source"]:checked')?.value||'curriculum';}function grade(){return document.querySelector('input[name="grade"]:checked')?.value||'9';}function direction(){return document.querySelector('input[name="direction"]:checked')?.value||'mixed';}function durationSec(){return Number(document.querySelector('input[name="duration"]:checked')?.value||3)*60;}function selectedTopics(){return[...document.querySelectorAll('input[name="topic"]:checked')].map(x=>x.value);}function selectedSet(){return getSets().find(s=>s.id===state.setId)||null;}
function scoring(){const practice=state.mode==='practice';return{correctPoints:100,wrongPenalty:Number(el.wrongPenalty.value),lockSeconds:Math.max(practice?5:0,Number(el.lockSeconds.value)),speedBonus:practice?false:el.speedBonus.checked,streakBonus:true,showSolution:true,allowNegative:true};}
function renderTopics(){const g=Number(grade()),available=new Set(availableTopics(g)),recommended=new Set(recommendedTopics(g));el.gradeHint.textContent=GRADE_HINTS[g]||'';el.topicGrid.replaceChildren();Object.entries(TOPICS).forEach(([id,m])=>{const label=document.createElement('label');label.className='topicTile';const input=document.createElement('input');input.type='checkbox';input.name='topic';input.value=id;input.checked=recommended.has(id);const span=document.createElement('span');const em=document.createElement('em');em.textContent=m.introduced===g?`NEU / ZENTRAL IN JGST. ${g}`:m.introduced<g?'WIEDERHOLEN & VERTIEFEN':`ZUSÄTZLICH · AB JGST. ${m.introduced}`;const b=document.createElement('b');b.textContent=m.label;const small=document.createElement('small');small.textContent=m.desc;span.append(em,b,small);label.append(input,span);if(!available.has(id))label.dataset.additional='1';el.topicGrid.append(label);});}
function renderSets(){const sets=getSets();el.setList.replaceChildren();if(!sets.length){const p=document.createElement('p');p.className='empty';p.textContent='Noch kein eigenes Vokabelset. Lege dein erstes Set an.';el.setList.append(p);state.setId=null;return;}if(!sets.some(s=>s.id===state.setId))state.setId=sets[0].id;sets.forEach(s=>{const d=document.createElement('button');d.type='button';d.className='setCard'+(s.id===state.setId?' selected':'');d.innerHTML='<span></span><b></b>';d.firstElementChild.textContent=s.title;d.lastElementChild.textContent=`${s.items.length} Wörter`;d.addEventListener('click',()=>{state.setId=s.id;renderSets();});el.setList.append(d);});}
function updateSourceUI(){state.source=activeSource();el.curriculumSetup.hidden=state.source!=='curriculum';el.customSetup.hidden=state.source!=='custom';if(state.source==='custom')renderSets();}
function updateScorePreview(){el.scorePreview.textContent=`${Number(el.wrongPenalty.value)?`−${el.wrongPenalty.value} falsch`:'keine Minuspunkte'} · ${Math.max(state.mode==='practice'?5:0,Number(el.lockSeconds.value))} s Pause${state.mode==='practice'?' · Fehler kommen wieder':''}`;}
function gatherConfig(){const source=activeSource(),base={version:1,source,durationSec:durationSec(),scoring:scoring(),leaderboardMode:state.mode==='liveTeacher'?el.leaderboardMode.value:'hidden'};if(source==='curriculum'){const topics=selectedTopics();if(!topics.length)throw new Error('Bitte mindestens ein Thema auswählen.');return{...base,grade:grade(),topics};}const set=selectedSet();if(!set||set.items.length<4)throw new Error('Bitte ein Vokabelset mit mindestens 4 Einträgen auswählen.');return{...base,setId:set.id,setTitle:set.title,direction:direction(),items:set.items.slice(0,120)};}
function configLabel(c){if(c.source==='custom')return `${c.setTitle} · ${c.direction==='mixed'?'DE ↔ EN':c.direction==='en-de'?'EN → DE':'DE → EN'} · ${Math.round(c.durationSec/60)} min`;const names=c.topics.length<=2?c.topics.map(t=>TOPICS[t]?.short||t).join(' + '):`${c.topics.length} Themen`;return `Jgst. ${c.grade} · ${names} · ${Math.round(c.durationSec/60)} min`;}
function ruleLabel(c){const s=c.scoring;return `+100 richtig · ${s.wrongPenalty?`−${s.wrongPenalty} falsch`:'keine Minuspunkte'} · ${s.lockSeconds}s Pause`;}
function openSetup(mode){stopAsync();state.mode=mode;const live=mode==='liveTeacher';el.teacherRules.hidden=!live;el.setupEyebrow.textContent=live?'LIVE MIT LEHRKRAFT':'ÜBEN';el.setupTitle.textContent=live?'Live-Runde konfigurieren':'Vocab Rush einstellen';el.setupSubtitle.textContent=live?'Lehrplan-Thema oder eigenes Vokabelset auswählen. Danach entsteht der QR-Code.':'Trainiere Lehrplan-Inhalte oder genau die Vokabeln aus deinem Unterricht.';el.rulesHint.textContent=live?'Diese Regeln gelten für alle Teilnehmenden.':'Lernmodus: Erklärungen und Wiederholung nach Fehlern.';el.setupSubmit.textContent=live?'Live-Runde erstellen':'Training starten';el.setupError.textContent='';if(!live){el.lockSeconds.value='5';el.speedBonus.checked=false;}else el.speedBonus.checked=true;renderTopics();renderSets();updateSourceUI();updateScorePreview();show($('setupView'));}
function openHighscore(){stopAsync();state.mode='highscore';el.highscoreName.value=el.highscoreName.value||localStorage.getItem(NAME_KEY)||'';fillHighscoreTopics();el.highscoreError.textContent='';show($('highscoreView'));refreshBoard();}
function fillHighscoreTopics(){const g=el.highscoreGrade.value,available=availableTopics(g);const current=el.highscoreTopic.value;el.highscoreTopic.replaceChildren();available.forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=TOPICS[id].label;el.highscoreTopic.append(o);});if(available.includes(current))el.highscoreTopic.value=current;}
function openJoin(code=''){stopAsync();el.joinCode.value=String(code).replace(/\D/g,'').slice(0,6);el.joinName.value=el.joinName.value||localStorage.getItem(NAME_KEY)||'';el.joinError.textContent='';show($('joinView'));}
function resetGame(seed){clearInterval(state.timerId);clearInterval(state.progressId);clearInterval(state.lockId);state.seed=seed>>>0;state.engine=state.config.source==='custom'?createVocabEngine({...state.config,seed:state.seed}):createCurriculumEngine({...state.config,seed:state.seed});state.task=null;state.startedAt=0;state.endsAt=0;state.questionStartedAt=0;state.questionIndex=0;state.locked=false;state.finished=false;state.correct=0;state.total=0;state.streak=0;state.bestStreak=0;state.score=0;}
function beginGame(startAt,endAt){state.startedAt=startAt;state.endsAt=endAt;el.roundLabel.textContent=configLabel(state.config);el.playerLabel.textContent=state.mode==='practice'?'Üben':state.playerName||(state.mode==='highscore'?'Highscore':'Live');el.roundCodeLabel.textContent=state.roomCode||(state.mode==='highscore'?'HIGHSCORE':'SOLO');updateCounters();show($('gameView'));updateTimer();state.timerId=setInterval(updateTimer,200);if(state.mode==='livePlayer')state.progressId=setInterval(()=>submitLive(false),1800);nextTask();}
function startPractice(config,seed=randomSeed()){state.mode='practice';state.config=config;state.roomCode=null;state.playerName='';resetGame(seed);const now=Date.now();beginGame(now,now+config.durationSec*1000);}
function nextTask(){if(state.finished||Date.now()>=state.endsAt){finishGame();return;}state.locked=false;el.penaltyLock.hidden=true;state.task=state.engine.next();state.questionIndex++;state.questionStartedAt=Date.now();renderTask();}
function renderTask(){const t=state.task;el.taskNumber.textContent=`Aufgabe ${state.questionIndex}`;el.taskTopic.textContent=t.topic==='custom'?(state.config.setTitle||'Eigene Vokabeln'):(TOPICS[t.topic]?.label||t.topic);el.taskPrompt.textContent=t.prompt;el.answers.replaceChildren();el.feedback.textContent='';el.feedback.className='feedback';t.options.forEach((opt,i)=>{const b=document.createElement('button');b.type='button';b.className='answerBtn';b.innerHTML=`<span>${i+1}. </span><b></b>`;b.lastElementChild.textContent=opt;b.dataset.value=opt;b.addEventListener('click',()=>answer(opt,b));el.answers.append(b);});}
function scoreDelta(ok){const s=state.config.scoring;if(!ok)return-s.wrongPenalty;const ms=Date.now()-state.questionStartedAt,speed=s.speedBonus?Math.max(0,50-Math.floor(ms/180)):0,streak=s.streakBonus?Math.min(60,Math.max(0,state.streak)*6):0;return 100+speed+streak;}
function answer(value,button){if(state.locked||state.finished)return;state.locked=true;const accepted=state.task.accepted||[state.task.correct],ok=accepted.some(a=>norm(a)===norm(value)),delta=scoreDelta(ok);state.total++;if(ok){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);}else{state.streak=0;if(state.mode==='practice'&&state.config.source==='custom')state.engine.requeue(state.task.id);}state.score+=delta;updateCounters();for(const b of el.answers.querySelectorAll('.answerBtn')){b.disabled=true;if(accepted.some(a=>norm(a)===norm(b.dataset.value)))b.classList.add('correct');}if(!ok)button.classList.add('wrong');showFeedback(ok,delta);afterAnswer(ok);}
function norm(v){return String(v||'').trim().toLocaleLowerCase('de-DE').replace(/\s+/g,' ');}
function showFeedback(ok,delta){if(ok){el.feedback.textContent=`Richtig · +${delta} Punkte. ${state.task.explanation}`;el.feedback.className='feedback good';return;}if(state.mode==='practice'){el.feedback.textContent=`Merke dir: ${state.task.explanation}`;}else{el.feedback.textContent=`Nicht richtig. ${state.task.explanation} · ${delta} Punkte.`;}el.feedback.className='feedback bad';}
function afterAnswer(ok){const lock=!ok?Math.max(state.mode==='practice'?5:0,state.config.scoring.lockSeconds):0;if(lock>0)startLock(lock);else setTimeout(nextTask,ok?450:800);}
function startLock(sec){let r=sec;el.penaltyLock.hidden=false;el.penaltyTime.textContent=r;clearInterval(state.lockId);state.lockId=setInterval(()=>{r--;el.penaltyTime.textContent=Math.max(0,r);if(r<=0){clearInterval(state.lockId);state.lockId=null;nextTask();}},1000);}
function updateCounters(){el.correctCount.textContent=state.correct;el.streakCount.textContent=state.streak;el.scoreCount.textContent=state.score;}
function updateTimer(){const left=Math.max(0,state.endsAt-Date.now()),total=Math.max(1,state.endsAt-state.startedAt);el.timer.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.ceil((left%60000)/1000)).padStart(2,'0')}`;el.timerFill.style.width=`${Math.max(0,Math.min(100,left/total*100))}%`;if(left<=0)finishGame();}
function summary(){return{total:state.total,correct:state.correct,bestStreak:state.bestStreak,score:state.score};}
async function finishGame(){if(state.finished)return;state.finished=true;clearInterval(state.timerId);clearInterval(state.progressId);clearInterval(state.lockId);const s=summary(),acc=s.total?Math.round(s.correct/s.total*100):0;el.resultCorrect.textContent=`${s.correct} / ${s.total}`;el.resultAccuracy.textContent=`${acc} %`;el.resultStreak.textContent=s.bestStreak;el.resultScore.textContent=s.score;el.resultSummary.textContent=`${configLabel(state.config)} · ${acc}% richtig.`;el.resultBoardCard.hidden=true;if(state.mode==='practice')el.resultActionText.textContent='Falsche eigene Vokabeln wurden in der Runde bevorzugt wiederholt.';if(state.mode==='livePlayer'){await submitLive(true).catch(()=>{});try{const r=await api('roomState',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken});if(r.leaderboard?.length){el.resultBoardCard.hidden=false;renderBoard(el.resultBoard,r.leaderboard);}}catch{}el.resultActionText.textContent='Die Live-Runde ist beendet.';}if(state.mode==='highscore'){try{const r=await api('finishHighscoreAttempt',{attemptId:state.attemptId,attemptToken:state.attemptToken,summary:s});el.resultBoardCard.hidden=false;renderBoard(el.resultBoard,r.leaderboard||[]);el.resultActionText.textContent=r.personalBest?'Neuer persönlicher Highscore!':'Versuch gespeichert.';}catch(e){el.resultActionText.textContent=`Highscore konnte nicht gespeichert werden: ${e.message}`;}}show($('resultView'));}
function renderBoard(target,rows=[]){target.replaceChildren();if(!rows.length){const li=document.createElement('li');li.className='empty';li.textContent='Noch keine Einträge.';target.append(li);return;}rows.forEach((r,i)=>{const li=document.createElement('li');li.innerHTML=`<span class="rank">${r.rank||i+1}</span><span class="name"></span><span class="score">${r.score} P</span>`;li.querySelector('.name').textContent=r.name;target.append(li);});}
async function createLive(config){el.setupSubmit.disabled=true;try{const r=await api('createRoom',{config});state.mode='liveTeacher';state.config=r.config;state.roomCode=r.code;state.hostToken=r.hostToken;el.roomCode.textContent=r.code;el.teacherSummary.textContent=configLabel(r.config);el.teacherRulesSummary.textContent=ruleLabel(r.config);renderQr(r.code);show($('teacherView'));startTeacherPoll();}catch(e){el.setupError.textContent=e.message;}finally{el.setupSubmit.disabled=false;}}
function renderQr(code){el.qrBox.replaceChildren();const u=new URL(location.href);u.search='';u.searchParams.set('join',code);if(window.QRCode)new QRCode(el.qrBox,{text:u.toString(),width:100,height:100,correctLevel:QRCode.CorrectLevel.M});}
function startTeacherPoll(){clearInterval(state.pollId);pollTeacher();state.pollId=setInterval(pollTeacher,1000);}async function pollTeacher(){try{const r=await api('roomState',{code:state.roomCode,hostToken:state.hostToken});el.playerCount.textContent=`${r.playerCount} / ${r.maxPlayers} bereit`;el.roomBadge.textContent=r.status==='waiting'?'WARTET':r.status==='running'?'LÄUFT':'FERTIG';renderPlayers(r.players||[]);renderBoard(el.liveBoard,r.leaderboard||[]);el.liveBoardStatus.textContent=r.status==='waiting'?'erscheint ab dem Start':r.status==='running'?'aktueller Stand':'Endstand';if(r.status==='finished')clearInterval(state.pollId);}catch{}}
function renderPlayers(rows){el.playerList.replaceChildren();if(!rows.length){el.playerList.innerHTML='<p class="empty">Noch niemand beigetreten.</p>';return;}rows.forEach(p=>{const d=document.createElement('div');d.className='playerRow';d.innerHTML='<strong></strong><span></span>';d.firstElementChild.textContent=p.name;d.lastElementChild.textContent=p.status==='finished'?'fertig':p.status==='running'?`${p.score} P`:'bereit';el.playerList.append(d);});}
async function startLive(){el.startLiveBtn.disabled=true;try{await api('startRoom',{code:state.roomCode,hostToken:state.hostToken});await pollTeacher();}catch(e){alert(e.message);}finally{el.startLiveBtn.disabled=false;}}
async function joinLive(){const code=el.joinCode.value.replace(/\D/g,'').slice(0,6),name=el.joinName.value.trim();el.joinError.textContent='';if(code.length!==6){el.joinError.textContent='Bitte einen 6-stelligen Code eingeben.';return;}if(!name){el.joinError.textContent='Bitte einen kurzen Namen eingeben.';return;}el.joinBtn.disabled=true;try{const r=await api('joinRoom',{code,name});localStorage.setItem(NAME_KEY,name);state.mode='livePlayer';state.roomCode=r.code;state.playerId=r.playerId;state.playerToken=r.playerToken;state.playerName=r.name;state.config=r.config;el.waitingName.textContent=`${r.name}, du bist bereit.`;el.waitingCode.textContent=code;show($('waitingView'));startPlayerPoll();}catch(e){el.joinError.textContent=e.message;}finally{el.joinBtn.disabled=false;}}
function startPlayerPoll(){clearInterval(state.pollId);pollPlayer();state.pollId=setInterval(pollPlayer,900);}async function pollPlayer(){try{const r=await api('roomState',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken});if(r.status==='running'){clearInterval(state.pollId);state.config=r.config;resetGame(r.seed);startCountdownTo(r.startsAtMs,r.endsAtMs);}else if(r.status==='finished'){clearInterval(state.pollId);el.waitingName.textContent='Diese Runde ist bereits beendet.';}}catch{}}
function startCountdownTo(startAt,endAt){const tick=()=>{const ms=startAt-Date.now();if(ms<=0){clearInterval(state.countdownId);el.countdown.hidden=true;beginGame(startAt,endAt);return;}el.countdown.hidden=false;el.countdown.textContent=Math.max(1,Math.ceil(ms/1000));};tick();state.countdownId=setInterval(tick,150);}async function submitLive(finished){if(!state.roomCode||!state.playerId)return;return api('submitLive',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken,summary:summary(),finished});}
async function refreshBoard(){const g=el.highscoreGrade.value,t=el.highscoreTopic.value;el.boardLabel.textContent=`Jgst. ${g} · ${TOPICS[t]?.label||''}`;try{const r=await api('leaderboard',{grade:g,topic:t});renderBoard(el.highscoreBoard,r.leaderboard||[]);}catch{renderBoard(el.highscoreBoard,[]);}}
async function startHighscore(){const name=el.highscoreName.value.trim();if(!name){el.highscoreError.textContent='Bitte einen kurzen Namen eingeben.';return;}el.startHighscoreBtn.disabled=true;try{const r=await api('createHighscoreAttempt',{name,playerKey:playerKey(),grade:el.highscoreGrade.value,topic:el.highscoreTopic.value});localStorage.setItem(NAME_KEY,name);state.mode='highscore';state.playerName=name;state.attemptId=r.attemptId;state.attemptToken=r.attemptToken;state.config=r.config;resetGame(r.seed);beginGame(r.startsAtMs,r.endsAtMs);}catch(e){el.highscoreError.textContent=e.message;}finally{el.startHighscoreBtn.disabled=false;}}
function newSet(){state.editorItems=[];el.setTitle.value='';el.pasteArea.value='';el.importStatus.textContent='';renderEditor();show($('setEditorView'));}
function parsePaste(){const lines=el.pasteArea.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),items=[];for(const line of lines){let parts=line.split(/\t|\s*=\s*|\s+[-–—]\s+|\s*:\s*/);if(parts.length<2)continue;const source=parts.shift().trim(),targets=parts.join(':').split(/\s*[;,/]\s*/).map(x=>x.trim()).filter(Boolean);if(source&&targets.length)items.push({source,targets});}state.editorItems=dedupe(items);renderEditor();el.importStatus.textContent=`${state.editorItems.length} Einträge aus Text erkannt.`;}
function dedupe(items){const map=new Map();for(const raw of items){const source=String(raw.source||'').trim(),targets=[...new Set((raw.targets||[]).map(x=>String(x).trim()).filter(Boolean))];if(!source||!targets.length)continue;const k=norm(source);if(map.has(k))map.get(k).targets=[...new Set([...map.get(k).targets,...targets])];else map.set(k,{source,targets});}return[...map.values()].slice(0,120);}
function renderEditor(){el.itemEditor.replaceChildren();state.editorItems.forEach((item,i)=>{const row=document.createElement('div');row.className='itemRow';const a=document.createElement('input');a.value=item.source;a.placeholder='Englisch';const b=document.createElement('input');b.value=item.targets.join('; ');b.placeholder='Deutsch (mehrere mit ;)';const del=document.createElement('button');del.type='button';del.textContent='×';a.addEventListener('input',()=>item.source=a.value);b.addEventListener('input',()=>item.targets=b.value.split(';').map(x=>x.trim()).filter(Boolean));del.addEventListener('click',()=>{state.editorItems.splice(i,1);renderEditor();});row.append(a,b,del);el.itemEditor.append(row);});el.itemCount.textContent=`${state.editorItems.length} Einträge`;}
function saveSet(){const title=el.setTitle.value.trim(),items=dedupe(state.editorItems);el.setError.textContent='';if(!title){el.setError.textContent='Bitte einen Namen für das Set eingeben.';return;}if(items.length<4){el.setError.textContent='Mindestens 4 Vokabeln sind nötig.';return;}const sets=getSets(),id=`set_${Date.now().toString(36)}`,set={id,title,items,createdAt:Date.now()};sets.unshift(set);saveSets(sets);state.setId=id;openSetup(state.mode==='liveTeacher'?'liveTeacher':'practice');document.querySelector('input[name="source"][value="custom"]').checked=true;updateSourceUI();}
async function fileToDataUrl(file){if(file.size>8*1024*1024)throw new Error('Das Bild ist zu groß. Bitte maximal 8 MB verwenden.');const raw=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=raw;});const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.84);}
async function importPhoto(file){if(!file)return;el.importStatus.textContent='Foto wird vorbereitet und Vokabeln werden erkannt …';el.photoImportBtn.disabled=true;try{const imageDataUrl=await fileToDataUrl(file),r=await api('extractVocabulary',{imageDataUrl});state.editorItems=dedupe(r.items||[]);if(!el.setTitle.value&&r.suggestedTitle)el.setTitle.value=r.suggestedTitle;renderEditor();const review=(r.items||[]).filter(x=>x.needsReview).length;el.importStatus.textContent=`${state.editorItems.length} Vokabeln erkannt${review?` · ${review} bitte besonders prüfen`:''}. Bitte Liste vor dem Speichern kontrollieren.`;}catch(e){el.importStatus.textContent=`Fotoimport fehlgeschlagen: ${e.message}`;}finally{el.photoImportBtn.disabled=false;el.photoInput.value='';}}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.open;if(m==='practice')openSetup('practice');else if(m==='live')openSetup('liveTeacher');else openHighscore();}));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>{stopAsync();show($('homeView'));}));document.querySelectorAll('input[name="source"]').forEach(i=>i.addEventListener('change',updateSourceUI));document.querySelectorAll('input[name="grade"]').forEach(i=>i.addEventListener('change',renderTopics));[el.wrongPenalty,el.lockSeconds].forEach(x=>x.addEventListener('change',updateScorePreview));
el.setupForm.addEventListener('submit',e=>{e.preventDefault();el.setupError.textContent='';try{const c=gatherConfig();if(state.mode==='liveTeacher')createLive(c);else startPractice(c);}catch(err){el.setupError.textContent=err.message;}});el.newSetBtn.addEventListener('click',newSet);el.backToSetup.addEventListener('click',()=>openSetup(state.mode==='liveTeacher'?'liveTeacher':'practice'));el.pasteImportBtn.addEventListener('click',()=>el.pasteArea.focus());el.parsePasteBtn.addEventListener('click',parsePaste);el.addRowBtn.addEventListener('click',()=>{state.editorItems.push({source:'',targets:[]});renderEditor();});el.saveSetBtn.addEventListener('click',saveSet);el.photoImportBtn.addEventListener('click',()=>el.photoInput.click());el.photoInput.addEventListener('change',()=>importPhoto(el.photoInput.files?.[0]));
el.quickJoinCode.addEventListener('input',()=>el.quickJoinCode.value=el.quickJoinCode.value.replace(/\D/g,'').slice(0,6));el.quickJoinBtn.addEventListener('click',()=>openJoin(el.quickJoinCode.value));el.joinCode.addEventListener('input',()=>el.joinCode.value=el.joinCode.value.replace(/\D/g,'').slice(0,6));el.joinBtn.addEventListener('click',joinLive);el.startLiveBtn.addEventListener('click',startLive);el.copyLinkBtn.addEventListener('click',async()=>{const u=new URL(location.href);u.search='';u.searchParams.set('join',state.roomCode);await navigator.clipboard?.writeText(u.toString());el.copyLinkBtn.textContent='Link kopiert';setTimeout(()=>el.copyLinkBtn.textContent='Beitrittslink kopieren',1200);});el.highscoreGrade.addEventListener('change',()=>{fillHighscoreTopics();refreshBoard();});el.highscoreTopic.addEventListener('change',refreshBoard);el.refreshBoardBtn.addEventListener('click',refreshBoard);el.startHighscoreBtn.addEventListener('click',startHighscore);el.homeBtn.addEventListener('click',()=>{stopAsync();show($('homeView'));});el.sameRoundBtn.addEventListener('click',()=>{if(state.mode==='practice')startPractice(state.config,state.seed);else if(state.mode==='highscore')openHighscore();else show($('homeView'));});el.newRoundBtn.addEventListener('click',()=>{if(state.mode==='practice')startPractice(state.config,randomSeed());else if(state.mode==='highscore')openHighscore();else show($('homeView'));});document.addEventListener('keydown',e=>{if($('gameView').hidden||state.locked||state.finished)return;const n=Number(e.key);if(n>=1&&n<=4)el.answers.querySelectorAll('.answerBtn')[n-1]?.click();});
renderTopics();renderSets();updateSourceUI();updateScorePreview();fillHighscoreTopics();const join=new URLSearchParams(location.search).get('join');if(join)openJoin(join);
})();