(() => {
'use strict';

const SETS_KEY='gradecrew-vocabrush-sets-v1';
const SELECTED_KEY='gradecrew-vocabrush-selected-sets-v1';
const VIRTUAL_ID='__gradecrew_combined_selection__';
const API_URL='https://europe-west1-hausaufgabe-staging.cloudfunctions.net/vocabRushApi';
const MAX_SETS=30,MAX_IMPORT_PAGES=20;
const $=id=>document.getElementById(id);
const norm=v=>String(v||'').trim().toLocaleLowerCase('de-DE').replace(/\s+/g,' ');
let selectedIds=new Set();
let editingSet=null;
let importPages=[];
let cropPageId=null;
let cropStart=null;
let cropRect=null;

function readAllSets(){try{const v=JSON.parse(localStorage.getItem(SETS_KEY)||'[]');return Array.isArray(v)?v:[];}catch{return[];}}
function realSets(){return readAllSets().filter(s=>s&&s.id!==VIRTUAL_ID&&!s.virtual);}
function writeRealSets(sets){localStorage.setItem(SETS_KEY,JSON.stringify(sets.slice(0,MAX_SETS)));}
function readSelected(){try{const v=JSON.parse(sessionStorage.getItem(SELECTED_KEY)||'[]');return Array.isArray(v)?v:[];}catch{return[];}}
function saveSelected(){sessionStorage.setItem(SELECTED_KEY,JSON.stringify([...selectedIds]));}
function dedupeItems(items){const map=new Map();for(const raw of items||[]){const source=String(raw?.source||'').trim();const targets=[...new Set((raw?.targets||[]).map(v=>String(v).trim()).filter(Boolean))];if(!source||!targets.length)continue;const k=norm(source);if(map.has(k))map.get(k).targets=[...new Set([...map.get(k).targets,...targets])];else map.set(k,{source,targets});}return[...map.values()].slice(0,120);}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function refreshNativeSets(){const custom=document.querySelector('input[name="source"][value="custom"]');if(custom){custom.dispatchEvent(new Event('change',{bubbles:true}));}}

function ensureLibrary(){const custom=$('customSetup'),native=$('setList'),newBtn=$('newSetBtn');if(!custom||!native||!newBtn||$('vrLibrary'))return;native.classList.add('vrNativeSetList');const wrap=document.createElement('div');wrap.id='vrLibrary';wrap.className='vrLibrary';wrap.innerHTML=`
  <div class="vrLibraryHead"><div><strong>Meine Vokabelsets</strong><small>Ein Set, mehrere Units oder alle Sets gemeinsam trainieren.</small></div><button id="vrManageSets" class="secondary" type="button">Verwalten</button></div>
  <div class="vrSelectionTools"><button id="vrSelectAll" class="textBtn" type="button">Alle auswählen</button><button id="vrSelectNone" class="textBtn" type="button">Auswahl leeren</button><span id="vrSelectionSummary"></span></div>
  <div id="vrSetChoices" class="vrSetChoices"></div>`;
native.before(wrap);newBtn.textContent='+ Neues Vokabelset';
$('vrSelectAll').addEventListener('click',()=>{selectedIds=new Set(realSets().map(s=>s.id));saveSelected();renderLibrary();});
$('vrSelectNone').addEventListener('click',()=>{selectedIds.clear();saveSelected();renderLibrary();});
$('vrManageSets').addEventListener('click',()=>openManager());
const obs=new MutationObserver(()=>renderLibrary());obs.observe(native,{childList:true,subtree:true});
renderLibrary();
}
function syncSelected(){const sets=realSets(),valid=new Set(sets.map(s=>s.id));selectedIds=new Set([...selectedIds].filter(id=>valid.has(id)));if(!selectedIds.size&&sets.length)selectedIds.add(sets[0].id);saveSelected();}
function renderLibrary(){const host=$('vrSetChoices');if(!host)return;syncSelected();const sets=realSets();host.replaceChildren();if(!sets.length){host.innerHTML='<p class="empty">Noch kein Set vorhanden. Lege z. B. „Unit 1“ als erstes Vokabelset an.</p>';const sum=$('vrSelectionSummary');if(sum)sum.textContent='0 Sets';return;}for(const set of sets){const label=document.createElement('label');label.className='vrSetChoice';const input=document.createElement('input');input.type='checkbox';input.checked=selectedIds.has(set.id);input.addEventListener('change',()=>{if(input.checked)selectedIds.add(set.id);else selectedIds.delete(set.id);saveSelected();renderLibrary();});const box=document.createElement('span');box.innerHTML=`<b>${escapeHtml(set.title)}</b><small>${set.items?.length||0} Vokabeln</small>`;label.append(input,box);host.append(label);}const chosen=sets.filter(s=>selectedIds.has(s.id));const items=dedupeItems(chosen.flatMap(s=>s.items||[]));$('vrSelectionSummary').textContent=chosen.length?`${chosen.length} Set${chosen.length===1?'':'s'} · ${items.length} eindeutige Vokabeln`:'Noch kein Set ausgewählt';}

function ensureManager(){if($('vrManagerDialog'))return;const d=document.createElement('dialog');d.id='vrManagerDialog';d.className='vrDialog';d.innerHTML=`<form method="dialog" class="vrDialogCard"><div class="vrDialogHead"><div><p class="eyebrow">MEINE VOKABELN</p><h2>Vokabelsets verwalten</h2><p>Sets bearbeiten, duplizieren oder löschen. Für Übungen kannst du anschließend mehrere Sets gleichzeitig auswählen.</p></div><button value="cancel" class="vrClose" aria-label="Schließen">×</button></div><div id="vrManagerList" class="vrManagerList"></div><div class="vrDialogFoot"><button value="cancel" class="secondary">Fertig</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>{editingSet=null;renderLibrary();refreshNativeSets();});}
function openManager(){ensureManager();renderManager();$('vrManagerDialog').showModal();}
function renderManager(){const host=$('vrManagerList');if(!host)return;const sets=realSets();host.replaceChildren();if(!sets.length){host.innerHTML='<p class="empty">Noch keine Vokabelsets gespeichert.</p>';return;}sets.forEach(set=>{const row=document.createElement('div');row.className='vrManagerRow';row.innerHTML=`<div><strong>${escapeHtml(set.title)}</strong><small>${set.items?.length||0} Vokabeln</small></div><div class="vrManagerActions"><button class="secondary" type="button" data-act="edit">Bearbeiten</button><button class="secondary" type="button" data-act="copy">Duplizieren</button><button class="vrDanger" type="button" data-act="delete">Löschen</button></div>`;row.querySelector('[data-act="edit"]').addEventListener('click',()=>openSetEditor(set.id));row.querySelector('[data-act="copy"]').addEventListener('click',()=>duplicateSet(set.id));row.querySelector('[data-act="delete"]').addEventListener('click',()=>deleteSet(set.id));host.append(row);});}
function duplicateSet(id){const sets=realSets(),src=sets.find(s=>s.id===id);if(!src)return;if(sets.length>=MAX_SETS){alert(`Maximal ${MAX_SETS} Sets sind im Prototyp vorgesehen.`);return;}const copy={...src,id:`set_${Date.now().toString(36)}`,title:`${src.title} · Kopie`,items:(src.items||[]).map(x=>({source:x.source,targets:[...(x.targets||[])]})),createdAt:Date.now()};sets.unshift(copy);writeRealSets(sets);selectedIds.add(copy.id);saveSelected();renderManager();renderLibrary();refreshNativeSets();}
function deleteSet(id){const sets=realSets(),set=sets.find(s=>s.id===id);if(!set)return;if(!confirm(`„${set.title}“ wirklich löschen?\n\nDie ${set.items?.length||0} Vokabeln werden nur aus deiner lokalen Vocab-Rush-Bibliothek entfernt.`))return;writeRealSets(sets.filter(s=>s.id!==id));selectedIds.delete(id);saveSelected();renderManager();renderLibrary();refreshNativeSets();}
function ensureEditDialog(){if($('vrEditDialog'))return;const d=document.createElement('dialog');d.id='vrEditDialog';d.className='vrDialog';d.innerHTML=`<div class="vrDialogCard vrEditCard"><div class="vrDialogHead"><div><p class="eyebrow">VOKABELSET</p><h2>Set bearbeiten</h2></div><button id="vrEditClose" class="vrClose" type="button">×</button></div><label class="field"><span>Name</span><input id="vrEditTitle" maxlength="80"></label><div class="panelHead"><div><strong>Vokabeln</strong><small id="vrEditCount"></small></div><button id="vrEditAdd" class="textBtn" type="button">+ Zeile</button></div><div id="vrEditRows" class="itemEditor"></div><p id="vrEditError" class="error"></p><div class="vrDialogFoot"><button id="vrEditCancel" class="secondary" type="button">Abbrechen</button><button id="vrEditSave" class="primary" type="button">Änderungen speichern</button></div></div>`;document.body.append(d);$('vrEditClose').addEventListener('click',()=>d.close());$('vrEditCancel').addEventListener('click',()=>d.close());$('vrEditAdd').addEventListener('click',()=>{editingSet.items.push({source:'',targets:[]});renderEditRows();});$('vrEditSave').addEventListener('click',saveEditedSet);}
function openSetEditor(id){const set=realSets().find(s=>s.id===id);if(!set)return;ensureEditDialog();editingSet={id:set.id,title:set.title,items:(set.items||[]).map(x=>({source:x.source,targets:[...(x.targets||[])]}))};$('vrEditTitle').value=editingSet.title;$('vrEditError').textContent='';renderEditRows();$('vrEditDialog').showModal();}
function renderEditRows(){const host=$('vrEditRows');host.replaceChildren();editingSet.items.forEach((item,i)=>{const row=document.createElement('div');row.className='itemRow';const a=document.createElement('input');a.value=item.source;a.placeholder='Englisch';const b=document.createElement('input');b.value=item.targets.join('; ');b.placeholder='Deutsch (mehrere mit ;)';const del=document.createElement('button');del.type='button';del.textContent='×';a.addEventListener('input',()=>item.source=a.value);b.addEventListener('input',()=>item.targets=b.value.split(';').map(x=>x.trim()).filter(Boolean));del.addEventListener('click',()=>{editingSet.items.splice(i,1);renderEditRows();});row.append(a,b,del);host.append(row);});$('vrEditCount').textContent=`${editingSet.items.length} Einträge`;}
function saveEditedSet(){if(!editingSet)return;const title=$('vrEditTitle').value.trim(),items=dedupeItems(editingSet.items);if(!title){$('vrEditError').textContent='Bitte einen Namen eingeben.';return;}if(items.length<4){$('vrEditError').textContent='Mindestens 4 vollständige Vokabeln sind nötig.';return;}const sets=realSets(),i=sets.findIndex(s=>s.id===editingSet.id);if(i<0)return;sets[i]={...sets[i],title,items,updatedAt:Date.now()};writeRealSets(sets);$('vrEditDialog').close();renderManager();renderLibrary();refreshNativeSets();}

function prepareCombinedSelection(){const source=document.querySelector('input[name="source"]:checked')?.value;if(source!=='custom')return true;const sets=realSets().filter(s=>selectedIds.has(s.id));if(!sets.length){const err=$('setupError');if(err)err.textContent='Bitte mindestens ein Vokabelset auswählen.';return false;}const merged=dedupeItems(sets.flatMap(s=>s.items||[]));if(merged.length<4){const err=$('setupError');if(err)err.textContent='Die gewählten Sets enthalten zusammen weniger als 4 nutzbare Vokabeln.';return false;}const title=sets.length===1?sets[0].title:sets.length<=3?sets.map(s=>s.title).join(' + '):`${sets.length} Sets · gemischt`;
const virtual={id:VIRTUAL_ID,title,items:merged,createdAt:Date.now(),virtual:true};const raw=readAllSets().filter(s=>s?.id!==VIRTUAL_ID);localStorage.setItem(SETS_KEY,JSON.stringify([virtual,...raw]));refreshNativeSets();const card=[...document.querySelectorAll('#setList .setCard')].find(x=>x.querySelector('span')?.textContent===title);if(card)card.click();setTimeout(()=>{localStorage.setItem(SETS_KEY,JSON.stringify(raw));},0);return true;}

function ensureImporter(){const editor=$('setEditorView'),tabs=editor?.querySelector('.importTabs');if(!editor||!tabs||$('vrImportPanel'))return;const photoBtn=$('photoImportBtn'),photoInput=$('photoInput');if(photoBtn)photoBtn.textContent='📷 Foto aufnehmen';if(photoInput){photoInput.setAttribute('accept','image/jpeg,image/png,image/webp');photoInput.addEventListener('change',e=>{e.stopImmediatePropagation();const files=[...(photoInput.files||[])];photoInput.value='';addImportFiles(files);},{capture:true});}
const panel=document.createElement('div');panel.id='vrImportPanel';panel.className='vrImportPanel';panel.innerHTML=`<div id="vrDropZone" class="vrDropZone" tabindex="0"><strong>Bilder, Screenshots oder PDFs hinzufügen</strong><span>Mehrere Dateien und Seiten bleiben erhalten. Du kannst vor dem Auslesen pro Seite einen Ausschnitt wählen.</span><div class="vrDropActions"><button id="vrChooseFiles" class="secondary" type="button">🖼 Dateien auswählen</button></div><input id="vrMultiInput" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.pdf" multiple hidden></div><div id="vrPageQueue" class="vrPageQueue"></div><button id="vrProcessPages" class="primary full" type="button" hidden>Seiten auslesen</button><small class="vrImportHelp">Tipp: Ziehe mehrere Screenshots direkt hierher. Bereits ausgelesene Seiten bleiben sichtbar; neue Seiten werden beim nächsten Durchlauf zusätzlich verarbeitet.</small>`;tabs.after(panel);
const input=$('vrMultiInput'),zone=$('vrDropZone');$('vrChooseFiles').addEventListener('click',()=>input.click());input.addEventListener('change',()=>{const files=[...(input.files||[])];input.value='';addImportFiles(files);});['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('isDragging');}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('isDragging');}));zone.addEventListener('drop',e=>addImportFiles([...e.dataTransfer.files]));$('vrProcessPages').addEventListener('click',processImportPages);ensureCropDialog();}
async function addImportFiles(files){if(!files.length)return;const status=$('importStatus');status.textContent='Dateien werden vorbereitet …';for(const file of files){if(importPages.length>=MAX_IMPORT_PAGES)break;try{if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){await addPdf(file);}else if(/^image\/(jpeg|png|webp)$/i.test(file.type)){const dataUrl=await readDataUrl(file);importPages.push({id:crypto.randomUUID?.()||`${Date.now()}_${Math.random()}`,name:file.name||'Foto',dataUrl,cropDataUrl:null,processed:false,status:'bereit'});}else{status.textContent=`„${file.name}“ wurde übersprungen. Unterstützt werden JPG, PNG, WebP und PDF.`;}}catch(err){status.textContent=`${file.name}: ${err.message}`;}}renderImportQueue();if(importPages.length)status.textContent=`${importPages.length} Seite${importPages.length===1?'':'n'} vorbereitet. Ausschnitt prüfen oder direkt auslesen.`;}
function readDataUrl(file){if(file.size>15*1024*1024)return Promise.reject(new Error('Datei ist größer als 15 MB.'));return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Datei konnte nicht gelesen werden.'));r.readAsDataURL(file);});}
async function addPdf(file){const status=$('importStatus');status.textContent=`PDF „${file.name}“ wird in Seiten zerlegt …`;let pdfjs;try{pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';}catch{throw new Error('PDF-Unterstützung konnte nicht geladen werden. Bitte alternativ Screenshots verwenden.');}const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const remaining=MAX_IMPORT_PAGES-importPages.length,count=Math.min(pdf.numPages,remaining);for(let n=1;n<=count;n++){const page=await pdf.getPage(n),viewport=page.getViewport({scale:1.45}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;importPages.push({id:crypto.randomUUID?.()||`${Date.now()}_${n}_${Math.random()}`,name:`${file.name} · Seite ${n}`,dataUrl:canvas.toDataURL('image/jpeg',.9),cropDataUrl:null,processed:false,status:'bereit'});}if(pdf.numPages>count)status.textContent=`PDF hat ${pdf.numPages} Seiten. Für einen Import sind aktuell maximal ${MAX_IMPORT_PAGES} Seiten vorgesehen.`;}
function renderImportQueue(){const host=$('vrPageQueue');if(!host)return;host.replaceChildren();for(const page of importPages){const card=document.createElement('div');card.className='vrPageCard'+(page.processed?' isProcessed':'');card.innerHTML=`<img alt=""><div class="vrPageInfo"><strong></strong><small>${page.processed?'✓ ausgelesen':'bereit zum Auslesen'}</small></div><div class="vrPageActions"><button class="secondary" type="button" data-crop>Ausschnitt</button><button class="vrDanger" type="button" data-remove>Entfernen</button></div>`;card.querySelector('img').src=page.cropDataUrl||page.dataUrl;card.querySelector('.vrPageInfo strong').textContent=page.name;card.querySelector('[data-crop]').addEventListener('click',()=>openCrop(page.id));card.querySelector('[data-remove]').addEventListener('click',()=>{importPages=importPages.filter(p=>p.id!==page.id);renderImportQueue();});host.append(card);}const pending=importPages.filter(p=>!p.processed).length,btn=$('vrProcessPages');btn.hidden=!pending;btn.textContent=pending===1?'1 neue Seite auslesen':`${pending} neue Seiten auslesen`;}
async function normalizedImage(dataUrl){const img=await loadImage(dataUrl),max=1800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.86);}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Bild konnte nicht verarbeitet werden.'));img.src=src;});}
async function callExtract(imageDataUrl){const c=new AbortController(),timer=setTimeout(()=>c.abort(),90000);try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'extractVocabulary',payload:{imageDataUrl}}),signal:c.signal});const b=await r.json().catch(()=>null);if(!r.ok||!b?.ok)throw new Error(b?.error?.message||`Backend ${r.status}`);return b.data;}catch(err){if(err.name==='AbortError')throw new Error('Die Erkennung dauert zu lange.');throw err;}finally{clearTimeout(timer);}}
function editorItemsFromDom(){return[...document.querySelectorAll('#itemEditor .itemRow')].map(row=>{const inputs=row.querySelectorAll('input');return{source:inputs[0]?.value||'',targets:String(inputs[1]?.value||'').split(';').map(x=>x.trim()).filter(Boolean)};});}
async function processImportPages(){const pending=importPages.filter(p=>!p.processed);if(!pending.length)return;const btn=$('vrProcessPages'),status=$('importStatus');btn.disabled=true;let merged=dedupeItems(editorItemsFromDom()),done=0,review=0;try{for(const page of pending){status.textContent=`Seite ${done+1} von ${pending.length} wird erkannt: ${page.name}`;const imageDataUrl=await normalizedImage(page.cropDataUrl||page.dataUrl),r=await callExtract(imageDataUrl);merged=dedupeItems([...merged,...(r.items||[])]);review+=(r.items||[]).filter(x=>x.needsReview).length;if(!$('setTitle').value&&r.suggestedTitle)$('setTitle').value=r.suggestedTitle;page.processed=true;page.status='ausgelesen';done++;renderImportQueue();}const paste=$('pasteArea');paste.value=merged.map(x=>`${x.source} = ${x.targets.join('; ')}`).join('\n');$('parsePasteBtn').click();status.textContent=`${done} Seite${done===1?'':'n'} hinzugefügt · ${merged.length} eindeutige Vokabeln insgesamt${review?` · ${review} neue Einträge bitte besonders prüfen`:''}.`;renderImportQueue();}catch(err){status.textContent=`Import gestoppt: ${err.message} Bereits erfolgreich erkannte Seiten bleiben erhalten.`;}finally{btn.disabled=false;}}

function ensureCropDialog(){if($('vrCropDialog'))return;const d=document.createElement('dialog');d.id='vrCropDialog';d.className='vrDialog';d.innerHTML=`<div class="vrDialogCard vrCropCard"><div class="vrDialogHead"><div><p class="eyebrow">AUSSCHNITT</p><h2>Vokabelbereich auswählen</h2><p>Ziehe ein Rechteck um den Bereich, der ausgelesen werden soll. Ohne Auswahl wird die ganze Seite verwendet.</p></div><button id="vrCropClose" class="vrClose" type="button">×</button></div><div id="vrCropStage" class="vrCropStage"><img id="vrCropImage" alt="Seite"><div id="vrCropSelection" class="vrCropSelection" hidden></div></div><div class="vrDialogFoot"><button id="vrCropReset" class="secondary" type="button">Ganze Seite</button><button id="vrCropSave" class="primary" type="button">Ausschnitt übernehmen</button></div></div>`;document.body.append(d);$('vrCropClose').addEventListener('click',()=>d.close());$('vrCropReset').addEventListener('click',()=>{cropRect=null;$('vrCropSelection').hidden=true;});$('vrCropSave').addEventListener('click',saveCrop);const stage=$('vrCropStage');stage.addEventListener('pointerdown',cropDown);stage.addEventListener('pointermove',cropMove);stage.addEventListener('pointerup',cropUp);stage.addEventListener('pointercancel',cropUp);}
function openCrop(id){const page=importPages.find(p=>p.id===id);if(!page)return;cropPageId=id;cropRect=null;$('vrCropSelection').hidden=true;$('vrCropImage').src=page.dataUrl;$('vrCropDialog').showModal();}
function cropPoint(e){const r=$('vrCropStage').getBoundingClientRect();return{x:Math.max(0,Math.min(r.width,e.clientX-r.left)),y:Math.max(0,Math.min(r.height,e.clientY-r.top)),w:r.width,h:r.height};}
function cropDown(e){if(e.target.closest('button'))return;e.preventDefault();const p=cropPoint(e);cropStart=p;cropRect={x:p.x,y:p.y,width:0,height:0,stageW:p.w,stageH:p.h};$('vrCropStage').setPointerCapture?.(e.pointerId);drawCrop();}
function cropMove(e){if(!cropStart)return;const p=cropPoint(e),x=Math.min(cropStart.x,p.x),y=Math.min(cropStart.y,p.y);cropRect={x,y,width:Math.abs(p.x-cropStart.x),height:Math.abs(p.y-cropStart.y),stageW:p.w,stageH:p.h};drawCrop();}
function cropUp(){cropStart=null;}
function drawCrop(){const s=$('vrCropSelection');if(!cropRect||cropRect.width<2||cropRect.height<2){s.hidden=true;return;}s.hidden=false;Object.assign(s.style,{left:`${cropRect.x}px`,top:`${cropRect.y}px`,width:`${cropRect.width}px`,height:`${cropRect.height}px`});}
async function saveCrop(){const page=importPages.find(p=>p.id===cropPageId);if(!page)return;if(!cropRect||cropRect.width<12||cropRect.height<12){page.cropDataUrl=null;}else{const img=await loadImage(page.dataUrl),sx=img.naturalWidth/cropRect.stageW,sy=img.naturalHeight/cropRect.stageH,x=Math.round(cropRect.x*sx),y=Math.round(cropRect.y*sy),w=Math.max(1,Math.round(cropRect.width*sx)),h=Math.max(1,Math.round(cropRect.height*sy)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,x,y,w,h,0,0,w,h);page.cropDataUrl=canvas.toDataURL('image/jpeg',.9);}page.processed=false;page.status='bereit';$('vrCropDialog').close();renderImportQueue();$('importStatus').textContent='Ausschnitt geändert. Diese Seite wird beim nächsten Auslesen neu verarbeitet.';}

function init(){selectedIds=new Set(readSelected());ensureLibrary();ensureManager();ensureEditDialog();ensureImporter();document.querySelectorAll('input[name="source"]').forEach(x=>x.addEventListener('change',()=>setTimeout(renderLibrary,0)));document.querySelectorAll('[data-open]').forEach(x=>x.addEventListener('click',()=>setTimeout(renderLibrary,0)));const form=$('setupForm');if(form)form.addEventListener('submit',e=>{if(document.querySelector('input[name="source"]:checked')?.value==='custom'&&!prepareCombinedSelection()){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});}
init();
})();
