#include "PizzaKitchen.h"
#include "PizzaHUD.h"
#include "Components/CapsuleComponent.h"
#include "Components/SceneComponent.h"
#include "GameFramework/FloatingPawnMovement.h"
#include "Kismet/GameplayStatics.h"
#include "Camera/CameraActor.h"
#include "Camera/CameraComponent.h"
#include "Engine/World.h"
#include "Components/InputComponent.h"
#include "Engine/GameViewportClient.h"
#include "Widgets/SViewport.h"
#include "GameFramework/PlayerInput.h"
#include "EngineUtils.h"
namespace {void ClearArt(AActor* A){auto Components=A->GetInstanceComponents();for(auto* C:Components)if(C&&C!=A->GetRootComponent())C->DestroyComponent();}FString Frac(PizzaRules::Rational R){return FString(UTF8_TO_TCHAR(PizzaRules::Format(R).c_str()));}}
APizzaArena::APizzaArena(){RootComponent=CreateDefaultSubobject<USceneComponent>(TEXT("KitchenRoot"));}
void APizzaArena::OnConstruction(const FTransform& T){Super::OnConstruction(T);ClearArt(this);KitchenArt::Room(this,RootComponent);}
APizzaVisual::APizzaVisual(){RootComponent=CreateDefaultSubobject<USceneComponent>(TEXT("PizzaRoot"));}
void APizzaVisual::SetPizza(const FKitchenPizza& P){
 ClearArt(this);KitchenArt::Cylinder(this,RootComponent,TEXT("Plate"),FVector(0,0,-3),FVector(.96,.96,.045),FLinearColor(.94,.91,.77));
 const auto Pieces=P.Cuts.Pieces();
 for(int I=0;I<static_cast<int>(Pieces.size());++I){
  if(P.Plated&&!(P.Selection&(1u<<I)))continue;
  const auto& Piece=Pieces[I];const auto Center=PizzaRules::PizzaCuts::Center(Piece);
  const FVector Direction=FVector(Center.X,Center.Y,0).GetSafeNormal();
  FVector Offset=Pieces.size()>1?Direction*1.4f:FVector::ZeroVector;
  if(!P.Plated&&(P.Selection&(1u<<I)))Offset+=Direction*7+FVector(0,0,4);
  TArray<FVector2D> Shape,SauceShape,CheeseShape;for(const auto& Point:Piece)Shape.Add(FVector2D(Point.X,Point.Y));for(const auto& Point:PizzaRules::PizzaCuts::Inset(Piece,37./42))SauceShape.Add(FVector2D(Point.X,Point.Y));for(const auto& Point:PizzaRules::PizzaCuts::Inset(Piece,34./42))CheeseShape.Add(FVector2D(Point.X,Point.Y));
  KitchenArt::Polygon(this,RootComponent,*FString::Printf(TEXT("Crust%d"),I),Offset,Shape,42,6,FLinearColor(P.Baked?.66:.84,P.Baked?.35:.64,.22));
  if(P.Ingredients&1)KitchenArt::Polygon(this,RootComponent,*FString::Printf(TEXT("Sauce%d"),I),Offset+FVector(0,0,6),SauceShape,42,1,FLinearColor(.65,.12,.06));
  if(P.Ingredients&2)KitchenArt::Polygon(this,RootComponent,*FString::Printf(TEXT("Cheese%d"),I),Offset+FVector(0,0,7),CheeseShape,42,1,FLinearColor(.96,.73,.29));
  if(P.Ingredients&4)for(int J=0;J<11;++J){const float Angle=J*2.39996f,Radius=12+(J%3)*8;const FVector Topping(FMath::Cos(Angle)*Radius,FMath::Sin(Angle)*Radius,11);if(!PizzaRules::PizzaCuts::Contains(Piece,{Topping.X/42,Topping.Y/42}))continue;FVector Pos=Offset+Topping;KitchenArt::Cylinder(this,RootComponent,TEXT("MushroomStem"),Pos,FVector(.035,.035,.05),FLinearColor(.88,.8,.63));KitchenArt::Sphere(this,RootComponent,TEXT("MushroomCap"),Pos+FVector(0,0,3),FVector(.12,.12,.05),FLinearColor(.55,.35,.18));}
 }
}

AKitchenChef::AKitchenChef(){PrimaryActorTick.bCanEverTick=true;Body=CreateDefaultSubobject<UCapsuleComponent>(TEXT("ChefCollision"));Body->InitCapsuleSize(28,73);Body->SetCollisionProfileName(TEXT("Pawn"));RootComponent=Body;Movement=CreateDefaultSubobject<UFloatingPawnMovement>(TEXT("ChefMovement"));Movement->UpdatedComponent=Body;Movement->MaxSpeed=410;Movement->Acceleration=2600;Movement->Deceleration=3200;}
void AKitchenChef::OnConstruction(const FTransform& T){Super::OnConstruction(T);ClearArt(this);Rig=KitchenArt::Chef(this,RootComponent,TEXT("Chef"),FVector(0,0,-73),FLinearColor(.08,.37,.34));Rig.Root->SetRelativeRotation(FRotator(0,90,0));}
void AKitchenChef::Tick(float D){Super::Tick(D);const FVector V=GetVelocity();if(V.SizeSquared2D()>100){AnimationClock+=D*11;SetActorRotation(FRotator(0,V.Rotation().Yaw,0));}const float Swing=FMath::Sin(AnimationClock)*FMath::Min(V.Size2D()/410.f,1.f)*30; if(Rig.LeftFoot)Rig.LeftFoot->SetRelativeRotation(FRotator(0,0,Swing));if(Rig.RightFoot)Rig.RightFoot->SetRelativeRotation(FRotator(0,0,-Swing));auto* G=Cast<APizzaGameMode>(GetWorld()->GetAuthGameMode());const bool Carrying=G&&G->Carry.IsSet();if(Rig.LeftArm)Rig.LeftArm->SetRelativeRotation(FRotator(Carrying?-35:0,0,Carrying?0:-Swing*.4));if(Rig.RightArm)Rig.RightArm->SetRelativeRotation(FRotator(Carrying?-35:0,0,Carrying?0:Swing*.4));}
APizzaGameMode::APizzaGameMode(){PrimaryActorTick.bCanEverTick=true;DefaultPawnClass=AKitchenChef::StaticClass();PlayerControllerClass=APizzaController::StaticClass();HUDClass=APizzaHUD::StaticClass();}
AKitchenChef* APizzaGameMode::Chef()const{return Cast<AKitchenChef>(UGameplayStatics::GetPlayerPawn(GetWorld(),0));}
void APizzaGameMode::BeginPlay(){Super::BeginPlay();if(!UGameplayStatics::GetActorOfClass(GetWorld(),APizzaArena::StaticClass()))GetWorld()->SpawnActor<APizzaArena>();Camera=GetWorld()->SpawnActor<ACameraActor>(NormalCamera,NormalRotation);Camera->GetCameraComponent()->FieldOfView=58;Camera->GetCameraComponent()->PostProcessSettings.bOverride_AutoExposureMethod=true;Camera->GetCameraComponent()->PostProcessSettings.AutoExposureMethod=EAutoExposureMethod::AEM_Manual;Camera->GetCameraComponent()->PostProcessSettings.bOverride_AutoExposureApplyPhysicalCameraExposure=true;Camera->GetCameraComponent()->PostProcessSettings.AutoExposureApplyPhysicalCameraExposure=false;Camera->GetCameraComponent()->PostProcessSettings.bOverride_AutoExposureBias=true;Camera->GetCameraComponent()->PostProcessSettings.AutoExposureBias=-1.0;Camera->GetCameraComponent()->PostProcessSettings.bOverride_BloomIntensity=true;Camera->GetCameraComponent()->PostProcessSettings.BloomIntensity=.12;UGameplayStatics::GetPlayerController(GetWorld(),0)->SetViewTarget(Camera);CarryVisual=GetWorld()->SpawnActor<APizzaVisual>();CarryVisual->SetActorHiddenInGame(true);BoardVisual=GetWorld()->SpawnActor<APizzaVisual>(CutLocation(),FRotator::ZeroRotator);BoardVisual->SetActorHiddenInGame(true);OvenVisual=GetWorld()->SpawnActor<APizzaVisual>(FVector(610,100,97),FRotator::ZeroRotator);OvenVisual->SetActorHiddenInGame(true);for(int I=0;I<3;++I){auto* Guest=GetWorld()->SpawnActor<AActor>();auto* Root=NewObject<USceneComponent>(Guest,TEXT("GuestRoot"));Guest->SetRootComponent(Root);Root->RegisterComponent();Guest->SetActorLocation(FVector(-300+300*I,548,0));KitchenArt::Chef(Guest,Root,TEXT("Guest"),FVector::ZeroVector,FLinearColor(I==0?.7:.25,I==1?.6:.22,I==2?.7:.18));Guests.Add(Guest);}UE_LOG(LogTemp,Display,TEXT("PIZZA_NATIVE_READY: room, chef, camera and station actors spawned"));}
void APizzaGameMode::Start(){Intro=false;Cutting=false;Learning=false;Paused=false;Finished=false;RecipeLesson=false;Lesson.clear();LessonIndex=0;AnswerChoice=0;FeedbackTime=0;if(auto* C=Chef()){C->Movement->StopMovementImmediately();C->Movement->MaxSpeed=410;}if(auto* P=Cast<APizzaController>(UGameplayStatics::GetPlayerController(GetWorld(),0)))P->ClearInput();RoundTime=240;Score=0;Served=0;OrderSerial=0;Orders.Empty();Carry.Reset();Board.Reset();Oven.Reset();BakeTime=0;for(int I=0;I<3;++I)MakeOrder();Feedback=TEXT("Teig holen → Tomate & Käse → backen → schneiden → servieren. E: benutzen.");RefreshPizza();}
void APizzaGameMode::MakeOrder(){if(Orders.Num()>=3)return;static const char* Names[]={"Mila","Ben","Lina","Tom","Ava"};FKitchenOrder O;O.Name=UTF8_TO_TCHAR(Names[OrderSerial%5]);const int Nums[]={4,1,3,5,7,2,6};O.Amount=PizzaRules::Rational(Nums[OrderSerial%7],8);O.Ingredients=(OrderSerial%3==2)?7:3;if(Difficulty==1){O.Op=OrderSerial%2?'-':'+';O.Left=PizzaRules::Rational(O.Op=='+'?1:3,4);O.Right=PizzaRules::Rational(1,8);O.Amount=PizzaRules::Calculate(O.Op,O.Left,O.Right);}else if(Difficulty==2){const char Ops[]={'+','-','*','/'};O.Op=Ops[OrderSerial%4];O.Left=PizzaRules::Rational(O.Op=='*'?3:O.Op=='-'?3:1,4);O.Right=PizzaRules::Rational(O.Op=='/'?2:1,O.Op=='/'?1:O.Op=='*'?2:8);O.Amount=PizzaRules::Calculate(O.Op,O.Left,O.Right);}Orders.Add(O);++OrderSerial;}
FString APizzaGameMode::OrderLabel(const FKitchenOrder& O)const{return O.Op==' '?Frac(O.Amount)+TEXT(" Pizza"):Frac(O.Left)+TEXT(" ")+FString::Chr(O.Op=='*'?TEXT('×'):O.Op=='/'?TEXT('÷'):O.Op)+TEXT(" ")+Frac(O.Right)+TEXT(" = ?");}
int APizzaGameMode::NearestStation()const{auto* C=Chef();if(!C)return -1;const FVector P=C->GetActorLocation();const FVector Pos[]={FVector(-610,-280,0),FVector(-610,-30,0),FVector(-610,220,0),FVector(610,-280,0),FVector(610,100,0),FVector(0,190,0),FVector(-300,430,0),FVector(0,430,0),FVector(300,430,0)};int Best=-1;float Dist=170;for(int I=0;I<9;++I){const float D=FVector::Dist2D(P,Pos[I]);if(D<Dist){Dist=D;Best=I;}}return Best;}
void APizzaGameMode::Use(){if(Frozen())return;if(Cutting){FinishCut();return;}const int S=NearestStation();if(S==0){if(Carry.IsSet()){Feedback=TEXT("Lege die Pizza zuerst ab oder serviere sie.");return;}Carry=FKitchenPizza();Feedback=TEXT("Frischer Teig! Jetzt Tomatensauce und Käse hinzufügen.");}else if(S>=1&&S<=3){if(!Carry.IsSet()||Carry->Baked){Feedback=TEXT("Belege zuerst einen frischen Pizzateig.");return;}Carry->Ingredients|=(S==1?1:S==2?2:4);Feedback=S==1?TEXT("Tomatensauce verteilt."):S==2?TEXT("Käse drauf! Ab in den Ofen."):TEXT("Pilze hinzugefügt.");}else if(S==4){if(Oven.IsSet()){if(!Carry.IsSet()&&Oven->Baked){Carry=Oven;Oven.Reset();Feedback=TEXT("Goldbraun gebacken! Zum Schneidebrett.");}else Feedback=TEXT("Die Pizza backt noch. Du kannst inzwischen vorbereiten.");}else if(Carry.IsSet()&&(Carry->Ingredients&3)==3&&!Carry->Baked){Oven=Carry;Carry.Reset();BakeTime=0;Feedback=TEXT("Die Pizza ist im Ofen. Beobachte den Backfortschritt.");}else Feedback=TEXT("Der Ofen braucht eine belegte Pizza mit Tomate und Käse.");}else if(S==5){if(Carry.IsSet()&&Carry->Baked&&!Board.IsSet()){Board=Carry;Carry.Reset();BeginCut();}else if(Board.IsSet()&&!Carry.IsSet())BeginCut();else if(Board.IsSet())Feedback=TEXT("Deine Hände sind voll. Lege den Teller zuerst ab; die Pizza am Brett bleibt erhalten.");else Feedback=TEXT("Bring eine gebackene Pizza zum Schneidebrett.");}else if(S>=6)TryServe(S-6);else Feedback=TEXT("Geh näher an eine Station. Die helle Markierung zeigt, was du benutzen kannst.");RefreshPizza();}
void APizzaGameMode::Drop(){if(Frozen()||Cutting)return;if(Carry.IsSet()){Carry.Reset();Feedback=TEXT("Pizza zurückgelegt. Du kannst neu anfangen.");RefreshPizza();}}
void APizzaGameMode::Dash(){if(Frozen()||Cutting)return;if(auto* C=Chef()){C->Movement->MaxSpeed=720;FeedbackTime=.32f;}}
void APizzaGameMode::CycleDifficulty(){if(Learning||Cutting)return;Difficulty=(Difficulty+1)%3;Feedback=TEXT("Neue Bestellungen verwenden den gewählten Modus. Deine laufenden Bestellungen bleiben erhalten.");}
void APizzaGameMode::BeginCut(){Cutting=true;Feedback=TEXT("Ziehe von einer Pizzaseite zur anderen. Tippe danach deine Stücke an.");if(auto* C=Chef())C->Movement->StopMovementImmediately();}
void APizzaGameMode::FinishCut(){if(Frozen()||!Cutting||!Board.IsSet()||Carry.IsSet())return;const auto Amount=Board->Cuts.Selected(Board->Selection);if(!Amount.Valid){Feedback=TEXT("Wähle gleich große Stücke. Für Achtel brauchst du vier Schnitte durch die Mitte.");return;}Board->Plated=true;Carry=Board;Board.Reset();Cutting=false;Feedback=TEXT("Portion auf dem Teller. Bring sie zum passenden Gast.");RefreshPizza();}
void APizzaGameMode::CutStroke(FVector2D A,FVector2D B){if(!Cutting||!Board.IsSet()||Frozen())return;if(Board->Cuts.AddStroke(A.X,A.Y,B.X,B.Y)){Board->Selection=0;Feedback=Board->Cuts.EqualParts()?TEXT("Schnitt sitzt! Die Stücke sind gleich groß."):Board->Cuts.Count()==6&&!Board->Cuts.HasGrossCuts()?TEXT("Noch ein Schnitt: Dann kannst du acht gleich große Stücke wählen."):TEXT("Dieser Schnitt ist stark schief oder seitlich. Die Stücke sind ungleich. Nutze Neu teilen.");}else Feedback=TEXT("Ziehe deutlich quer über die Pizza. Kurze Tipps oder derselbe Schnitt teilen sie nicht erneut.");RefreshPizza();}
void APizzaGameMode::CutAngle(float Angle){if(!Cutting||!Board.IsSet()||Frozen())return;if(Board->Cuts.AddDiameter(Angle))Board->Selection=0;RefreshPizza();}
void APizzaGameMode::TogglePiece(FVector2D P){if(!Cutting||!Board.IsSet()||Frozen())return;const auto Pieces=Board->Cuts.Pieces();for(int I=0;I<static_cast<int>(Pieces.size());++I)if(PizzaRules::PizzaCuts::Contains(Pieces[I],{P.X,P.Y})){Board->Selection^=(1u<<I);break;}RefreshPizza();}
void APizzaGameMode::ResetCuts(){if(!Board.IsSet()||Frozen())return;Board->Cuts=PizzaRules::PizzaCuts();Board->Selection=0;RefreshPizza();}
void APizzaGameMode::TryServe(int I){if(Frozen()||!Orders.IsValidIndex(I)||!Carry.IsSet()||!Carry->Baked||!Carry->Plated){Feedback=TEXT("Serviere einen gebackenen, geschnittenen Teller.");return;}const auto Delivered=Carry->Cuts.Selected(Carry->Selection);const auto& O=Orders[I];if(!PizzaRules::Equal(Delivered,O.Amount)){BeginLesson(O,Delivered);return;}if(Carry->Ingredients!=O.Ingredients){BeginLesson(O,Delivered);RecipeLesson=true;const int Missing=O.Ingredients&~Carry->Ingredients;const int Extra=Carry->Ingredients&~O.Ingredients;const int Bit=Missing?Missing:Extra;int Correct=Bit&1?1:Bit&2?2:4;Lesson={{Missing?"Schau auf die Bestellkarte. Welche Zutat fehlt auf dieser Pizza?":"Schau auf die Bestellkarte. Welche Zutat gehört hier nicht auf die Pizza?",Correct,{1,2,4,7}}};LessonContext=O.Name+TEXT(" bestellt ")+(O.Ingredients==7?TEXT("Tomate, Käse und Pilze."):TEXT("Tomate und Käse."));return;}Score+=Orders[I].Patience>0?110:70;++Served;Feedback=O.Name+TEXT(": Grazie! Genau meine Portion!");Orders.RemoveAt(I);MakeOrder();Carry.Reset();RefreshPizza();}
void APizzaGameMode::BeginLesson(const FKitchenOrder& O,PizzaRules::Rational Delivered){Learning=true;RecipeLesson=false;AnswerChoice=0;Lesson=PizzaRules::MakeLesson(O.Amount,Delivered,O.Op,O.Left,O.Right);if(O.Op==' '&&Carry.IsSet()){const int Parts=FMath::Max(O.Amount.Den,Carry->Cuts.Count());const int Pieces=O.Amount.Num*(Parts/O.Amount.Den);const auto Choice=[](int N,int Seed){std::vector<int> V{N,N+1,N>0?N-1:N+2,N+3};std::rotate(V.begin(),V.begin()+((N+Seed)%4),V.end());return V;};const std::string Subdivision=Parts>Carry->Cuts.Count()?"Für diese Bestellung teilen wir die ganze Pizza in ":"Deine Pizza hat ";Lesson={{Subdivision+std::to_string(Parts)+" gleich große Teile. Welcher Nenner beschreibt ein Stück?",Parts,Choice(Parts,1)},{"Die Bestellung ist "+PizzaRules::Format(O.Amount)+". Wie viele dieser Stücke gehören auf den Teller?",Pieces,Choice(Pieces,2)},{"Von "+std::to_string(Parts)+" Stücken servierst du "+std::to_string(Pieces)+". Wie viele bleiben von der ganzen Pizza übrig?",Parts-Pieces,Choice(Parts-Pieces,3)}};}LessonIndex=0;LessonContext=O.Name+TEXT(" bestellt ")+OrderLabel(O)+TEXT(". Du hast ")+Frac(Delivered)+TEXT(" geliefert.");Feedback=TEXT("Wir nehmen uns kurz Zeit und rechnen gemeinsam. Die Küche wartet.");if(auto* C=Chef())C->Movement->StopMovementImmediately();if(auto* P=Cast<APizzaController>(UGameplayStatics::GetPlayerController(GetWorld(),0)))P->ClearInput();UE_LOG(LogTemp,Display,TEXT("PIZZA_LESSON_PAUSE wanted=%s delivered=%s steps=%d"),*Frac(O.Amount),*Frac(Delivered),static_cast<int>(Lesson.size()));}
void APizzaGameMode::Answer(int N){if(!Learning||LessonIndex>=static_cast<int>(Lesson.size()))return;if(N!=Lesson[LessonIndex].Correct){Feedback=TEXT("Fast! Schau auf den Hinweis. Du darfst es nochmal versuchen.");return;}++LessonIndex;Feedback=TEXT("Richtig! Diesen Schritt hast du verstanden.");if(LessonIndex==static_cast<int>(Lesson.size())){Learning=false;Feedback=TEXT("Gut gemacht! Teile deine Pizza neu und serviere die richtige Portion.");if(RecipeLesson){Carry.Reset();RecipeLesson=false;Feedback=TEXT("Die Zutaten sind geklärt. Bereite eine neue Pizza passend zur Bestellkarte vor.");}else if(Carry.IsSet()&&!Board.IsSet()){Carry->Plated=false;Carry->Selection=0;Board=Carry;Carry.Reset();Cutting=true;}else if(Carry.IsSet())Feedback=TEXT("Am Brett liegt noch eine Pizza. Lege deinen Teller erst ab, bevor du dort weiterarbeitest.");RefreshPizza();UE_LOG(LogTemp,Display,TEXT("PIZZA_LESSON_RESUME"));}}
void APizzaGameMode::RefreshPizza(){if(CarryVisual){CarryVisual->SetActorHiddenInGame(!Carry.IsSet());if(Carry.IsSet())CarryVisual->SetPizza(Carry.GetValue());}if(BoardVisual){BoardVisual->SetActorHiddenInGame(!Board.IsSet());if(Board.IsSet())BoardVisual->SetPizza(Board.GetValue());}if(OvenVisual){OvenVisual->SetActorHiddenInGame(!Oven.IsSet());if(Oven.IsSet())OvenVisual->SetPizza(Oven.GetValue());}}
void APizzaGameMode::Tick(float D){Super::Tick(D);if(!Camera)return;const bool Close=Cutting&&!Learning;const FVector Goal=Close?FVector(0,-30,650):NormalCamera;const FRotator Rot=Close?FRotator(-69,90,0):NormalRotation;Camera->SetActorLocation(FMath::VInterpTo(Camera->GetActorLocation(),Goal,D,4));Camera->SetActorRotation(FMath::RInterpTo(Camera->GetActorRotation(),Rot,D,4));Camera->GetCameraComponent()->FieldOfView=FMath::FInterpTo(Camera->GetCameraComponent()->FieldOfView,Close?32.f:58.f,D,4);if(auto* C=Chef()){if(CarryVisual&&Carry.IsSet())CarryVisual->SetActorLocation(C->GetActorLocation()+C->GetActorForwardVector()*46+FVector(0,0,18));}if(Frozen()){if(auto* C=Chef())C->Movement->StopMovementImmediately();return;}RoundTime=FMath::Max(0.f,RoundTime-D);if(RoundTime<=0){Finished=true;if(auto* C=Chef())C->Movement->StopMovementImmediately();if(auto* P=Cast<APizzaController>(UGameplayStatics::GetPlayerController(GetWorld(),0)))P->ClearInput();return;}for(auto& O:Orders)O.Patience=FMath::Max(0.f,O.Patience-D);if(Oven.IsSet()&&!Oven->Baked){BakeTime+=D;if(BakeTime>=5){Oven->Baked=true;Feedback=TEXT("Ding! Die Pizza ist goldbraun. E am Ofen zum Abholen.");RefreshPizza();}}if(FeedbackTime>0){FeedbackTime-=D;if(FeedbackTime<=0)if(auto* C=Chef())C->Movement->MaxSpeed=410;}}
APizzaController::APizzaController(){bShowMouseCursor=true;bEnableClickEvents=true;bEnableTouchEvents=true;}
void APizzaController::BeginPlay(){Super::BeginPlay();if(IsLocalController()){FInputModeGameAndUI Mode;Mode.SetHideCursorDuringCapture(false);Mode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);if(auto* Viewport=GetWorld()->GetGameViewport())if(Viewport->GetGameViewportWidget().IsValid())Mode.SetWidgetToFocus(Viewport->GetGameViewportWidget());SetInputMode(Mode);bShowMouseCursor=true;}}
APizzaGameMode* APizzaController::Game()const{return Cast<APizzaGameMode>(GetWorld()->GetAuthGameMode());}
FVector APizzaController::MoveDirection(FVector2D Axes)const{const auto* G=Game();if(!G||!G->Camera)return FVector::ZeroVector;const FVector Right=FVector(G->Camera->GetActorRightVector().X,G->Camera->GetActorRightVector().Y,0).GetSafeNormal();const FVector Forward=FVector(G->Camera->GetActorForwardVector().X,G->Camera->GetActorForwardVector().Y,0).GetSafeNormal();return (Right*Axes.X+Forward*Axes.Y).GetClampedToMaxSize(1.f);}

void APizzaController::SetupInputComponent(){Super::SetupInputComponent();InputComponent->BindKey(EKeys::E,IE_Pressed,this,&APizzaController::Use);InputComponent->BindKey(EKeys::SpaceBar,IE_Pressed,this,&APizzaController::Dash);InputComponent->BindKey(EKeys::X,IE_Pressed,this,&APizzaController::Drop);InputComponent->BindKey(EKeys::Escape,IE_Pressed,this,&APizzaController::Escape);InputComponent->BindKey(EKeys::Q,IE_Pressed,this,&APizzaController::DifficultyMode);InputComponent->BindKey(EKeys::One,IE_Pressed,this,&APizzaController::Cut0);InputComponent->BindKey(EKeys::Two,IE_Pressed,this,&APizzaController::Cut45);InputComponent->BindKey(EKeys::Three,IE_Pressed,this,&APizzaController::Cut90);InputComponent->BindKey(EKeys::Four,IE_Pressed,this,&APizzaController::Cut135);InputComponent->BindKey(EKeys::LeftMouseButton,IE_Pressed,this,&APizzaController::PointerDown);InputComponent->BindKey(EKeys::LeftMouseButton,IE_Released,this,&APizzaController::PointerUp);InputComponent->BindTouch(IE_Pressed,this,&APizzaController::TouchDown);InputComponent->BindTouch(IE_Released,this,&APizzaController::TouchUp);}
void APizzaController::Use(){if(auto* G=Game()){if(G->Intro||G->Finished)G->Start();else if(G->Learning)ChooseAnswer(G->AnswerChoice);else G->Use();}}void APizzaController::Drop(){if(auto* G=Game())G->Drop();}void APizzaController::Dash(){if(auto* G=Game())G->Dash();}void APizzaController::Escape(){if(auto* G=Game()){if(G->Learning)return;if(G->Cutting)G->Cutting=false;else G->TogglePause();}}void APizzaController::DifficultyMode(){if(auto* G=Game())G->CycleDifficulty();}void APizzaController::Cut0(){if(auto* G=Game()){if(G->Learning)ChooseAnswer(0);else G->CutAngle(0);}}void APizzaController::Cut45(){if(auto* G=Game()){if(G->Learning)ChooseAnswer(1);else G->CutAngle(45);}}void APizzaController::Cut90(){if(auto* G=Game()){if(G->Learning)ChooseAnswer(2);else G->CutAngle(90);}}void APizzaController::Cut135(){if(auto* G=Game()){if(G->Learning)ChooseAnswer(3);else G->CutAngle(135);}}
FVector2D APizzaController::PizzaPoint(FVector2D P)const{FVector O,V;if(!DeprojectScreenPositionToWorld(P.X,P.Y,O,V)||FMath::Abs(V.Z)<.0001)return FVector2D(10,10);const FVector Hit=O+V*((94-O.Z)/V.Z);return FVector2D(Hit.X/42.f,(Hit.Y-190)/42.f);}
void APizzaController::Press(FVector2D P,int Index){auto* G=Game();if(!G)return;if(auto* H=Cast<APizzaHUD>(GetHUD()))if(H->Press(P))return;if(G->Frozen())return;if((Dragging||Joystick)&&Index!=ActiveTouch)return;if(G->Cutting){DragStart=PizzaPoint(P);DragEnd=DragStart;Dragging=true;ActiveTouch=Index;}}
void APizzaController::Release(FVector2D P,int Index){if(Index!=ActiveTouch)return;if(Dragging){auto* G=Game();const FVector2D End=PizzaPoint(P);if((End-DragStart).Size()<.15){if(G)G->TogglePiece(End);}else if(G)G->CutStroke(DragStart,End);}Dragging=false;Joystick=false;Stick=FVector2D::ZeroVector;ActiveTouch=-1;}
void APizzaController::PointerDown(){float X,Y;if(GetMousePosition(X,Y))Press(FVector2D(X,Y),-2);}void APizzaController::PointerUp(){float X,Y;if(GetMousePosition(X,Y))Release(FVector2D(X,Y),-2);else ClearInput();}void APizzaController::TouchDown(ETouchIndex::Type I,FVector P){Press(FVector2D(P.X,P.Y),static_cast<int>(I));}void APizzaController::TouchUp(ETouchIndex::Type I,FVector P){Release(FVector2D(P.X,P.Y),static_cast<int>(I));}
void APizzaController::PlayerTick(float D){Super::PlayerTick(D);auto* G=Game();if(!G)return;FVector2D Pointer;if(ActiveTouch==-2){float X,Y;if(GetMousePosition(X,Y))Pointer=FVector2D(X,Y);else {ClearInput();Pointer=FVector2D::ZeroVector;}}else if(ActiveTouch>=0){float X,Y;bool Pressed;GetInputTouchState(static_cast<ETouchIndex::Type>(ActiveTouch),X,Y,Pressed);Pointer=FVector2D(X,Y);if(!Pressed){Release(Pointer,ActiveTouch);}}if(Dragging)DragEnd=PizzaPoint(Pointer);if(Joystick){const FVector2D Diff=(Pointer-DragStart)/70.f;Stick=Diff.GetClampedToMaxSize(1.f);}if(G->Frozen()||G->Cutting)return;auto* C=G->Chef();if(!C)return;float X=Stick.X,Y=-Stick.Y;X+=(IsInputKeyDown(EKeys::D)||IsInputKeyDown(EKeys::Right))?1.f:0.f;X-=(IsInputKeyDown(EKeys::A)||IsInputKeyDown(EKeys::Left))?1.f:0.f;Y+=(IsInputKeyDown(EKeys::W)||IsInputKeyDown(EKeys::Up))?1.f:0.f;Y-=(IsInputKeyDown(EKeys::S)||IsInputKeyDown(EKeys::Down))?1.f:0.f;C->AddMovementInput(MoveDirection(FVector2D(X,Y)));}

void APizzaGameMode::TogglePause(){if(Learning||Intro||Finished)return;Paused=!Paused;if(Paused){if(auto* C=Chef())C->Movement->StopMovementImmediately();if(auto* P=Cast<APizzaController>(UGameplayStatics::GetPlayerController(GetWorld(),0)))P->ClearInput();}}
void APizzaController::ClearInput(){Dragging=false;Joystick=false;Stick=FVector2D::ZeroVector;ActiveTouch=-1;}
void APizzaController::ChooseAnswer(int I){auto* G=Game();if(G&&G->Learning&&G->LessonIndex<static_cast<int>(G->Lesson.size())&&I>=0&&I<static_cast<int>(G->Lesson[G->LessonIndex].Choices.size()))G->Answer(G->Lesson[G->LessonIndex].Choices[I]);}
void APizzaController::PreviousAnswer(){if(auto* G=Game())if(G->Learning)G->AnswerChoice=(G->AnswerChoice+3)%4;}
void APizzaController::NextAnswer(){if(auto* G=Game())if(G->Learning)G->AnswerChoice=(G->AnswerChoice+1)%4;}
