"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createRequire}=require("node:module"),path=require("node:path");
assert.match(process.env.FIRESTORE_EMULATOR_HOST||"",/^(127\.0\.0\.1|localhost):\d+$/);
const requireFunctions=createRequire(path.resolve(__dirname,"../../functions/package.json"));
const {initializeApp,deleteApp}=requireFunctions("firebase-admin/app");
const {getFirestore}=requireFunctions("firebase-admin/firestore");
const {createAccountActions}=requireFunctions("./lib/admin-account-actions");
const app=initializeApp({projectId:"demo-gradecrew-secure"},"admin-actions"),db=getFirestore(app);
let time=Date.now(), failure="", identityDeletes=0;
const identities=new Map();
const auth={getUser:async id=>{if(!identities.has(id))throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});return identities.get(id);},updateUser:async(id,patch)=>{if(!identities.has(id))throw Object.assign(new Error("missing"),{code:"auth/user-not-found"});Object.assign(identities.get(id),patch);},revokeRefreshTokens:async()=>{},deleteUser:async id=>{if(id===failure)throw new Error("provider unavailable");identityDeletes++;identities.delete(id);}};
const service=createAccountActions({db,auth,now:()=>time});
const req=(uid,data)=>({auth:uid?{uid,token:{auth_time:Math.floor(time/1000)}}:undefined,data});
async function seed(){failure="";identityDeletes=0;time=Date.now();identities.clear();for(const c of ["users","accountActions","accountActionControl","accountDeletions","quizzes","cocoMemory","cocoImageIndex","aiJobs","adminAudit"])await db.recursiveDelete(db.collection(c));for(const [id,role]of[["a","admin"],["b","admin"],["t","teacher"]]){await db.doc(`users/${id}`).set({role,status:"active",email:`${id}@example.invalid`});identities.set(id,{uid:id,disabled:false,tokensValidAfterTime:"1970-01-01T00:00:00Z"});}}
const preview=(caller,action,targets,value)=>service.preview(req(caller,{action,targets,value}));
const execute=(caller,p)=>service.execute(req(caller,{operationId:p.operationId}));
test.after(async()=>{await db.terminate();await deleteApp(app);});
test("anonymous, teacher, suspended, disabled and revoked callers cannot mutate",async()=>{await seed();await assert.rejects(preview(null,"delete",["t"]),{code:"unauthenticated"});await assert.rejects(preview("t","delete",["b"]),{code:"permission-denied"});await db.doc("users/a").update({status:"suspended"});await assert.rejects(preview("a","delete",["t"]),{code:"permission-denied"});identities.get("b").disabled=true;await assert.rejects(preview("b","delete",["t"]),{code:"permission-denied"});identities.get("b").disabled=false;identities.get("b").tokensValidAfterTime=new Date(time+1000).toISOString();await assert.rejects(preview("b","delete",["t"]),{code:"permission-denied"});assert.equal((await db.doc("users/t").get()).exists,true);});
test("self and active published exams are refused while ended school records are preserved",async()=>{await seed();await db.doc("quizzes/live").set({ownerId:"t",published:true,ended:false});const p=await preview("a","delete",["a","t"]);assert.deepEqual(p.targets.map(r=>r.code),["self-protected","active-exam"]);const r=await execute("a",p);assert.deepEqual(r.outcomes.map(r=>r.code),["self-protected","active-exam"]);assert.equal(identityDeletes,0);});
test("stale identity, security state, expiration and new active exams invalidate confirmation",async()=>{for(const kind of["identity","auth-identity","status","expiry","exam"]){await seed();const p=await preview("a","delete",["t"]);if(kind==="identity")await db.doc("users/t").update({email:"different@example.invalid"});if(kind==="auth-identity")identities.get("t").email="changed@example.invalid";if(kind==="status")await db.doc("users/t").update({status:"suspended"});if(kind==="expiry")time+=301000;if(kind==="exam")await db.doc("quizzes/new").set({ownerId:"t",published:true});await assert.rejects(execute("a",p),{code:"failed-precondition"});assert.equal(identityDeletes,0);}});
test("concurrent mutual admin demotion retains one active admin and denies the loser",async()=>{await seed();const p=await preview("a","role",["b"],"teacher"),q=await preview("b","role",["a"],"teacher");const r=await Promise.allSettled([execute("a",p),execute("b",q)]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);assert.equal(r.filter(x=>x.status==="rejected")[0].reason.code,"permission-denied");const admins=(await db.collection("users").where("role","==","admin").get()).docs.filter(s=>s.data().status==="active");assert.equal(admins.length,1);});
test("mixed concurrent suspension and deletion cannot eliminate every administrator",async()=>{await seed();const p=await preview("a","delete",["b"]),q=await preview("b","status",["a"],"suspended");const r=await Promise.allSettled([execute("a",p),execute("b",q)]);assert.equal(r.filter(x=>x.status==="fulfilled").length,1);const admins=(await db.collection("users").where("role","==","admin").get()).docs.filter(s=>s.data().status==="active");assert.equal(admins.length,1);});
test("deletion removes identity and proven private paths, preserves school and foreign content, and retries idempotently",async()=>{await seed();await db.doc("quizzes/ended").set({ownerId:"t",published:true,ended:true});await db.doc("quizzes/ended/submissions/one").set({points:2});for(const p of["cocoMemory/t","cocoImageIndex/t/images/one","users/t/announcementViews/one","aiJobs/private","cocoMemory/b","aiJobs/foreign"]){await db.doc(p).set(p==="aiJobs/private"?{ownerId:"t"}:{ownerId:"b",marker:"synthetic"});}const p=await preview("a","delete",["t"]);const r=await execute("a",p);assert.deepEqual(r.outcomes,[{id:"t",code:"complete"}]);assert.equal(identities.has("t"),false);for(const path of["users/t","cocoMemory/t","cocoImageIndex/t/images/one","users/t/announcementViews/one","aiJobs/private"])assert.equal((await db.doc(path).get()).exists,false,path);for(const path of["quizzes/ended","quizzes/ended/submissions/one","cocoMemory/b","aiJobs/foreign"])assert.equal((await db.doc(path).get()).exists,true,path);assert.equal((await db.doc("accountDeletions/t").get()).exists,true);assert.deepEqual(await execute("a",p),r);assert.equal(identityDeletes,1);});
test("partial provider failure never reports deletion success and retries the same operation",async()=>{await seed();failure="t";const p=await preview("a","delete",["t"]);const r=await execute("a",p);assert.equal(r.status,"partial");assert.equal(r.outcomes[0].code,"failed");assert.equal((await db.doc("users/t").get()).data().status,"deleting");identities.get("t").email="replacement@example.invalid";const changed=await execute("a",p);assert.equal(changed.outcomes[0].reason,"identity-changed");assert.equal(identities.has("t"),true);delete identities.get("t").email;failure="";const retried=await execute("a",p);assert.equal(retried.status,"complete");assert.equal((await db.doc("users/t").get()).exists,false);});
test("another admin cannot execute a confirmation and concurrent duplicate starts do not delete twice",async()=>{await seed();const p=await preview("a","delete",["t"]);await assert.rejects(execute("b",p),{code:"permission-denied"});const r=await Promise.allSettled([execute("a",p),execute("a",p)]);assert.ok(r.some(x=>x.status==="fulfilled"));for(const result of r){if(result.status==="rejected")assert.equal(result.reason.code,"aborted");else assert.deepEqual(result.value.outcomes,[{id:"t",code:"complete"}]);}assert.equal(identityDeletes,1);});
test("a delayed memory transaction cannot recreate private history after deletion reservation",async()=>{await seed();const {memoryOperation}=requireFunctions("./lib/coco-support");const p=await preview("a","delete",["t"]);await execute("a",p);await assert.rejects(memoryOperation(db,db.doc("cocoMemory/t"),{operation:"remember",turnId:"synthetic1",messages:[{role:"user",text:"private fixture"}]},()=>new Date(),async tx=>{const profile=(await tx.get(db.doc("users/t"))).data();if(!profile||profile.status!=="active")throw Object.assign(new Error("inactive"),{code:"permission-denied"});}),{code:"permission-denied"});assert.equal((await db.doc("cocoMemory/t").get()).exists,false);});
test("active private background jobs block deletion and no new job can reserve after account cleanup",async()=>{await seed();await db.doc('aiJobs/running').set({ownerId:'t',status:'running'});const blocked=await preview('a','delete',['t']);assert.equal(blocked.targets[0].code,'active-job');await db.doc('aiJobs/running').update({status:'complete'});const p=await preview('a','delete',['t']);await execute('a',p);const {reserveJob}=requireFunctions('./lib/job-slots'),{requireAccountWrite}=requireFunctions('./lib/account-state');const {Timestamp}=requireFunctions('firebase-admin/firestore');await assert.rejects(reserveJob(db,{uid:'t',jobRef:db.doc('aiJobs/new'),lockRef:db.doc('users/t/aiRuntime/current'),now:Timestamp.now(),jobData:{ownerId:'t',status:'queued'},beforeReserve:tx=>requireAccountWrite(tx,db,'t')}),{code:'permission-denied'});assert.equal((await db.doc('aiJobs/new').get()).exists,false);});
test('fresh admin recovers only explicitly selected target after original initiator loses eligibility',async()=>{
 for(const loss of ['role','status','identity']){
  await seed();for(const id of ['t','sibling']){if(id==='sibling'){await db.doc(`users/${id}`).set({role:'teacher',status:'active'});identities.set(id,{uid:id,disabled:false,tokensValidAfterTime:'1970-01-01T00:00:00Z'});}await db.doc(`cocoMemory/${id}`).set({history:[]});}
  const original=await preview('a','delete',['t','sibling']);
  const saved=(await db.doc(`accountActions/${original.operationId}`).get()).data();
  // Reserve a genuinely confirmed bulk deletion with failures for both targets, without calling any live Auth.
  const previousDelete=auth.deleteUser;auth.deleteUser=async()=>{throw new Error('synthetic provider outage');};
  await execute('a',original);auth.deleteUser=previousDelete;
  if(loss==='role'){const removal=await preview('b','role',['a'],'teacher');await execute('b',removal);}else if(loss==='status'){const removal=await preview('b','status',['a'],'suspended');await execute('b',removal);}else identities.delete('a');
  const recovery=await preview('b','recover-delete',['t']);assert.deepEqual(recovery.targets.map(x=>({id:x.id,code:x.code})),[{id:'t',code:'allowed'}]);assert.match(recovery.extent,/Tests, Abgaben und Ergebnisse.*erhalten/);
  const result=await execute('b',recovery);assert.deepEqual(result.outcomes,[{id:'t',code:'complete'}]);assert.equal((await db.doc('users/t').get()).exists,false);assert.equal((await db.doc('cocoMemory/t').get()).exists,false);
  assert.equal((await db.doc('users/sibling').get()).exists,true);assert.equal((await db.doc('cocoMemory/sibling').get()).exists,true);assert.equal(identities.has('sibling'),true);
  const origin=(await db.doc(`accountActions/${original.operationId}`).get()).data();assert.equal(origin.uid,'a');assert.equal(origin.outcomes.find(x=>x.id==='sibling').code,'failed');assert.equal(origin.outcomes.find(x=>x.id==='t').code,'transferred');
  const audit=(await db.collection('adminAudit').where('action','==','account_deletion_recovered').get()).docs.map(x=>x.data());assert.equal(audit.length,1);assert.equal(audit[0].actorId,'b');assert.equal(audit[0].details.originalInitiators[0],'a');assert.deepEqual(audit[0].details.targets,['t']);assert.equal(saved.uid,'a');
 }
});
test('recovery denies nonadmin, uncommitted/foreign targets, running lease, stale transfer and replacement Auth identity',async()=>{
 await seed();failure='t';const original=await preview('a','delete',['t']);await execute('a',original);failure='';
 await db.doc('users/outsider').set({role:'teacher',status:'active'});identities.set('outsider',{uid:'outsider',disabled:false,tokensValidAfterTime:'1970-01-01T00:00:00Z'});await assert.rejects(preview('outsider','recover-delete',['t']),{code:'permission-denied'});
 await db.doc(`accountActions/${original.operationId}`).update({'spec.targets':['a']});const wrongScope=await preview('b','recover-delete',['t']);assert.equal(wrongScope.targets[0].code,'not-recoverable');await db.doc(`accountActions/${original.operationId}`).update({'spec.targets':['t']});
 const foreign=await preview('b','recover-delete',['a']);assert.equal(foreign.targets[0].code,'not-recoverable');
 await db.doc(`accountActions/${original.operationId}`).update({leaseUntil:time+330000});const running=await preview('b','recover-delete',['t']);assert.equal(running.targets[0].code,'deletion-running');await db.doc(`accountActions/${original.operationId}`).update({leaseUntil:0});
 identities.get('t').email='replacement@example.invalid';const changed=await preview('b','recover-delete',['t']);assert.equal(changed.targets[0].code,'identity-changed');delete identities.get('t').email;
 const p=await preview('b','recover-delete',['t']),q=await preview('a','recover-delete',['t']);await execute('a',q);await assert.rejects(execute('b',p),{code:'failed-precondition'});
 await assert.rejects(service.execute(req('b',{operationId:p.operationId,targets:['a']})),{code:'invalid-argument'});assert.equal((await db.doc('users/a').get()).exists,true);
 const notCommitted=await preview('b','delete',['a']);const faked=await preview('b','recover-delete',['a']);assert.equal(faked.targets[0].code,'not-recoverable');assert.equal((await db.doc(`accountActions/${notCommitted.operationId}`).get()).data().status,'preview');
});
