import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url);const {JSDOM}=require('./tools/ui/node_modules/jsdom');
function harness(){const dom=new JSDOM('<div id="gcCrewMessages"></div><form id="gcCrewComposer"><button class="gcCrewSend"></button></form><textarea id="gcCrewInput"></textarea>',{url:'https://example.org'});dom.window.HTMLElement.prototype.scrollIntoView=()=>{};const user={uid:'A'};const calls=[];let aiPromise=Promise.resolve({data:{reply:'Antwort',action:{type:'none'}}});const ctx=vm.createContext({document:dom.window.document,window:dom.window,CustomEvent:dom.window.CustomEvent,crypto:{randomUUID},CREW_MEMBERS:{coco:{}},getApp:()=>({}),getAuth:()=>({currentUser:user}),getFunctions:()=>({}),httpsCallable:(_,name)=>async data=>{calls.push(data);if(name==='crewAssistant')return aiPromise;return {data:data.operation==='search'?{matches:[],unindexedImages:0}:{preferences:'',history:[],saved:true}};},resolveLocalCrewRequest:()=>({handled:false}),setTimeout,clearTimeout});const source=readFileSync(new URL('./crew-assistant-ui.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function installCrewAssistant','function installCrewAssistant').replace(/\ninstallCrewAssistant\(\);/, '');vm.runInContext(source,ctx);vm.runInContext('memoryUid="A"',ctx);return {dom,user,calls,ctx,setAi:p=>{aiPromise=p;}};}
test('clear waits for pending saves but never deletes switched account',async()=>{const h=harness();let release;h.ctx.waiter=new Promise(r=>{release=r;});vm.runInContext('memoryQueue=waiter',h.ctx);await vm.runInContext('showMemory()',h.ctx);const clear=[...h.dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Gespräch und Vorlieben löschen');const pending=clear.onclick();h.user.uid='B';release();await pending;assert.equal(h.calls.filter(c=>c.operation==='clear').length,0);});
test('clear invalidates an in-flight turn and binds deletion to original account',async()=>{const h=harness();await vm.runInContext('showMemory()',h.ctx);const before=vm.runInContext('requestEpoch',h.ctx);await [...h.dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Gespräch und Vorlieben löschen').onclick();assert.ok(vm.runInContext('requestEpoch',h.ctx)>before);assert.equal(h.calls.find(c=>c.operation==='clear').accountId,'A');assert.equal(vm.runInContext('conversation.length',h.ctx),1);});
test('a stale preference editor cannot write into another account',async()=>{const h=harness();await vm.runInContext('showMemory()',h.ctx);h.user.uid='B';await [...h.dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Vorlieben speichern').onclick();assert.equal(h.calls.filter(c=>c.operation==='preferences').length,0);});
test('response arriving after memory deletion never persists the cleared turn',async()=>{const h=harness();let respond;h.setAi(new Promise(r=>{respond=r;}));h.dom.window.document.getElementById('gcCrewInput').value='Hallo';const send=vm.runInContext('sendCurrentMessage()',h.ctx);await Promise.resolve();await vm.runInContext('showMemory()',h.ctx);await [...h.dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Gespräch und Vorlieben löschen').onclick();respond({data:{reply:'Späte Antwort',action:{type:'none'}}});await send;await vm.runInContext('memoryQueue',h.ctx);assert.equal(h.calls.filter(c=>c.operation==='remember').length,0);assert.ok(!h.dom.window.document.body.textContent.includes('Späte Antwort'));});
test('fresh cat search excludes previous maths request',async()=>{const h=harness();vm.runInContext('conversation=[{role:"user",text:"Erstelle einen Test zu Bruchrechnung"}]',h.ctx);h.dom.window.document.getElementById('gcCrewInput').value='Suche meinen Test mit einer Katze';await vm.runInContext('sendCurrentMessage()',h.ctx);assert.equal(h.calls.find(c=>c.operation==='search').query,'Suche meinen Test mit einer Katze');});
test('explicit remember command cannot copy previous-account preferences after read completes',async()=>{const h=harness();let actual='A',reads=0;Object.defineProperty(h.user,'uid',{get(){const value=actual;if(++reads===2){actual='B';vm.runInContext('memoryUid="B";requestEpoch++',h.ctx);}return value;},set(v){actual=v;}});h.dom.window.document.getElementById('gcCrewInput').value='Merke dir Klasse 5';await vm.runInContext('sendCurrentMessage()',h.ctx);assert.equal(h.calls.filter(c=>c.operation==='preferences').length,0);});
