import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url);const {JSDOM}=require('./tools/ui/node_modules/jsdom');
function harness(){const dom=new JSDOM('<div id="gcCrewMessages"></div><form id="gcCrewComposer"><button class="gcCrewSend"></button></form><textarea id="gcCrewInput"></textarea>',{url:'https://example.org'});dom.window.HTMLElement.prototype.scrollIntoView=()=>{};const user={uid:'A'};const calls=[];let authHandler;let aiPromise=Promise.resolve({data:{reply:'Antwort',action:{type:'none'}}}),readWait=null,preferenceWait=null;const ctx=vm.createContext({document:dom.window.document,window:dom.window,CustomEvent:dom.window.CustomEvent,crypto:{randomUUID},CREW_MEMBERS:{coco:{}},onAuthStateChanged:(_,fn)=>{authHandler=fn;},getApp:()=>({}),getAuth:()=>({currentUser:user}),getFunctions:()=>({}),httpsCallable:(_,name)=>async data=>{calls.push(data);if(name==='crewAssistant')return aiPromise;if(data.operation==='read'&&readWait)return readWait;if(data.operation==='preferences'&&preferenceWait)return preferenceWait;return {data:data.operation==='search'?{matches:[],unindexedImages:0}:{preferences:'',history:[],saved:true}};},resolveLocalCrewRequest:()=>({handled:false}),setTimeout,clearTimeout});const source=readFileSync(new URL('./crew-assistant-ui.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export function installCrewAssistant','function installCrewAssistant').replace(/\ninstallCrewAssistant\(\);/, '');vm.runInContext(source,ctx);vm.runInContext('memoryUid="A"',ctx);return {dom,user,calls,ctx,hydrate:async()=>{vm.runInContext("installDurableMemory()",ctx);await authHandler(user);},setAi:p=>{aiPromise=p;},setRead:p=>{readWait=p;},setPreference:p=>{preferenceWait=p;}};}

test('chat header and memory request never create a preferences editor',async()=>{const h=harness();h.dom.window.document.body.replaceChildren();vm.runInContext('createUi()',h.ctx);assert.equal(h.dom.window.document.getElementById('gcCrewMemory'),null);h.dom.window.document.getElementById('gcCrewInput').value='Erinnerungen';await vm.runInContext('sendCurrentMessage()',h.ctx);assert.equal(h.dom.window.document.querySelectorAll('textarea').length,1);assert.ok(!h.dom.window.document.body.textContent.includes('Vorlieben speichern'));assert.ok(!h.dom.window.document.body.textContent.includes('Gespräch und Vorlieben löschen'));});
test('ordinary conversation is saved in background with account and generation',async()=>{const h=harness();h.dom.window.document.getElementById('gcCrewInput').value='Hallo';await vm.runInContext('sendCurrentMessage()',h.ctx);await vm.runInContext('memoryQueue',h.ctx);const write=h.calls.find(c=>c.operation==='remember');assert.equal(write.accountId,'A');assert.equal(write.generation,0);assert.deepEqual(JSON.parse(JSON.stringify(write.messages)),[{role:'user',text:'Hallo'},{role:'assistant',text:'Antwort'}]);});
test('explicit personal hint stays persistent without linking an editor',async()=>{const h=harness();h.dom.window.document.getElementById('gcCrewInput').value='Merke dir Klasse 5';await vm.runInContext('sendCurrentMessage()',h.ctx);await vm.runInContext('memoryQueue',h.ctx);assert.equal(h.calls.find(c=>c.operation==='preferences').preferences,'Klasse 5');assert.ok(!h.dom.window.document.body.textContent.includes('„Erinnerungen“'));});
test('durable history is hydrated after restart without preference controls',async()=>{const h=harness();h.setRead(Promise.resolve({data:{history:[{role:'user',text:'Frühere Frage'},{role:'assistant',text:'Frühere Antwort'}],preferences:'Klasse 5',generation:3}}));await h.hydrate();assert.equal(vm.runInContext('memoryGeneration',h.ctx),3);assert.equal(vm.runInContext('conversation.length',h.ctx),2);assert.match(h.dom.window.document.body.textContent,/Frühere Frage/);assert.equal(h.dom.window.document.querySelectorAll('textarea').length,1);});
test('queued background writes never save into a switched account',async()=>{const h=harness();let release;h.ctx.waiter=new Promise(r=>{release=r;});vm.runInContext('memoryQueue=waiter',h.ctx);const write=vm.runInContext('queueMemoryWrite("remember",{messages:[],turnId:"test"},"A")',h.ctx);h.user.uid='B';release();await write;assert.equal(h.calls.filter(c=>c.operation==='remember').length,0);});
test('delayed AI response after account switch never appears or persists',async()=>{const h=harness();let release;h.setAi(new Promise(r=>{release=r;}));h.dom.window.document.getElementById('gcCrewInput').value='Hallo';const send=vm.runInContext('sendCurrentMessage()',h.ctx);await Promise.resolve();h.user.uid='B';vm.runInContext('requestEpoch++;memoryUid="B"',h.ctx);release({data:{reply:'Späte Antwort',action:{type:'none'}}});await send;await vm.runInContext('memoryQueue',h.ctx);assert.equal(h.calls.filter(c=>c.operation==='remember').length,0);assert.ok(!h.dom.window.document.body.textContent.includes('Späte Antwort'));});
test('fresh cat search excludes previous maths request',async()=>{const h=harness();vm.runInContext('conversation=[{role:"user",text:"Erstelle einen Test zu Bruchrechnung"}]',h.ctx);h.dom.window.document.getElementById('gcCrewInput').value='Suche meinen Test mit einer Katze';await vm.runInContext('sendCurrentMessage()',h.ctx);assert.equal(h.calls.find(c=>c.operation==='search').query,'Suche meinen Test mit einer Katze');});
test('explicit remember command cannot copy previous-account preferences after read completes',async()=>{const h=harness();let actual='A',reads=0;Object.defineProperty(h.user,'uid',{get(){const value=actual;if(++reads===2){actual='B';vm.runInContext('memoryUid="B";requestEpoch++',h.ctx);}return value;},set(v){actual=v;}});h.dom.window.document.getElementById('gcCrewInput').value='Merke dir Klasse 5';await vm.runInContext('sendCurrentMessage()',h.ctx);assert.equal(h.calls.filter(c=>c.operation==='preferences').length,0);});
