"use strict";
const { randomBytes, createHash }=require("node:crypto");
const { initializeApp }=require("firebase-admin/app");
const { getFirestore, FieldValue, Timestamp }=require("firebase-admin/firestore");
const { onRequest }=require("firebase-functions/v2/https");
const { defineSecret }=require("firebase-functions/params");
initializeApp();
const OPENAI_API_KEY=defineSecret("OPENAI_API_KEY");
const REGION="europe-west1",MAX_PLAYERS=30;
const TOPICS={irregular_verbs:5,simple_present:5,simple_past:5,question_words:5,prepositions:5,some_any_no:5,phrasal_verbs:5,collocations:5,present_progressive:6,will_future:6,modal_verbs:6,adjective_comparison:6,pronouns:6,present_perfect:7,quantities:7,going_to:8,relative_clauses:8,adverbs:8,word_order:5,past_progressive:9,if_clause1:9,tense_mix:9};
const hash=v=>createHash("sha256").update(String(v||"")).digest("hex");const token=()=>randomBytes(24).toString("base64url");const now=()=>Date.now();
function fail(code,message,status=400){const e=new Error(message);e.code=code;e.status=status;throw e;}function txt(v,n){return String(v||"").trim().slice(0,n);}function name(v){const n=txt(v,24).replace(/[<>]/g,"");if(!n)fail("name_required","Bitte einen Namen oder ein Kürzel eingeben.");return n;}function code(v){const c=String(v||"").replace(/\D/g,"").slice(0,6);if(c.length!==6)fail("invalid_code","Ungültiger Rundencode.");return c;}function safeSummary(x={}){const total=Math.max(0,Math.min(500,Math.trunc(Number(x.total||0)))),correct=Math.max(0,Math.min(total,Math.trunc(Number(x.correct||0)))),bestStreak=Math.max(0,Math.min(correct,Math.trunc(Number(x.bestStreak||0)))),score=Math.max(-100000,Math.min(1000000,Math.trunc(Number(x.score||0))));return{total,correct,bestStreak,score};}
function cleanItems(items){if(!Array.isArray(items))return[];const out=[],seen=new Set();for(const raw of items.slice(0,120)){const source=txt(raw?.source,100),targets=[...new Set((Array.isArray(raw?.targets)?raw.targets:[]).map(v=>txt(v,100)).filter(Boolean))].slice(0,4);const k=source.toLowerCase();if(!source||!targets.length||seen.has(k))continue;seen.add(k);out.push({source,targets});}return out;}
function cleanConfig(raw={}){const source=raw.source==="custom"?"custom":"curriculum",durationSec=Math.max(60,Math.min(300,Math.round(Number(raw.durationSec||180)/60)*60)),s=raw.scoring||{},scoring={correctPoints:100,wrongPenalty:[0,25,50,100].includes(Number(s.wrongPenalty))?Number(s.wrongPenalty):50,lockSeconds:[0,3,5,10,30].includes(Number(s.lockSeconds))?Number(s.lockSeconds):5,speedBonus:s.speedBonus!==false,streakBonus:true,showSolution:true,allowNegative:true};if(source==="custom"){const items=cleanItems(raw.items);if(items.length<4)fail("too_few_items","Mindestens 4 Vokabeln sind nötig.");return{version:1,source,setId:txt(raw.setId,80),setTitle:txt(raw.setTitle,80)||"Eigene Vokabeln",direction:["mixed","en-de","de-en"].includes(raw.direction)?raw.direction:"mixed",items,durationSec,scoring,leaderboardMode:["live","after","hidden"].includes(raw.leaderboardMode)?raw.leaderboardMode:"after"};}const grade=[5,6,7,8,9].includes(Number(raw.grade))?Number(raw.grade):9,topics=[...new Set((Array.isArray(raw.topics)?raw.topics:[]).map(String))].filter(t=>TOPICS[t]&&TOPICS[t]<=grade);if(!topics.length)fail("topics_required","Mindestens ein passendes Thema ist nötig.");return{version:1,source,grade:String(grade),topics,durationSec,scoring,leaderboardMode:["live","after","hidden"].includes(raw.leaderboardMode)?raw.leaderboardMode:"after"};}
function officialConfig(grade,topic){const g=[5,6,7,8,9].includes(Number(grade))?Number(grade):9;if(!TOPICS[topic]||TOPICS[topic]>g)fail("invalid_topic","Dieses Thema passt nicht zur Jahrgangsstufe.");return{boardId:`v1_${g}_${topic}`,config:{version:1,source:"curriculum",grade:String(g),topics:[topic],durationSec:120,scoring:{correctPoints:100,wrongPenalty:100,lockSeconds:3,speedBonus:true,streakBonus:true,showSolution:true,allowNegative:true},leaderboardMode:"after"}};}
function cors(req,res){res.set("Access-Control-Allow-Origin","*");res.set("Access-Control-Allow-Headers","Content-Type");res.set("Access-Control-Allow-Methods","POST,OPTIONS");if(req.method==="OPTIONS"){res.status(204).send("");return true;}return false;}
async function uniqueRoomCode(db){for(let i=0;i<12;i++){const c=String(Math.floor(100000+Math.random()*900000)),s=await db.doc(`vocabRushRooms/${c}`).get();if(!s.exists)return c;}fail("code_generation","Bitte erneut versuchen.",500);}
async function createRoom(db,p){const config=cleanConfig(p.config),c=await uniqueRoomCode(db),hostToken=token(),seed=randomBytes(4).readUInt32BE(0),created=now();await db.doc(`vocabRushRooms/${c}`).set({code:c,status:"waiting",config,seed,hostTokenHash:hash(hostToken),playerCount:0,createdAtMs:created,startsAtMs:null,endsAtMs:null,expiresAt:Timestamp.fromMillis(created+8*60*60*1000)});return{code:c,hostToken,config};}
async function joinRoom(db,p){const c=code(p.code),n=name(p.name),roomRef=db.doc(`vocabRushRooms/${c}`),playerId=randomBytes(8).toString("hex"),playerToken=token(),playerRef=roomRef.collection("players").doc(playerId);let config,seed;await db.runTransaction(async tx=>{const snap=await tx.get(roomRef);if(!snap.exists)fail("room_not_found","Runde nicht gefunden.",404);const room=snap.data();if(room.status!=="waiting")fail("room_started","Diese Runde wurde bereits gestartet.");if(Number(room.playerCount||0)>=MAX_PLAYERS)fail("room_full","Diese Runde ist voll.");config=room.config;seed=room.seed;tx.update(roomRef,{playerCount:FieldValue.increment(1)});tx.create(playerRef,{name:n,tokenHash:hash(playerToken),status:"waiting",score:0,total:0,correct:0,bestStreak:0,joinedAtMs:now()});});return{code:c,playerId,playerToken,name:n,config,seed};}
async function startRoom(db,p){const c=code(p.code),ref=db.doc(`vocabRushRooms/${c}`),snap=await ref.get();if(!snap.exists)fail("room_not_found","Runde nicht gefunden.",404);const room=snap.data();if(hash(p.hostToken)!==room.hostTokenHash)fail("forbidden","Keine Berechtigung.",403);if(room.status!=="waiting")fail("already_started","Runde wurde bereits gestartet.");const startsAtMs=now()+5000,endsAtMs=startsAtMs+room.config.durationSec*1000;await ref.update({status:"running",startsAtMs,endsAtMs});return{startsAtMs,endsAtMs};}
function roomStatus(room){if(room.status==="running"&&room.endsAtMs&&now()>room.endsAtMs+2000)return"finished";return room.status;}
async function roomState(db,p){const c=code(p.code),ref=db.doc(`vocabRushRooms/${c}`),snap=await ref.get();if(!snap.exists)fail("room_not_found","Runde nicht gefunden.",404);const room=snap.data(),status=roomStatus(room),isHost=p.hostToken&&hash(p.hostToken)===room.hostTokenHash;let isPlayer=false;if(p.playerId&&p.playerToken){const ps=await ref.collection("players").doc(txt(p.playerId,40)).get();isPlayer=ps.exists&&ps.data().tokenHash===hash(p.playerToken);}if(!isHost&&!isPlayer)fail("forbidden","Keine Berechtigung.",403);const base={code:c,status,config:room.config,seed:room.seed,startsAtMs:room.startsAtMs,endsAtMs:room.endsAtMs,maxPlayers:MAX_PLAYERS,playerCount:Number(room.playerCount||0)};if(isHost){const q=await ref.collection("players").orderBy("joinedAtMs","asc").limit(MAX_PLAYERS).get(),players=q.docs.map(d=>({id:d.id,name:d.data().name,status:d.data().status||"waiting",score:Number(d.data().score||0),correct:Number(d.data().correct||0),total:Number(d.data().total||0)})),leaderboard=[...players].sort((a,b)=>b.score-a.score||b.correct-a.correct).map((x,i)=>({...x,rank:i+1}));return{...base,players,leaderboard};}let leaderboard=[];if(room.config.leaderboardMode==="live"||(room.config.leaderboardMode==="after"&&status==="finished")){const q=await ref.collection("players").orderBy("score","desc").limit(20).get();leaderboard=q.docs.map((d,i)=>({rank:i+1,name:d.data().name,score:Number(d.data().score||0)}));}return{...base,leaderboard};}
async function submitLive(db,p){const c=code(p.code),ref=db.doc(`vocabRushRooms/${c}/players/${txt(p.playerId,40)}`),snap=await ref.get();if(!snap.exists||snap.data().tokenHash!==hash(p.playerToken))fail("forbidden","Keine Berechtigung.",403);const s=safeSummary(p.summary);await ref.update({...s,status:p.finished?"finished":"running",updatedAtMs:now()});return{saved:true};}
async function createHighscoreAttempt(db,p){const n=name(p.name),{boardId,config}=officialConfig(p.grade,p.topic),attemptId=randomBytes(12).toString("hex"),attemptToken=token(),seed=randomBytes(4).readUInt32BE(0),startsAtMs=now()+1000,endsAtMs=startsAtMs+120000;await db.doc(`vocabRushAttempts/${attemptId}`).set({boardId,config,name:n,playerKeyHash:hash(txt(p.playerKey,120)),tokenHash:hash(attemptToken),seed,startsAtMs,endsAtMs,finished:false,expiresAt:Timestamp.fromMillis(now()+60*60*1000)});return{attemptId,attemptToken,config,seed,startsAtMs,endsAtMs,boardId};}
async function finishHighscoreAttempt(db,p){const id=txt(p.attemptId,60),ref=db.doc(`vocabRushAttempts/${id}`),snap=await ref.get();if(!snap.exists)fail("attempt_not_found","Versuch nicht gefunden.",404);const a=snap.data();if(a.tokenHash!==hash(p.attemptToken)||a.finished)fail("forbidden","Ungültiger Versuch.",403);if(now()>a.endsAtMs+20000)fail("attempt_expired","Der Versuch ist abgelaufen.");const s=safeSummary(p.summary),entryRef=db.doc(`vocabRushBoards/${a.boardId}/entries/${a.playerKeyHash}`);let personalBest=false;await db.runTransaction(async tx=>{const old=await tx.get(entryRef);if(!old.exists||Number(old.data().score||-Infinity)<s.score){personalBest=true;tx.set(entryRef,{name:a.name,...s,updatedAtMs:now()});}tx.update(ref,{finished:true,summary:s,finishedAtMs:now()});});return{personalBest,leaderboard:await leaderboardRows(db,a.boardId)};}
async function leaderboardRows(db,boardId){const q=await db.collection(`vocabRushBoards/${boardId}/entries`).orderBy("score","desc").limit(20).get();return q.docs.map((d,i)=>({rank:i+1,name:d.data().name,score:Number(d.data().score||0)}));}
async function leaderboard(db,p){const {boardId}=officialConfig(p.grade,p.topic);return{leaderboard:await leaderboardRows(db,boardId)};}
const vocabSchema={type:"object",additionalProperties:false,required:["suggestedTitle","sourceLanguage","targetLanguage","items"],properties:{suggestedTitle:{type:"string"},sourceLanguage:{type:"string",enum:["en"]},targetLanguage:{type:"string",enum:["de"]},items:{type:"array",minItems:1,maxItems:120,items:{type:"object",additionalProperties:false,required:["source","targets","needsReview","note"],properties:{source:{type:"string"},targets:{type:"array",minItems:1,maxItems:4,items:{type:"string"}},needsReview:{type:"boolean"},note:{type:["string","null"]}}}}}};
function responseText(json){if(typeof json.output_text==="string")return json.output_text;for(const out of json.output||[])for(const c of out.content||[])if(c.type==="output_text"&&typeof c.text==="string")return c.text;return"";}
async function extractVocabulary(db,req,p){const image=String(p.imageDataUrl||"");if(!/^data:image\/(jpeg|png|webp);base64,/i.test(image)||image.length>12_000_000)fail("invalid_image","Bitte ein JPG-, PNG- oder WebP-Bild bis etwa 8 MB verwenden.");const day=new Date().toISOString().slice(0,10),ip=String(req.ip||req.headers["x-forwarded-for"]||"unknown"),rateRef=db.doc(`vocabRushAiRate/${day}-${hash(ip).slice(0,32)}`);await db.runTransaction(async tx=>{const s=await tx.get(rateRef),count=Number(s.data()?.count||0);if(count>=30)fail("rate_limit","Zu viele Fotoimporte heute. Bitte später erneut versuchen.",429);tx.set(rateRef,{count:count+1,day},{merge:true});});const body={model:"gpt-5.6-luna",store:false,reasoning:{effort:"low"},input:[{role:"system",content:[{type:"input_text",text:"Du extrahierst Vokabelpaare aus fotografierten Unterrichtsseiten. Übernimm nur Wörter und Wendungen, die tatsächlich sichtbar sind. Erfinde keine Übersetzungen. Ignoriere Seitenzahlen, Aufgabenstellungen, Überschriften und Beispiele, sofern sie keine Vokabeleinträge sind. Erkenne Englisch als source und Deutsch als target. Mehrere deutsche Bedeutungen desselben Eintrags kommen in targets. Wenn Zuordnung, Lesbarkeit oder Bedeutung unsicher ist, needsReview=true und kurze note. Keine personenbezogenen Daten übernehmen."}]},{role:"user",content:[{type:"input_text",text:"Extrahiere die sichtbaren Englisch-Deutsch-Vokabelpaare. Liefere nur das Schema."},{type:"input_image",image_url:image,detail:"high"}]}],text:{format:{type:"json_schema",name:"vocab_rush_extract",strict:true,schema:vocabSchema}}};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${OPENAI_API_KEY.value()}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await r.json();if(!r.ok)fail("ai_error","Die Vokabelerkennung ist gerade nicht verfügbar.",502);let parsed;try{parsed=JSON.parse(responseText(json));}catch{fail("ai_invalid","Die erkannten Vokabeln konnten nicht sicher verarbeitet werden.",502);}parsed.items=cleanItems(parsed.items).map((x,i)=>({...x,needsReview:Boolean(parsed.items?.[i]?.needsReview),note:txt(parsed.items?.[i]?.note,160)||null}));if(!parsed.items.length)fail("no_vocab","Auf dem Bild wurden keine eindeutigen Vokabelpaare gefunden.");return parsed;}
exports.vocabRushApi=onRequest({region:REGION,secrets:[OPENAI_API_KEY],timeoutSeconds:90,memory:"512MiB",cors:false},async(req,res)=>{if(cors(req,res))return;if(req.method!=="POST")return res.status(405).json({ok:false,error:{message:"POST erforderlich."}});const db=getFirestore();try{const action=txt(req.body?.action,60),p=req.body?.payload||{};let data;if(action==="extractVocabulary")data=await extractVocabulary(db,req,p);else if(action==="createRoom")data=await createRoom(db,p);else if(action==="joinRoom")data=await joinRoom(db,p);else if(action==="startRoom")data=await startRoom(db,p);else if(action==="roomState")data=await roomState(db,p);else if(action==="submitLive")data=await submitLive(db,p);else if(action==="createHighscoreAttempt")data=await createHighscoreAttempt(db,p);else if(action==="finishHighscoreAttempt")data=await finishHighscoreAttempt(db,p);else if(action==="leaderboard")data=await leaderboard(db,p);else fail("unknown_action","Unbekannte Aktion.",404);res.json({ok:true,data});}catch(e){console.error("Vocab Rush:",e.code||e.name,e.message);res.status(e.status||400).json({ok:false,error:{code:e.code||"error",message:e.message||"Unbekannter Fehler"}});}});
