(() => {
  'use strict';
  const D = window.GradeCrewEscapePrototype;
  if (!D) throw new Error('Escape-Room-Daten fehlen.');
  const check = D.validateWorldDefinition();
  const $ = id => document.getElementById(id);
  const KEY = `gradecrew-escape-save:${D.world.id}:${D.world.version}`;
  const fresh = () => ({
    version:D.world.version, startedAt:null, activeSeconds:0, room:'classroom', completedQuestions:[], attempts:{}, inventory:[], selectedItem:null,
    flags:{deskOpened:false,flashlightFound:false,flashlightReady:false,code4:false,code7:false,code8:false,classroomDoorOpen:false,lockerHint:false,lockerSolved:false,accessCard:false,officeDoorOpen:false,officeSequenceKnown:false,keyBoardSolved:false,mainKey:false,finalAuthorized:false,gameComplete:false},
    hintsUsed:0,puzzleCompletions:0,currentHintStep:0,feedback:null
  });
  let S=fresh(), activeQuestion=null, activePuzzle=null, puzzleInput=[], timer=null, lastTick=Date.now(), docActive=!document.hidden;

  function event(name,detail={}) { window.dispatchEvent(new CustomEvent('gradecrew:escape-event',{detail:{name,worldId:D.world.id,worldVersion:D.world.version,room:S.room,...detail}})); }
  function save(){try{localStorage.setItem(KEY,JSON.stringify(S));}catch{}}
  function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');return s?.version===D.world.version&&s.startedAt&&!s.flags?.gameComplete?s:null;}catch{return null}}
  function clearSave(){try{localStorage.removeItem(KEY);}catch{}}
  function show(id){['homeView','gameView','resultView'].forEach(x=>$(x).hidden=x!==id)}
  function msg(t){$('messageBar').textContent=t}
  function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function q(id){return D.questions.find(x=>x.id===id)}
  function done(id){return S.completedQuestions.includes(id)}
  function markDone(id){if(!done(id))S.completedQuestions.push(id);save();renderProgress()}
  function renderProgress(){const n=S.completedQuestions.length;$('progressText').textContent=`${n} / ${D.questions.length} Fragen`;$('progressFill').style.width=`${Math.round(n/D.questions.length*100)}%`}

  function startTimer(){stopTimer();lastTick=Date.now();timer=setInterval(()=>{const now=Date.now();if(docActive&&!S.flags.gameComplete&&!$('gameView').hidden){S.activeSeconds+=Math.max(0,Math.round((now-lastTick)/1000));$('timer').textContent=fmt(S.activeSeconds);if(S.activeSeconds%10===0)save()}lastTick=now},1000)}
  function stopTimer(){if(timer)clearInterval(timer);timer=null}
  document.addEventListener('visibilitychange',()=>{docActive=!document.hidden;lastTick=Date.now()});

  function addItem(id,label,icon){if(!S.inventory.some(x=>x.id===id)){S.inventory.push({id,label,icon});event('item.collected',{itemId:id});save()}renderInventory()}
  function removeItem(id){S.inventory=S.inventory.filter(x=>x.id!==id);if(S.selectedItem===id)S.selectedItem=null;save();renderInventory()}
  function renderInventory(){const c=$('inventory');c.replaceChildren();$('inventoryCount').textContent=`${S.inventory.length} / 3`;if(!S.inventory.length){const p=document.createElement('p');p.className='emptyText';p.textContent='Noch leer.';c.append(p);return}S.inventory.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='inventoryItem';b.classList.toggle('selected',S.selectedItem===item.id);b.setAttribute('aria-pressed',String(S.selectedItem===item.id));b.textContent=`${item.icon} ${item.label}`;b.onclick=()=>{S.selectedItem=S.selectedItem===item.id?null:item.id;renderInventory();msg(S.selectedItem?`${item.label} ausgewählt. Tippe jetzt auf ein passendes Ziel.`:'Auswahl aufgehoben.')};c.append(b)})}

  function setRoom(room){S.room=room;S.currentHintStep=0;$('roomScene').className=`roomScene room-${room}`;const i=D.world.rooms.findIndex(x=>x.id===room);$('roomEyebrow').textContent=`RAUM ${i+1} VON ${D.world.rooms.length}`;$('roomTitle').textContent=D.world.rooms[i].label;renderMission();renderHotspots();save();event('room.entered',{roomId:room})}
  function renderHotspots(){document.querySelectorAll('.hotspot').forEach(b=>b.classList.remove('completed'));const mark=a=>document.querySelector(`[data-action="${a}"]`)?.classList.add('completed');if(S.room==='classroom'){if(done('q1'))mark('desk');if(S.flags.flashlightReady)mark('cabinet');if(done('q2'))mark('shelf');if(done('q3'))mark('computer');if(S.flags.code8)mark('board');if(S.flags.classroomDoorOpen)mark('door')}else if(S.room==='hallway'){if(S.flags.lockerSolved)mark('desk');if(done('q4'))mark('shelf');if(S.flags.officeDoorOpen)mark('door')}else{if(done('q6'))mark('computer');if(S.flags.keyBoardSolved)mark('shelf');if(done('q7'))mark('cabinet');if(S.flags.finalAuthorized)mark('door')}}
  function renderMission(){let t='';if(S.room==='classroom'){t=!S.flags.deskOpened?'Untersuche das Lehrerpult.':!S.flags.flashlightReady?'Die Batterie muss irgendwo nützlich sein.':!(S.flags.code4&&S.flags.code7&&S.flags.code8)?'Finde alle drei Teile des Türcodes.':'Öffne die Klassenzimmertür mit dem vollständigen Code.';$('codeDisplay').hidden=!(S.flags.code4&&S.flags.code7&&S.flags.code8)}else if(S.room==='hallway'){$('codeDisplay').hidden=true;t=!S.flags.lockerHint?'Suche nach einem Hinweis auf den richtigen Spind.':!S.flags.accessCard?'Öffne Spind 12 und finde die Zugangskarte.':!S.flags.officeDoorOpen?'Nutze die Zugangskarte am Sekretariat.':'Betritt das Sekretariat.'}else{$('codeDisplay').hidden=true;t=!S.flags.officeSequenceKnown?'Aktiviere den Sekretariatscomputer.':!S.flags.keyBoardSolved?'Nutze die Symbolfolge am Schlüsselbrett.':!S.flags.mainKey?'Öffne den Notfallkasten.':!S.flags.finalAuthorized?'Gehe zur Notentriegelung.':'Drücke die Notentriegelung.'}$('missionText').textContent=t}

  const solvedHandlers={
    q1Battery(){S.flags.deskOpened=true;addItem('battery','Batterie','🔋');msg('Die Schublade öffnet sich. Du findest eine Batterie.')},
    q2Code(){S.flags.code4=true;msg('Unter dem Regal leuchtet die Zahl 4 auf. Codefragment gefunden.')},
    q3Code(){S.flags.code7=true;msg('Der Computer zeigt die Zahl 7. Codefragment gefunden.')},
    q4Locker(){S.flags.lockerHint=true;msg('Am Schwarzen Brett steht: „Fach 12 enthält einen wichtigen Hinweis.“')},
    q5Office(){removeItem('access-card');S.flags.officeDoorOpen=true;msg('Sicherheitsprüfung bestanden. Die Sekretariatstür ist entriegelt.')},
    q6Sequence(){S.flags.officeSequenceKnown=true;msg('Der Computer zeigt die Folge ★ ◆ ●.')},
    q7Key(){S.flags.mainKey=true;addItem('main-key','Hauptschlüssel','🔑');msg('Der Hauptschlüssel wird freigegeben.')},
    q8Final(){removeItem('main-key');S.flags.finalAuthorized=true;msg('Letzte Prüfung bestanden. Drücke jetzt die Notentriegelung.')}
  };
  function openQuestion(id,handler){if(done(id)){msg('Diese Lernaufgabe ist bereits gelöst.');return}const x=q(id);if(!x)return;activeQuestion={id,handler};$('questionTitle').textContent=`Aufgabe ${id.slice(1)}`;$('questionPrompt').textContent=x.prompt;$('questionFeedback').hidden=true;$('questionFeedback').className='questionFeedback';$('questionHintBtn').textContent='Fachlicher Hinweis';$('questionOptions').replaceChildren(...x.options.map((o,i)=>{const l=document.createElement('label');l.className='answerOption';const r=document.createElement('input');r.type='radio';r.name='answer';r.value=i;const s=document.createElement('span');s.textContent=o;l.append(r,s);return l}));$('questionDialog').showModal();event('question.presented',{questionId:id})}
  $('questionHintBtn').onclick=()=>{if(!activeQuestion)return;const x=q(activeQuestion.id);$('questionFeedback').hidden=false;$('questionFeedback').className='questionFeedback';$('questionFeedback').textContent=`💡 ${x.hint}`;S.hintsUsed++;save();event('hint.used',{kind:'question',questionId:x.id})};
  $('questionForm').addEventListener('submit',e=>{e.preventDefault();if(!activeQuestion)return;const picked=$('questionOptions').querySelector('input:checked');if(!picked){$('questionFeedback').hidden=false;$('questionFeedback').textContent='Wähle zuerst eine Antwort.';return}const x=q(activeQuestion.id),ok=Number(picked.value)===x.correctIndex;S.attempts[x.id]=(S.attempts[x.id]||0)+1;event('question.answered',{questionId:x.id,correct:ok,attempt:S.attempts[x.id]});const box=$('questionFeedback');box.hidden=false;if(ok){box.className='questionFeedback success';box.textContent=`Richtig. ${x.explanation}`;finishQuestion(x.id,activeQuestion.handler);setTimeout(()=>$('questionDialog').close(),450)}else if(S.attempts[x.id]>=3){box.className='questionFeedback error';box.textContent=`Die Lösung ist ${x.options[x.correctIndex]}. Du kannst weiterspielen.`;finishQuestion(x.id,activeQuestion.handler);setTimeout(()=>$('questionDialog').close(),850)}else{box.className='questionFeedback error';box.textContent='Noch nicht richtig. Versuch es noch einmal.';save()}});
  function finishQuestion(id,handler){markDone(id);solvedHandlers[handler]?.();renderMission();renderHotspots();save()}

  const symbols={triangle:'▲',circle:'●',square:'■',star:'★',diamond:'◆'};
  function openPuzzle(id,title,text){activePuzzle=id;puzzleInput=[];$('puzzleTitle').textContent=title;$('puzzleText').textContent=text;$('puzzleFeedback').hidden=true;renderPuzzle();$('puzzleDialog').showModal();event('puzzle.started',{puzzleId:id})}
  function renderPuzzle(){const body=$('puzzleBody');body.replaceChildren();if(activePuzzle==='board-pattern'){const g=document.createElement('div');g.className='symbolGrid';['7','8','10'].forEach(v=>{const b=document.createElement('button');b.type='button';b.className='symbolButton';b.textContent=v;b.onclick=()=>checkBoard(v);g.append(b)});body.append(g);return}if(activePuzzle==='door-code'){const d=document.createElement('div');d.className='keypadDisplay';d.textContent=puzzleInput.join('').padEnd(3,'–');body.append(d);const k=document.createElement('div');k.className='keypad';for(let n=1;n<=9;n++){const b=document.createElement('button');b.type='button';b.textContent=n;b.onclick=()=>{if(puzzleInput.length<3)puzzleInput.push(String(n));renderPuzzle();if(puzzleInput.length===3)checkPuzzle()};k.append(b)}body.append(k);return}const allowed=activePuzzle==='locker-sequence'?D.world.lockerSequence:D.world.keySequence;const seq=document.createElement('div');seq.className='symbolSequence';for(let i=0;i<3;i++){const s=document.createElement('span');s.textContent=puzzleInput[i]?symbols[puzzleInput[i]]:'·';seq.append(s)}body.append(seq);const g=document.createElement('div');g.className='symbolGrid';[...new Set(allowed)].forEach(v=>{const b=document.createElement('button');b.type='button';b.className='symbolButton';b.textContent=symbols[v];b.onclick=()=>{if(puzzleInput.length<3)puzzleInput.push(v);renderPuzzle();if(puzzleInput.length===3)checkPuzzle()};g.append(b)});body.append(g)}
  function puzzleError(){const b=$('puzzleFeedback');b.hidden=false;b.className='questionFeedback error';b.textContent='Das passt noch nicht. Setze das Rätsel zurück und prüfe deine Hinweise.';event('puzzle.failed',{puzzleId:activePuzzle})}
  function checkBoard(v){if(v!=='8')return puzzleError();S.flags.code8=true;solvePuzzle('board-pattern','Muster gelöst. Das dritte Codefragment ist 8.')}
  function checkPuzzle(){const answer=puzzleInput.join('|');let ok=false;if(activePuzzle==='door-code')ok=puzzleInput.join('')===D.world.classroomDoorCode;if(activePuzzle==='locker-sequence')ok=answer===D.world.lockerSequence.join('|');if(activePuzzle==='key-sequence')ok=answer===D.world.keySequence.join('|');if(!ok)return puzzleError();if(activePuzzle==='door-code')S.flags.classroomDoorOpen=true;if(activePuzzle==='locker-sequence'){S.flags.lockerSolved=true;S.flags.accessCard=true;addItem('access-card','Zugangskarte','🪪')}if(activePuzzle==='key-sequence')S.flags.keyBoardSolved=true;const text=activePuzzle==='door-code'?'Die Klassenzimmertür ist entriegelt.':activePuzzle==='locker-sequence'?'Spind 12 öffnet sich. Du findest eine Zugangskarte.':'Das richtige Fach öffnet sich. Der Notfallkasten ist jetzt zugänglich.';solvePuzzle(activePuzzle,text)}
  function solvePuzzle(id,text){S.puzzleCompletions++;event('puzzle.completed',{puzzleId:id});save();renderMission();renderHotspots();const b=$('puzzleFeedback');b.hidden=false;b.className='questionFeedback success';b.textContent='Gelöst!';setTimeout(()=>{$('puzzleDialog').close();msg(text)},350)}
  $('puzzleResetBtn').onclick=()=>{puzzleInput=[];renderPuzzle();$('puzzleFeedback').hidden=true};

  function useItem(target){if(!S.selectedItem)return false;if(S.selectedItem==='battery'&&target==='cabinet'&&S.flags.flashlightFound){S.flags.flashlightReady=true;removeItem('battery');event('item.used',{itemId:'battery',target:'flashlight'});msg('Die Batterie passt. Die Taschenlampe funktioniert jetzt.');renderMission();renderHotspots();save();return true}if(S.selectedItem==='access-card'&&target==='door'&&S.room==='hallway'){openQuestion('q5','q5Office');return true}if(S.selectedItem==='main-key'&&target==='door'&&S.room==='office'){openQuestion('q8','q8Final');return true}msg('Dieser Gegenstand passt hier nicht.');event('item.mismatch',{itemId:S.selectedItem,target});return true}
  $('roomScene').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(useItem(a))return;S.room==='classroom'?classroom(a):S.room==='hallway'?hallway(a):office(a)});
  function classroom(a){if(a==='desk')return openQuestion('q1','q1Battery');if(a==='cabinet'){S.flags.flashlightFound=true;msg(S.flags.flashlightReady?'Die Taschenlampe ist einsatzbereit.':'Im Schrank liegt eine Taschenlampe ohne Batterie. Wähle die Batterie im Inventar und tippe erneut auf den Schrank.');save();return}if(a==='shelf')return S.flags.flashlightReady?openQuestion('q2','q2Code'):msg('Unter dem Regal ist es zu dunkel.');if(a==='computer')return openQuestion('q3','q3Code');if(a==='board')return S.flags.code8?msg('Die Tafel zeigt: 2 – 4 – 6 – 8.'):openPuzzle('board-pattern','Muster an der Tafel','2 – 4 – 6 – ? Welche Zahl setzt das Muster fort?');if(a==='door'){if(!(S.flags.code4&&S.flags.code7&&S.flags.code8))return msg('Das Zahlenschloss braucht einen dreistelligen Code. Dir fehlen noch Hinweise.');if(!S.flags.classroomDoorOpen)return openPuzzle('door-code','Zahlenschloss','Gib den dreistelligen Code ein.');setRoom('hallway');msg('Du bist auf dem Flur. Wo könnte die Zugangskarte sein?')}}
  function hallway(a){if(a==='shelf')return openQuestion('q4','q4Locker');if(a==='desk'){if(!S.flags.lockerHint)return msg('Viele Spinde. Ohne Hinweis wäre das nur Raten.');if(S.flags.lockerSolved)return msg('Spind 12 ist bereits geöffnet.');return openPuzzle('locker-sequence','Spind 12','Stelle die Symbolfolge ▲ ● ■ nach.')}if(a==='door'){if(S.flags.officeDoorOpen){setRoom('office');return msg('Du bist im Sekretariat. Finde die Notentriegelung.')}if(!S.flags.accessCard)return msg('Die Tür hat einen Kartenleser.');return msg('Wähle die Zugangskarte im Inventar und tippe erneut auf die Sekretariatstür.')}msg('Hier gibt es gerade nichts Wichtiges.')}
  function office(a){if(a==='computer')return openQuestion('q6','q6Sequence');if(a==='shelf'){if(!S.flags.officeSequenceKnown)return msg('Am Schlüsselbrett sind viele Symbole. Du brauchst zuerst die richtige Reihenfolge.');if(S.flags.keyBoardSolved)return msg('Das richtige Schlüsselfach ist bereits geöffnet.');return openPuzzle('key-sequence','Schlüsselbrett','Der Computer zeigte ★ ◆ ●. Stelle die Folge nach.')}if(a==='cabinet'){if(!S.flags.keyBoardSolved)return msg('Der Notfallkasten ist noch verriegelt.');return openQuestion('q7','q7Key')}if(a==='door'){if(S.flags.finalAuthorized)return complete();if(!S.flags.mainKey)return msg('Die Notentriegelung verlangt den Hauptschlüssel.');return msg('Wähle den Hauptschlüssel im Inventar und tippe erneut auf die Notentriegelung.')}msg('Hier gibt es gerade nichts Wichtiges.')}

  const hints={classroom:['Beginne am Lehrerpult.','Im Schrank liegt etwas, das eine Batterie gebrauchen könnte.','Mit Licht kannst du unter das Regal schauen. Computer und Tafel liefern weitere Code-Hinweise.'],hallway:['Schau zuerst am Schwarzen Brett nach.','Der Hinweis nennt einen bestimmten Spind.','Die Zugangskarte gehört zum Kartenleser am Sekretariat.'],office:['Der Computer ist der erste sinnvolle Anlaufpunkt.','Merke dir die Symbolfolge und suche sie am Schlüsselbrett.','Nach dem Schlüsselbrett ist der Notfallkasten wichtig.']};
  $('hintBtn').onclick=()=>{const list=hints[S.room],i=Math.min(S.currentHintStep,list.length-1);msg(`💡 ${list[i]}`);S.currentHintStep++;S.hintsUsed++;save();event('hint.used',{kind:'escape',step:i+1})};

  function complete(){S.flags.gameComplete=true;save();stopTimer();$('resultQuestions').textContent=`${S.completedQuestions.length} / ${D.questions.length}`;$('resultPuzzles').textContent=String(S.puzzleCompletions);$('resultHints').textContent=String(S.hintsUsed);$('resultTime').textContent=fmt(S.activeSeconds);show('resultView');clearSave();event('game.completed',{activeSeconds:S.activeSeconds,hintsUsed:S.hintsUsed})}
  function start(resume=false){if(!check.ok){alert('Der Prototyp ist nicht startbar. Prüfe die Lehrer-Vorschau.');return}if(!resume)S=fresh();if(!S.startedAt)S.startedAt=new Date().toISOString();show('gameView');setRoom(S.room||'classroom');renderInventory();renderProgress();$('timer').textContent=fmt(S.activeSeconds||0);startTimer();save();event(resume?'game.resumed':'game.started')}
  function renderTeacher(){const p=$('preflightStatus');p.classList.toggle('invalid',!check.ok);p.textContent=check.ok?`✓ Preflight bestanden · ${check.warnings.length?`${check.warnings.length} Hinweis(e)`:'keine Blocker'}`:`✕ Preflight fehlgeschlagen · ${check.errors.join(' · ')}`;const route=['Klassenzimmer: Q1 → Batterie/Taschenlampe → Q2/Q3 + Tafel → Code 784 → Tür','Flur: Q4 → Spind 12 → ▲ ● ■ → Zugangskarte → Q5 → Sekretariat','Sekretariat: Q6 → ★ ◆ ● → Schlüsselbrett → Q7 → Hauptschlüssel → Q8 → Notentriegelung'];$('teacherRoute').replaceChildren(...route.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('teacherQuestions').replaceChildren(...D.questions.map(x=>{const d=document.createElement('div');d.className='teacherQuestion';const a=document.createElement('strong');a.textContent=`${x.id.toUpperCase()}: ${x.prompt}`;const b=document.createElement('span');b.textContent=`Lösung: ${x.options[x.correctIndex]} · Hinweis: ${x.hint}`;d.append(a,b);return d}))}

  $('teacherPreviewBtn').onclick=()=>{renderTeacher();$('teacherDialog').showModal()};$('startBtn').onclick=()=>start(false);$('resumeBtn').onclick=()=>{const s=load();if(s){S=s;start(true)}};$('restartBtn').onclick=()=>{if(confirm('Spiel wirklich neu starten? Dein aktueller Fortschritt geht verloren.')){clearSave();S=fresh();start(false)}};$('homeBtn').onclick=()=>{S=fresh();show('homeView');updateResume()};document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{S.feedback=Number(b.dataset.feedback);document.querySelectorAll('[data-feedback]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));event('feedback.selected',{rating:S.feedback})});
  function updateResume(){$('resumeBtn').hidden=!load()}window.addEventListener('beforeunload',()=>{if(S.startedAt&&!S.flags.gameComplete)save()});
  if(!check.ok)console.error('Escape preflight failed',check.errors);updateResume();renderTeacher();show('homeView');
})();
