#!/usr/bin/env python3
"""Validate authored tasks and emit their deterministic C++ view."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Content/Tasks/tasks.json"
OUTPUT = ROOT / "Source/Lerninsel/Core/IslandTasks.generated.h"
FIELDS = ("id", "title", "type", "instruction", "goal", "variants", "hidden_clue", "clue_location", "follow_up", "completion_flag")


def load():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(data, list) or not data:
        raise ValueError("task catalog must be a non-empty list")
    by_id = {}
    for task in data:
        for field in FIELDS:
            if not isinstance(task.get(field), (str, int)) or task[field] == "":
                raise ValueError(f"task {task.get('id')}: missing {field}")
        if not isinstance(task["id"], int) or task["id"] <= 0 or task["id"] in by_id:
            raise ValueError(f"invalid or duplicate task id: {task['id']}")
        if len(task.get("hints", [])) != 3 or any(not isinstance(h, str) or not h.strip() for h in task["hints"]):
            raise ValueError(f"task {task['id']}: exactly three non-empty hints required")
        deps = task.get("prerequisites")
        if not isinstance(deps, list) or any(not isinstance(d, int) for d in deps) or len(set(deps)) != len(deps):
            raise ValueError(f"task {task['id']}: invalid prerequisites")
        by_id[task["id"]] = task
    for task in data:
        if task["id"] in task["prerequisites"] or any(d not in by_id for d in task["prerequisites"]):
            raise ValueError(f"task {task['id']}: self or unknown prerequisite")

    visiting, visited = set(), set()
    def visit(task_id):
        if task_id in visiting:
            raise ValueError(f"dependency cycle at task {task_id}")
        if task_id in visited:
            return
        visiting.add(task_id)
        for dep in by_id[task_id]["prerequisites"]:
            visit(dep)
        visiting.remove(task_id)
        visited.add(task_id)
    for task_id in by_id:
        visit(task_id)
    reachable = {t["id"] for t in data if not t["prerequisites"]}
    changed = True
    while changed:
        changed = False
        for task in data:
            if task["id"] not in reachable and set(task["prerequisites"]).issubset(reachable):
                reachable.add(task["id"])
                changed = True
    if reachable != set(by_id):
        raise ValueError(f"unreachable tasks: {sorted(set(by_id) - reachable)}")
    if len(data) > 63:
        raise ValueError("at most 63 task bits supported")
    return data


def emit(data):
    lines = ["// Generated by Tools/generate_tasks.py; edit Content/Tasks/tasks.json.", "#pragma once", "#include <array>", "#include <cstdint>", "#include <string>", "#include <vector>", "namespace Island {", "struct TaskDefinition { int Id; const char* Title; const char* Type; const char* Instruction; const char* Goal; const char* Variants; std::array<const char*,3> Hints; const char* HiddenClue; const char* ClueLocation; std::vector<int> Prerequisites; const char* FollowUp; const char* CompletionFlag; };", f"inline const std::array<TaskDefinition,{len(data)}>& TaskDefinitions() {{", " static const std::array<TaskDefinition," + str(len(data)) + "> Tasks = {{"]
    q = lambda value: json.dumps(value, ensure_ascii=False)
    for task in data:
        row = [str(task["id"])] + [q(task[key]) for key in ("title", "type", "instruction", "goal", "variants")]
        row += ["{{" + ",".join(q(x) for x in task["hints"]) + "}}", q(task["hidden_clue"]), q(task["clue_location"]), "{" + ",".join(map(str, task["prerequisites"])) + "}", q(task["follow_up"]), q(task["completion_flag"])]
        lines.append("  {" + ",".join(row) + "},")
    lines += [" }};", " return Tasks;", "}", "inline bool TaskDefinitionsValid() {", " const auto& tasks=TaskDefinitions();", " for(std::size_t i=0;i<tasks.size();++i){const auto& t=tasks[i];if(t.Id<=0||!t.Title||!t.Type||!t.Instruction||!t.Goal||!t.Variants||!t.HiddenClue||!t.ClueLocation||!t.FollowUp||!t.CompletionFlag)return false;for(const char* h:t.Hints)if(!h||!*h)return false;for(std::size_t j=i+1;j<tasks.size();++j)if(t.Id==tasks[j].Id)return false;}", " return true;", "}", "enum class TaskStage { Locked, Available, Active, Solved };", "inline int TaskIndex(int id){const auto& tasks=TaskDefinitions();for(std::size_t i=0;i<tasks.size();++i)if(tasks[i].Id==id)return static_cast<int>(i);return -1;}", "inline std::uint64_t TaskBit(int id){const int i=TaskIndex(id);return i<0?0:(std::uint64_t{1}<<i);}", "inline TaskStage TaskStageFor(int id,std::uint64_t solved,std::uint64_t active=0){const int i=TaskIndex(id);if(i<0)return TaskStage::Locked;const std::uint64_t bit=std::uint64_t{1}<<i;if(solved&bit)return TaskStage::Solved;for(int dep:TaskDefinitions()[i].Prerequisites){const auto d=TaskBit(dep);if(!d||!(solved&d))return TaskStage::Locked;}return active&bit?TaskStage::Active:TaskStage::Available;}", "}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    try:
        rendered = emit(load())
        if "--check" in sys.argv:
            if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
                raise SystemExit("generated task header is stale")
        else:
            OUTPUT.write_text(rendered, encoding="utf-8")
            print(f"validated {len(load())} task definitions")
    except (ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"task catalog error: {exc}")
