import unreal
tools=unreal.AssetToolsHelpers.get_asset_tools()
mat=unreal.load_asset('/Game/Materials/M_Expedition')
if not mat:
    mat=tools.create_asset('M_Expedition','/Game/Materials',unreal.Material,unreal.MaterialFactoryNew())
    edit=unreal.MaterialEditingLibrary
    tint=edit.create_material_expression(mat,unreal.MaterialExpressionVectorParameter,-350,0)
    tint.set_editor_property('parameter_name','Tint')
    tint.set_editor_property('default_value',unreal.LinearColor(.3,.6,.4,1))
    edit.connect_material_property(tint,'',unreal.MaterialProperty.MP_BASE_COLOR)
    rough=edit.create_material_expression(mat,unreal.MaterialExpressionConstant,-350,160)
    rough.set_editor_property('r',.77)
    edit.connect_material_property(rough,'',unreal.MaterialProperty.MP_ROUGHNESS)
    edit.recompile_material(mat);unreal.EditorAssetLibrary.save_loaded_asset(mat)
maps=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
if not maps.new_level('/Game/Maps/Amazonas'): raise RuntimeError('Could not create own map')
actors=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
sun=actors.spawn_actor_from_class(unreal.DirectionalLight,unreal.Vector(0,0,1000),unreal.Rotator(-48,-28,0))
comp=sun.get_component_by_class(unreal.DirectionalLightComponent)
comp.set_editor_property('intensity',3.5)
comp.set_editor_property('light_color',unreal.Color(255,235,202,255))
comp.set_editor_property('light_source_angle',5.0)
sky=actors.spawn_actor_from_class(unreal.SkyLight,unreal.Vector(0,0,1000))
c=sky.get_component_by_class(unreal.SkyLightComponent)
c.set_editor_property('source_type',unreal.SkyLightSourceType.SLS_SPECIFIED_CUBEMAP)
c.set_editor_property('cubemap',unreal.load_asset('/Engine/MapTemplates/Sky/DaylightAmbientCubemap'))
c.set_editor_property('intensity',1.7);c.set_editor_property('lower_hemisphere_is_black',False)
maps.save_current_level()
unreal.log('EXPEDITION_MAP_CREATED')
unreal.SystemLibrary.quit_editor()
