import {installLiveControls} from './live-controls.mjs';
import {createOutbox} from './outbox.mjs';import {getDevAdapter,safeAdapterContext} from './sdk.mjs';
const STATUS={waiting:'Offen',working:'In Arbeit',preview:'Zum Prüfen',accepted:'Erledigt',error:'Fehler',rejected:'Zurückgestellt'};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
const rectOf=(r)=>{const w=innerWidth,h=innerHeight,x=Math.max(0,Math.min(w,r.left)),y=Math.max(0,Math.min(h,r.top));return {x,y,width:Math.max(0,Math.min(r.right,w)-x),height:Math.max(0,Math.min(r.bottom,h)-y),viewportWidth:w,viewportHeight:h};};
function selector(node){if(node.id)return '#'+CSS.escape(node.id);const parts=[];for(let n=node;n&&n!==document.body&&parts.length<6;n=n.parentElement){const siblings=[...(n.parentElement?.children||[])].filter(x=>x.localName===n.localName);parts.unshift(n.localName+(siblings.length>1?`:nth-of-type(${siblings.indexOf(n)+1})`:''));}return parts.join(' > ').slice(0,500);}
export function installVisualToolbar({apiBase='/__review/tasks',scene=()=>'',dataMode='local',projectId='gradecrew'}={}){
 if(document.getElementById('gc-review-tool'))return;const host=el('div');host.id='gc-review-tool';host.style.cssText='position:fixed;inset:auto auto 12px 12px;margin:0;padding:0;border:0;background:transparent;z-index:2147483000;color:#173f55;font:13px system-ui;';
 const s=host.attachShadow({mode:'open'});s.innerHTML=`<style>
 *{box-sizing:border-box}button,input,textarea,select{font:inherit}button{cursor:pointer}button:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #2563eb;outline-offset:2px}[hidden]{display:none!important}.launcher{width:54px;height:36px;border:0;border-radius:9px;background:#242a32;color:white;display:flex;align-items:center;justify-content:center;gap:2px;padding:3px 5px;box-shadow:0 3px 15px #0002;touch-action:none;font-weight:800;letter-spacing:.01em}.launcher img{display:block;width:25px;height:25px;object-fit:contain;flex:none}.launcher span{font-size:12px;line-height:1}.menu,.list,.draft{position:fixed;background:#fff;color:#173f55;border:1px solid #d7e1ee;box-shadow:0 14px 38px #10284130;border-radius:12px;padding:12px;width:min(320px,calc(100vw - 24px));max-height:calc(100dvh - 24px);overflow:auto;font:13px system-ui}.menu{left:12px;bottom:54px}.menu button[data-action]{display:block;width:100%;text-align:left;padding:11px;border:0;background:transparent;border-radius:8px;color:inherit}.menu button[data-action]:hover{background:#eef4ff}.menu small,.meta{display:block;color:#64748b;font-size:11px;line-height:1.4}.menu small{padding:8px}.live{color:#087b65!important}.draft{width:min(360px,calc(100vw - 24px))}.draft h2,.list h2{font-size:15px;margin:0 0 9px}.draft textarea{width:100%;height:90px;resize:vertical;padding:10px;border:1px solid #c4d2e4;border-radius:8px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.actions button,.card button,.list>button{background:white;border:1px solid #cfdae7;border-radius:8px;padding:8px 10px;color:#173f55}.actions .primary{background:#2563eb;color:white;border-color:#2563eb}.message{font-size:12px;line-height:1.4;margin-top:8px}.error{color:#b42318}.preview{display:block;max-height:150px;max-width:100%;border-radius:7px;margin:8px 0}.overlay{position:fixed;inset:0;cursor:crosshair;touch-action:none;background:#173f5503}.box{position:fixed;pointer-events:none;border:2px solid #2563eb;background:#2563eb16}.label{position:fixed;pointer-events:none;background:#173f55;color:white;font-size:11px;padding:3px 6px;border-radius:5px}.list{right:12px;bottom:54px;max-height:min(78dvh,720px);width:min(380px,calc(100vw - 24px))}.card{border:1px solid #dce5ef;border-radius:10px;padding:10px;margin:8px 0}.card p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5}.card select{border:1px solid #cfdae7;border-radius:6px;padding:5px;background:white;color:inherit}.card .row{display:flex;gap:8px;justify-content:space-between;align-items:center}.close{float:right;background:none!important;border:0!important;font-size:18px;padding:0!important}.toast{position:fixed;left:12px;bottom:54px;max-width:340px;background:#173f55;color:white;border-radius:9px;padding:10px;box-shadow:0 8px 20px #0002}.list input{width:100%;padding:8px;border:1px solid #cfdae7;border-radius:7px}.dirty{color:#9a3412}button:disabled{cursor:wait;opacity:.65}
 .menu,.draft{background:#20252f;color:#f5f7fa;border-color:#3a4350}.menu button[data-action]{color:#f5f7fa}.menu button[data-action]:hover{background:#303845}.menu small{color:#b8becb}.draft textarea{background:#161b23;color:#f5f7fa;border-color:#738198}.draft .actions button{background:#303845;color:#f5f7fa;border-color:#434d5c}.draft .actions .primary{background:#239f78;border-color:#239f78}.menu .mode{color:#c5cfdd}
 .drawing{position:fixed;inset:0;width:100vw;height:100dvh;touch-action:none;pointer-events:none}.draw-tools{position:fixed;right:12px;top:12px;display:flex;gap:5px;padding:6px;background:#20252f;border-radius:10px;box-shadow:0 8px 20px #0005;max-width:calc(100vw - 24px);flex-wrap:wrap}.draw-tools button,.draft-media button,.shot-tools button{padding:7px 9px;border:1px solid #576475;border-radius:7px;background:#303845;color:white}.draw-tools button[aria-pressed=true],.draw-tools [data-draw-done],.shot-tools button[aria-pressed=true],.shot-tools [data-shot-done]{background:#239f78;border-color:#239f78}.draft-media{display:flex;gap:8px;margin-top:9px}.draft-media button{flex:1}.shot-editor{position:fixed;inset:0;background:#10151deb;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;padding:12px;color:white}.shot-editor canvas{display:block;max-width:calc(100vw - 24px);max-height:calc(100dvh - 80px);width:auto;height:auto;object-fit:contain;touch-action:none;background:#fff;box-shadow:0 10px 30px #0009;cursor:crosshair}.shot-tools{display:flex;gap:7px;flex-wrap:wrap;justify-content:center}
 </style><button class="launcher" aria-label="ET – Entwicklungswerkzeug öffnen" title="ET – Entwicklungswerkzeug"><img src="/__dev/assets/et-touch-icon.png" width="25" height="25" alt="" aria-hidden="true"><span>ET</span></button><nav class="menu" hidden aria-label="Entwicklungswerkzeug">
 <small class="mode"></small><button data-action="select">Element auswählen</button><button data-action="area">Bereich markieren</button><button data-action="draw">✎ Auf Seite zeichnen</button><button data-action="page">Zur ganzen Seite etwas sagen</button><button data-action="list">Visuelle Hinweise <span class="count"></span></button><button data-action="hub">Projektzentrale öffnen</button><button data-action="reload" hidden>Vorschau aktualisieren</button><small class="live">● Lokal verbunden</small><small class="pending"></small></nav>
 <div class="overlay" hidden><div class="box" hidden></div><div class="label" hidden></div><canvas class="drawing" hidden></canvas><div class="draw-tools" hidden><button data-pen type="button" aria-pressed="true">✎ Stift</button><button data-arrow type="button" aria-pressed="false">➜ Pfeil</button><button data-draw-clear type="button">Löschen</button><button data-draw-cancel type="button">Abbrechen</button><button data-draw-done type="button">Fertig</button></div></div>
 <section class="draft" hidden role="dialog" aria-label="Auftrag zur Auswahl"><h2>Was möchtest du damit tun?</h2><img class="preview" hidden alt="Freiwillig aufgenommener Ausschnitt"><textarea maxlength="3000" placeholder="Was soll hier anders werden?"></textarea><div class="message" role="status"></div><div class="draft-media"><button data-draft-draw type="button" title="Kreise oder Pfeile auf der sichtbaren Seite zeichnen">✎ Markieren</button><button data-capture type="button" title="Der Browser fragt nach Freigabe für eine Bildschirmaufnahme">Bild aufnehmen</button></div><div class="actions"><button data-cancel>Abbrechen</button><button class="primary" data-save>Auftrag speichern</button></div></section>
 <section class="shot-editor" hidden role="dialog" aria-label="Auf dem Screenshot zeichnen"><div class="shot-tools"><button data-shot-pen type="button" aria-pressed="true">✎ Stift</button><button data-shot-arrow type="button" aria-pressed="false">➜ Pfeil</button><button data-shot-clear type="button">Zeichnung löschen</button><button data-shot-cancel type="button">Abbrechen</button><button data-shot-done type="button">Fertig</button></div><canvas aria-label="Screenshot zum Markieren"></canvas><div class="shot-message" role="status"></div></section>
 <section class="list" hidden aria-label="Visuelle Hinweise"><button class="close" aria-label="Liste schließen">×</button><h2>Visuelle Hinweise</h2><input type="search" placeholder="Hinweise suchen" aria-label="Hinweise suchen"><div class="list-message" role="status"></div><div class="cards"></div><button data-export>JSON sichern</button></section><div class="toast" hidden role="status"></div>`;
 const legacyStyle=document.createElement('style');legacyStyle.textContent='[data-review-toggle],[data-review-panel]{display:none!important}html.reviewPanelOpen body{margin-right:0!important}';document.head.append(legacyStyle);document.querySelector('[data-review-close]')?.click();document.documentElement.classList.remove('reviewPanelOpen');document.body.append(host);
 const hasPopover=typeof host.showPopover==='function';
 if(hasPopover){host.setAttribute('popover','manual');host.showPopover();}
 const pageDocument=document;
 function syncModalLayer(){
  const modal=[...pageDocument.querySelectorAll('dialog[open]')].at(-1),parent=modal||pageDocument.body;
  if(host.parentElement===parent)return;
  if(hasPopover&&host.matches(':popover-open'))host.hidePopover();
  if(modal){host.removeAttribute('popover');modal.append(host);}
  else{pageDocument.body.append(host);if(hasPopover){host.setAttribute('popover','manual');host.showPopover();}}
 }
 syncModalLayer();const modalObserver=new MutationObserver(()=>{if(!pageDocument.defaultView){modalObserver.disconnect();return;}syncModalLayer();});modalObserver.observe(pageDocument.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open']});
 document.addEventListener('fullscreenchange',()=>{syncModalLayer();if(hasPopover&&host.parentElement===document.body&&!host.matches(':popover-open'))host.showPopover();});
 const q=sel=>s.querySelector(sel),menu=q('.menu'),overlay=q('.overlay'),box=q('.box'),label=q('.label'),draft=q('.draft'),list=q('.list'),input=q('textarea'),message=q('.message'),drawing=q('.drawing'),drawTools=q('.draw-tools'),shotEditor=q('.shot-editor'),shotCanvas=q('.shot-editor canvas');
 sessionStorage.setItem('gc-dev-last-project',projectId);const outbox=createOutbox(localStorage,'gradecrew-dev-outbox-v1');let mode='',start=null,target=null,region=null,image=null,imageIsScreenshot=false,paused=false,sending=false,tasks=[],selectedNode=null;let captureWanted=false,refreshPending=false,pendingPayload=null,captureRevision=0,strokes=[],drawKind='pen',drawFromDraft=false,previousStrokes=[],shotBase=null,shotStrokes=[],shotKind='pen',shotActive=null;
 q('.mode').textContent=dataMode==='staging'?'Lokaler Code · Staging-Daten (Speichern ändert Staging-Tests)':'Lokaler Code · '+projectId;
 const toast=text=>{q('.toast').textContent=text;q('.toast').hidden=false;setTimeout(()=>q('.toast').hidden=true,4500);};
 const updatePending=()=>{try{const n=outbox.read().length;q('.pending').textContent=n?`${n} Hinweis(e) lokal gesichert · Abgleich offen`:'';}catch(e){q('.pending').textContent=e.message;}};
 const pause=()=>{if(!paused){try{getDevAdapter()?.pause?.();paused=true;}catch{}}};const resume=()=>{if(paused){try{getDevAdapter()?.resume?.();}catch{}paused=false;}};
 function cancel(){captureRevision++;host.style.visibility='';q('[data-save]').disabled=false;mode='';start=null;overlay.hidden=true;box.hidden=true;label.hidden=true;drawing.hidden=true;drawTools.hidden=true;shotEditor.hidden=true;draft.hidden=true;menu.hidden=true;image=null;imageIsScreenshot=false;strokes=[];drawFromDraft=false;shotBase=null;shotStrokes=[];resume();}
 const place=(node,x,y)=>{node.hidden=false;const r=node.getBoundingClientRect();node.style.left=Math.max(12,Math.min(x,innerWidth-r.width-12))+'px';node.style.top=Math.max(12,Math.min(y,innerHeight-r.height-12))+'px';};
 const beneath=(x,y)=>{overlay.hidden=true;const node=document.elementFromPoint(x,y);overlay.hidden=false;return node;};
 function openDrawing(){mode='draw';overlay.hidden=false;drawing.hidden=false;drawTools.hidden=false;drawing.width=Math.max(1,Math.round(innerWidth));drawing.height=Math.max(1,Math.round(innerHeight));drawKind='pen';q('[data-pen]').setAttribute('aria-pressed','true');q('[data-arrow]').setAttribute('aria-pressed','false');drawPaint();}
 function begin(kind){captureRevision++;q('[data-save]').disabled=false;menu.hidden=true;list.hidden=true;image=null;imageIsScreenshot=false;target=null;region=null;strokes=[];drawFromDraft=false;pendingPayload=null;input.readOnly=false;q('[data-save]').textContent=q('[data-save]').dataset.live?'An KI senden':'Auftrag speichern';q('[data-draft-draw]').textContent='✎ Markieren';q('[data-draft-draw]').title='Kreise oder Pfeile auf der sichtbaren Seite zeichnen';input.value='';message.textContent='';message.classList.remove('error');q('.preview').hidden=true;pause();if(kind==='page'||kind==='capturepage'){mode='';place(draft,innerWidth/2-180,innerHeight/2-100);input.focus();if(kind==='capturepage')void takeScreenshot(null);return;}mode=kind==='select'?'select':'area';captureWanted=kind==='screenshot';if(kind==='draw')openDrawing();else overlay.hidden=false;}
 function drawPaint(){const ctx=drawing.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,drawing.width,drawing.height);ctx.strokeStyle='#f0284b';ctx.fillStyle='#f0284b';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of strokes){const points=stroke.points;if(!points.length)continue;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);if(stroke.kind==='arrow'&&points.length>1){const end=points.at(-1);ctx.lineTo(end.x,end.y);}else for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();if(stroke.kind==='arrow'&&points.length>1){const a=points[0],b=points.at(-1),angle=Math.atan2(b.y-a.y,b.x-a.x),length=18;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-length*Math.cos(angle-.55),b.y-length*Math.sin(angle-.55));ctx.lineTo(b.x-length*Math.cos(angle+.55),b.y-length*Math.sin(angle+.55));ctx.closePath();ctx.fill();}}}
 function drawingCheckpoint(){return strokes.map(stroke=>({kind:stroke.kind,points:stroke.kind==='arrow'?[stroke.points[0],stroke.points.at(-1)]:stroke.points.filter((_,i)=>i%Math.max(1,Math.ceil(stroke.points.length/12))===0)}));}
 function drawingContext(){const data=[];for(const stroke of drawingCheckpoint()){const next=[...data,stroke];if(JSON.stringify({drawing:next}).length>3800)break;data.push(stroke);}return JSON.stringify({drawing:data,coordinateSystem:'viewport pixels',viewport:[innerWidth,innerHeight]});}
 function drawingOnlyImage(){if(!strokes.length)return;const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(drawing.width,drawing.height));canvas.width=Math.max(1,Math.round(drawing.width*scale));canvas.height=Math.max(1,Math.round(drawing.height*scale));canvas.getContext('2d').drawImage(drawing,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');if(data.length<=2800000){image={mimeType:'image/png',base64:data.split(',')[1]};imageIsScreenshot=false;q('.preview').src=data;q('.preview').hidden=false;}}
 function finishDrawing(){if(!strokes.length){toast('Zeichne zuerst einen Kreis, Strich oder Pfeil.');return;}const points=strokes.flatMap(x=>x.points),left=Math.max(0,Math.min(...points.map(p=>p.x))-20),top=Math.max(0,Math.min(...points.map(p=>p.y))-20),right=Math.min(innerWidth,Math.max(...points.map(p=>p.x))+20),bottom=Math.min(innerHeight,Math.max(...points.map(p=>p.y))+20);if(!region)region={x:left,y:top,width:right-left,height:bottom-top,viewportWidth:innerWidth,viewportHeight:innerHeight};if(!target){const node=beneath((left+right)/2,(top+bottom)/2);if(node&&node!==host)target={tag:node.localName,selector:selector(node),classes:'',text:(node.textContent||'').trim().slice(0,160),rect:rectOf(node.getBoundingClientRect())};}mode='';drawFromDraft=false;overlay.hidden=true;drawing.hidden=true;drawTools.hidden=true;place(draft,innerWidth/2-180,innerHeight/2-100);drawingOnlyImage();message.textContent='Markierung hinzugefügt. Du kannst jetzt den Auftrag senden.';input.focus();}
 function cancelDrawing(){if(!drawFromDraft){cancel();return;}strokes=previousStrokes;drawFromDraft=false;mode='';overlay.hidden=true;drawing.hidden=true;drawTools.hidden=true;draft.hidden=false;input.focus();}
 function renderShot(){if(!shotBase)return;const ctx=shotCanvas.getContext('2d');ctx.clearRect(0,0,shotCanvas.width,shotCanvas.height);ctx.drawImage(shotBase,0,0,shotCanvas.width,shotCanvas.height);ctx.strokeStyle='#ef234a';ctx.fillStyle='#ef234a';ctx.lineWidth=Math.max(3,shotCanvas.width/250);ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of shotStrokes){const points=stroke.points;if(!points.length)continue;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);if(stroke.kind==='arrow'&&points.length>1){const end=points.at(-1);ctx.lineTo(end.x,end.y);}else for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();if(stroke.kind==='arrow'&&points.length>1){const a=points[0],b=points.at(-1),angle=Math.atan2(b.y-a.y,b.x-a.x),length=Math.max(12,shotCanvas.width/50);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-length*Math.cos(angle-.55),b.y-length*Math.sin(angle-.55));ctx.lineTo(b.x-length*Math.cos(angle+.55),b.y-length*Math.sin(angle+.55));ctx.closePath();ctx.fill();}}}
 function shotPoint(e){const r=shotCanvas.getBoundingClientRect();return {x:Math.round((e.clientX-r.left)*shotCanvas.width/r.width),y:Math.round((e.clientY-r.top)*shotCanvas.height/r.height)};}
 function startShotEditor(){if(!image)return;const source='data:'+image.mimeType+';base64,'+image.base64,base=new Image();base.onload=()=>{shotBase=base;shotCanvas.width=base.naturalWidth;shotCanvas.height=base.naturalHeight;shotStrokes=[];shotKind='pen';q('[data-shot-pen]').setAttribute('aria-pressed','true');q('[data-shot-arrow]').setAttribute('aria-pressed','false');q('.shot-message').textContent='Zeichne direkt auf dem Bild. Mit Fertig wird genau dieses Bild gesendet.';draft.hidden=true;shotEditor.hidden=false;renderShot();};base.onerror=()=>{message.textContent='Bild konnte nicht zum Zeichnen geöffnet werden.';};base.src=source;}
 function cancelShotEditor(){shotEditor.hidden=true;shotBase=null;shotStrokes=[];shotActive=null;draft.hidden=false;input.focus();}
 function finishShotEditor(){if(!shotStrokes.length){cancelShotEditor();return;}const data=shotCanvas.toDataURL('image/png');if(data.length>2800000){q('.shot-message').textContent='Das markierte Bild ist zu groß. Entferne einige Striche oder nimm einen kleineren Ausschnitt auf.';return;}image={mimeType:'image/png',base64:data.split(',')[1]};imageIsScreenshot=true;q('.preview').src=data;q('.preview').hidden=false;message.textContent='Markierungen sind auf dem Screenshot gespeichert.';cancelShotEditor();}
 async function takeScreenshot(rect){const revision=captureRevision;let hiddenForCapture=false;q('[data-save]').disabled=true;message.textContent='Wähle im Browser die aktuelle Ansicht zur Aufnahme.';try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error(strokes.length?'Bildschirmaufnahme nicht verfügbar. Deine Zeichnung und Positionsdaten bleiben erhalten.':'Dieser Browser bietet keine Bildschirmaufnahme. Der Hinweis kann ohne Bild gespeichert werden.');const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});try{if(revision!==captureRevision)return;host.style.visibility='hidden';hiddenForCapture=true;const video=document.createElement('video');video.srcObject=stream;video.muted=true;await video.play();await new Promise(r=>setTimeout(r,100));const track=stream.getVideoTracks()[0],settings=track.getSettings();if(strokes.length&&settings.displaySurface!=='browser')throw Error('Bitte für die Zeichnung den aktuellen Tab wählen. Zeichnung und Positionsdaten bleiben erhalten.');const canCrop=rect&&settings.displaySurface==='browser';const sx=canCrop?rect.x*video.videoWidth/rect.viewportWidth:0,sy=canCrop?rect.y*video.videoHeight/rect.viewportHeight:0,sw=canCrop?rect.width*video.videoWidth/rect.viewportWidth:video.videoWidth,sh=canCrop?rect.height*video.videoHeight/rect.viewportHeight:video.videoHeight;const canvas=document.createElement('canvas');const scale=Math.min(1,1200/Math.max(sw,sh));canvas.width=Math.max(1,Math.round(sw*scale));canvas.height=Math.max(1,Math.round(sh*scale));const ctx=canvas.getContext('2d');ctx.drawImage(video,sx,sy,sw,sh,0,0,canvas.width,canvas.height);if(strokes.length)ctx.drawImage(drawing,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');if(revision!==captureRevision)return;if(data.length>2800000)throw Error('Aufnahme ist zu groß. Hinweis ohne Bild möglich.');image={mimeType:'image/png',base64:data.split(',')[1]};imageIsScreenshot=true;q('[data-draft-draw]').textContent='✎ Im Bild markieren';q('[data-draft-draw]').title='Kreise oder Pfeile direkt auf dem aufgenommenen Bild zeichnen';q('.preview').src=data;q('.preview').hidden=false;message.textContent=strokes.length?'Ansicht mit Zeichnung aufgenommen.':canCrop?'Ausschnitt aufgenommen.':rect?'Gewählte Ansicht aufgenommen; bei Fenster/Monitor wird das ganze Bild gespeichert.':'Ansicht aufgenommen.';}finally{stream.getTracks().forEach(t=>t.stop());if(hiddenForCapture&&revision===captureRevision)host.style.visibility='';}}catch(e){if(revision===captureRevision){message.textContent=/permission|notallowed|denied/i.test(e.name+' '+e.message)?'Bildaufnahme nicht freigegeben. Dein Bereich, deine Markierung und dein Text bleiben erhalten.':e.message;message.classList.toggle('error',!/permission|notallowed|denied/i.test(e.name+' '+e.message));}}finally{if(revision===captureRevision)q('[data-save]').disabled=false;}if(revision===captureRevision)input.focus();}
 q('.launcher').onclick=()=>{if(!draft.hidden){input.focus();return;}if(!overlay.hidden){cancel();return;}list.hidden=true;menu.hidden=!menu.hidden;updatePending();};
 s.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const a=button.dataset.action;if(a==='list'){menu.hidden=true;list.hidden=false;void load();}else if(a==='hub'){menu.hidden=true;location.assign('/__dev?project='+encodeURIComponent(projectId));}else if(a==='reload'){menu.hidden=true;requestReload();}else begin(a);});
 overlay.addEventListener("pointerdown",e=>{if(!e.isPrimary||e.button!==0||e.target.closest('button'))return;e.preventDefault();if(mode==='draw'){if(strokes.length>=12){toast('Maximal 12 Markierungen pro Auftrag.');return;}start={id:e.pointerId};strokes.push({kind:drawKind,points:[{x:Math.round(e.clientX),y:Math.round(e.clientY)}]});overlay.setPointerCapture(e.pointerId);drawPaint();return;}if(mode==='area'){start={x:e.clientX,y:e.clientY,id:e.pointerId};overlay.setPointerCapture(e.pointerId);box.hidden=false;Object.assign(box.style,{left:e.clientX+'px',top:e.clientY+'px',width:'0px',height:'0px'});}});
 overlay.addEventListener("pointermove",e=>{if(mode==='draw'&&start?.id===e.pointerId){const points=strokes.at(-1).points,p={x:Math.round(e.clientX),y:Math.round(e.clientY)};if(drawKind==='arrow')points[1]=p;else if(points.length<400)points.push(p);drawPaint();return;}if(mode==='select'){const n=beneath(e.clientX,e.clientY);if(!n||n===host)return;selectedNode=n;const r=n.getBoundingClientRect();box.hidden=false;Object.assign(box.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});label.hidden=false;label.textContent=n.localName;label.style.left=Math.max(4,r.left)+'px';label.style.top=Math.max(4,r.top-24)+'px';}else if(start&&e.pointerId===start.id){const x=Math.max(0,Math.min(start.x,e.clientX)),y=Math.max(0,Math.min(start.y,e.clientY));Object.assign(box.style,{left:x+'px',top:y+'px',width:Math.min(innerWidth-x,Math.abs(e.clientX-start.x))+'px',height:Math.min(innerHeight-y,Math.abs(e.clientY-start.y))+'px'});}});
 overlay.addEventListener("pointerup",e=>{if(mode==='draw'){if(start?.id===e.pointerId){const points=strokes.at(-1).points;if(points.length===1)points.push({x:Math.round(e.clientX),y:Math.round(e.clientY)});start=null;drawPaint();}return;}if(mode==='select'){const n=beneath(e.clientX,e.clientY);if(!n||n===host){cancel();return;}target={tag:n.localName,selector:selector(n),classes:'',text:/^(button|label|h[1-6])$/.test(n.localName)?(n.textContent||'').trim().slice(0,160):'',rect:rectOf(n.getBoundingClientRect())};}else{if(!start||start.id!==e.pointerId)return;const r=box.getBoundingClientRect();region=rectOf(r);start=null;if(region.width<8||region.height<8){cancel();toast('Bitte einen größeren Bereich ziehen.');return;}}if(region&&!target){const n=beneath(region.x+region.width/2,region.y+region.height/2);if(n&&n!==host)target={tag:n.localName,selector:selector(n),classes:'',text:/^(button|label|h[1-6]|span|p)$/.test(n.localName)||!n.children.length?(n.textContent||'').trim().slice(0,160):'',rect:rectOf(n.getBoundingClientRect())};}mode='';overlay.hidden=true;box.hidden=true;label.hidden=true;place(draft,e.clientX+12,e.clientY+12);input.focus();if(captureWanted)void takeScreenshot(region);});overlay.addEventListener("pointercancel",()=>cancelDrawing());
 q('[data-pen]').onclick=()=>{drawKind='pen';q('[data-pen]').setAttribute('aria-pressed','true');q('[data-arrow]').setAttribute('aria-pressed','false');};q('[data-arrow]').onclick=()=>{drawKind='arrow';q('[data-arrow]').setAttribute('aria-pressed','true');q('[data-pen]').setAttribute('aria-pressed','false');};q('[data-draw-clear]').onclick=()=>{strokes=[];drawPaint();};q('[data-draw-cancel]').onclick=cancelDrawing;q('[data-draw-done]').onclick=finishDrawing;
 q('[data-draft-draw]').onclick=()=>{if(imageIsScreenshot){startShotEditor();return;}previousStrokes=[...strokes];drawFromDraft=true;draft.hidden=true;openDrawing();};
 q('[data-shot-pen]').onclick=()=>{shotKind='pen';q('[data-shot-pen]').setAttribute('aria-pressed','true');q('[data-shot-arrow]').setAttribute('aria-pressed','false');};q('[data-shot-arrow]').onclick=()=>{shotKind='arrow';q('[data-shot-arrow]').setAttribute('aria-pressed','true');q('[data-shot-pen]').setAttribute('aria-pressed','false');};q('[data-shot-clear]').onclick=()=>{shotStrokes=[];renderShot();};q('[data-shot-cancel]').onclick=cancelShotEditor;q('[data-shot-done]').onclick=finishShotEditor;
 shotCanvas.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;e.preventDefault();if(shotStrokes.length>=12){q('.shot-message').textContent='Maximal 12 Markierungen pro Bild.';return;}shotActive=e.pointerId;shotStrokes.push({kind:shotKind,points:[shotPoint(e)]});shotCanvas.setPointerCapture(e.pointerId);renderShot();});shotCanvas.addEventListener('pointermove',e=>{if(shotActive!==e.pointerId)return;const points=shotStrokes.at(-1).points,p=shotPoint(e);if(shotKind==='arrow')points[1]=p;else if(points.length<400)points.push(p);renderShot();});shotCanvas.addEventListener('pointerup',e=>{if(shotActive!==e.pointerId)return;const points=shotStrokes.at(-1).points;if(points.length===1)points.push(shotPoint(e));shotActive=null;renderShot();});shotCanvas.addEventListener('pointercancel',()=>{if(shotActive!==null)shotStrokes.pop();shotActive=null;renderShot();});
 q('[data-capture]').onclick=()=>void takeScreenshot(strokes.length?null:region);
 q('[data-cancel]').onclick=cancel;
 async function post(payload){const response=await fetch(apiBase,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let result;try{result=await response.json();}catch{throw Error('Serverbeleg fehlt. Der Hinweis bleibt lokal gesichert.');}if(!response.ok||!result.task?.id)throw Error(result.message||'Serverbeleg fehlt.');return result;}
 q('[data-save]').onclick=async()=>{if(sending)return;const text=input.value.trim();if(!text){message.textContent='Schreibe einen kurzen Auftrag.';input.focus();return;}const c=safeAdapterContext();const payload=pendingPayload||{text,projectId,source:document.querySelector('canvas')?'canvas':'web',clientRequestId:crypto.randomUUID(),url:location.pathname+location.search,view:c.view,scene:scene()||c.scene,target,region,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio:devicePixelRatio||1},context:{app:'Browser',entity:c.entity,checkpoint:strokes.length?drawingContext():'',scrollX,scrollY}};if(image&&!pendingPayload)payload.screenshot=image;try{if(!pendingPayload)outbox.put(payload);pendingPayload=payload;input.readOnly=true;}catch(e){message.textContent='Lokal sichern fehlgeschlagen: '+e.message;message.classList.add('error');return;}sending=true;q('[data-save]').disabled=true;try{const result=await post(payload);outbox.remove(payload.clientRequestId);pendingPayload=null;cancel();toast('Hinweis '+result.task.id.slice(0,8)+' auf dem lokalen Server gespeichert.');void load();}catch(e){message.textContent=e.message+' Lokal gesichert. Erneut abgleichen im Menü oder beim nächsten Öffnen.';message.classList.add('error');q('[data-save]').textContent='Serverabgleich wiederholen';toast('Hinweis lokal gesichert · Serverabgleich offen.');}finally{sending=false;q('[data-save]').disabled=false;updatePending();}};
 async function flush(){try{for(const payload of outbox.read()){await post(payload);outbox.remove(payload.clientRequestId);}updatePending();}catch(e){q('.pending').textContent='Abgleich offen: '+e.message;}}
 async function load(){try{tasks=[];let cursor='';do{const u=new URL(apiBase,location.href);u.searchParams.set('projectId',projectId);if(cursor)u.searchParams.set('cursor',cursor);const response=await fetch(u,{cache:'no-store'});if(!response.ok)throw Error('Hinweise konnten nicht geladen werden.');const j=await response.json();tasks.push(...j.tasks);cursor=j.nextCursor||'';}while(cursor);q('.count').textContent='('+tasks.length+')';render();q('.list-message').textContent=tasks.length?'':'Noch keine Hinweise für dieses Projekt.';}catch(e){q('.list-message').textContent=e.message;}}
 function render(){const cards=q('.cards');cards.replaceChildren();const search=q('.list input').value.toLowerCase();for(const [i,task]of tasks.entries()){if(search&&!task.text.toLowerCase().includes(search))continue;const card=el('article','','card'),head=el('strong',`${i+1}. ${STATUS[task.status]}`),text=el('p',task.text),meta=el('small',`${task.source||'web'} · ${task.view||'Ansicht'} · ${new Date(task.createdAt).toLocaleString('de-DE')}`,'meta');card.append(head,text,meta);if(task.screenshotUrl){const img=el('img','','preview');img.src=task.screenshotUrl;img.alt='Gespeicherter Ausschnitt';card.append(img);}const row=el('div','','row'),jump=el('button','Stelle öffnen'),select=el('select');for(const [v,name]of Object.entries(STATUS)){const o=el('option',name);o.value=v;o.selected=task.status===v;select.append(o);}select.setAttribute('aria-label','Status');select.onchange=async()=>{try{const response=await fetch(apiBase+'/'+task.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value,error:''})});if(!response.ok)throw Error('Status konnte nicht gespeichert werden.');await load();}catch(e){toast(e.message);}};jump.onclick=()=>{list.hidden=true;if(task.scene&&typeof window.openReviewScene==='function')window.openReviewScene(task.scene);try{const n=task.target?.selector&&document.querySelector(task.target.selector);if(n){n.scrollIntoView({block:'center',behavior:'smooth'});n.animate?.([{outline:'3px solid #2563eb'},{outline:'3px solid transparent'}],{duration:1500});}else window.scrollTo({top:task.context?.scrollY||0,left:task.context?.scrollX||0,behavior:'smooth'});}catch{toast('Stelle hat sich geändert. Hinweis bleibt erhalten.');}};row.append(jump,select);card.append(row);cards.append(card);}}
 q('.list input').oninput=render;q('.close').onclick=()=>list.hidden=true;q('[data-export]').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({projectId,tasks,outbox:outbox.read()},null,2)],{type:'application/json'}));a.download='gradecrew-visuelle-hinweise.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!shotEditor.hidden){e.preventDefault();e.stopImmediatePropagation();cancelShotEditor();return;}if(mode||!draft.hidden){e.preventDefault();e.stopImmediatePropagation();if(mode==='draw')cancelDrawing();else cancel();}menu.hidden=true;list.hidden=true;}} ,true);
 s.addEventListener('keydown',e=>{if(!draft.hidden){e.stopPropagation();if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();q('[data-save]').click();}}});
 document.addEventListener('gradecrew:visual-tasks-changed',()=>void load());window.addEventListener('online',()=>void flush());
 function requestReload(){if(getDevAdapter()?.isDirty?.()){toast('Bitte zuerst Änderungen am Test speichern.');return;}try{const cp=getDevAdapter()?.captureCheckpoint?.();if(cp)sessionStorage.setItem('gc-dev-checkpoint-'+projectId,JSON.stringify({version:1,value:cp,scrollY}));}catch{}location.reload();}
 document.addEventListener('gradecrew:dev-source-change',e=>{if(e.detail?.cssOnly){for(const link of document.querySelectorAll('link[rel="stylesheet"]')){const u=new URL(link.href);if(u.origin===location.origin){u.searchParams.set('gcLive',Date.now());link.href=u.href;}}toast('Darstellung aktualisiert.');}else{if(draft.hidden&&!sending&&!mode&&getDevAdapter()?.captureCheckpoint&&!getDevAdapter()?.isDirty?.()){requestReload();return;}refreshPending=true;q('[data-action="reload"]').hidden=false;toast('Code geändert. Menü → Vorschau aktualisieren. Deine Ansicht bleibt bis dahin offen.');}});
 try{const saved=JSON.parse(sessionStorage.getItem('gc-dev-checkpoint-'+projectId)||'null');if(saved?.version===1){const restore=async()=>{if(!getDevAdapter()?.restoreCheckpoint)return;try{await getDevAdapter().restoreCheckpoint(saved.value);scrollTo(0,saved.scrollY||0);sessionStorage.removeItem('gc-dev-checkpoint-'+projectId);}catch(e){toast('Rücksprung nicht möglich: '+e.message);}};document.addEventListener('gradecrew:dev-adapter-ready',()=>void restore(),{once:true});}}catch{}
 installLiveControls({host,shadow:s,projectId,apiBase,scene,getPayload:text=>{const c=safeAdapterContext(),selected=!draft.hidden;let checkpoint=strokes.length?drawingContext():'';try{const node=selected&&target?.selector?document.querySelector(target.selector):null;if(node&&!strokes.length){const css=getComputedStyle(node);checkpoint=JSON.stringify({selector:target.selector,inlineStyle:node.getAttribute('style')||'',backgroundColor:css.backgroundColor,color:css.color,fontSize:css.fontSize});}}catch{}return {text,projectId,source:document.querySelector('canvas')?'canvas':'web',clientRequestId:crypto.randomUUID(),url:location.pathname+location.search,view:c.view,scene:scene()||c.scene,target:selected?target:null,region:selected?region:null,viewport:{width:innerWidth,height:innerHeight,devicePixelRatio:devicePixelRatio||1},context:{app:'Browser',entity:c.entity,checkpoint,scrollX,scrollY},...(selected&&image?{screenshot:image}:{})};},notify:toast,resume});updatePending();void flush();void load();return {host,begin,cancel,flush,load};
}
