import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
const hash=text=>createHash('sha256').update(text).digest('hex'),safeId=value=>{if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(value))throw Error('Projekt-ID ungültig.');return value;};
async function atomic(file,value){const tmp=file+'.'+randomUUID()+'.tmp';try{await fs.writeFile(tmp,value,{mode:0o600,flag:'wx'});await fs.rename(tmp,file);}finally{await fs.rm(tmp,{force:true}).catch(()=>{});}}
export function createEditHistory(folder){let serial=Promise.resolve();const run=fn=>{const pending=serial.catch(()=>{}).then(fn);serial=pending;return pending;};
async function read(project){await fs.mkdir(folder,{recursive:true,mode:0o700});const file=path.join(folder,safeId(project.id)+'.json');try{const raw=await fs.readFile(file,'utf8'),data=JSON.parse(raw);if(data.version!==1||!Array.isArray(data.entries)||!Number.isInteger(data.cursor)||data.cursor<0||data.cursor>data.entries.length)throw Error('Änderungshistorie beschädigt. Datei bleibt erhalten.');return {file,data};}catch(e){if(e.code==='ENOENT')return {file,data:{version:1,cursor:0,entries:[]}};throw e;}}
const status=data=>({canUndo:data.cursor>0,canRedo:data.cursor<data.entries.length,cursor:data.cursor,total:data.entries.length,lastSummary:data.cursor?data.entries[data.cursor-1].summary:''});
async function resolve(project,relative){if(typeof relative!=='string'||relative.includes('\\')||relative.split('/').some(x=>!x||x==='.'||x==='..'||x.startsWith('.'))||path.isAbsolute(relative)||! /\.(html|css|js|mjs|json|svg)$/.test(relative))throw Error('Dateipfad für Live-Änderung ungültig.');const root=await fs.realpath(project.root),file=await fs.realpath(path.join(root,relative));if(!file.startsWith(root+path.sep))throw Error('Änderung verlässt das Projekt.');return file;}
async function writeSet(changes,side){const written=[];try{for(const item of changes){await atomic(item.file,item[side]);written.push(item);} }catch(e){for(const item of written.reverse())await atomic(item.file,item[side==='after'?'before':'after']).catch(()=>{});throw e;}}
return {async state(project){return run(async()=>status((await read(project)).data));},
async apply(project,proposal,{allowedFiles,noteId='',requestId=randomUUID()}={}){return run(async()=>{const {file,data}=await read(project);const duplicate=data.entries.find(x=>x.requestId===requestId);if(duplicate)return {entry:duplicate,history:status(data)};if(!proposal||typeof proposal.summary!=='string'||proposal.summary.length>1500||!Array.isArray(proposal.changes)||proposal.changes.length>12)throw Error('KI-Änderung hat kein gültiges Patchformat.');const updates=[],seen=new Set();for(const change of proposal.changes){if(seen.has(change.path)||!allowedFiles?.has(change.path)||!Array.isArray(change.replacements)||change.replacements.length>30)throw Error('KI versucht eine nicht freigegebene Datei zu ändern.');seen.add(change.path);const real=await resolve(project,change.path),before=await fs.readFile(real,'utf8');if(before.length>1024*1024)throw Error('Quelldatei zu groß.');const expected=allowedFiles.get(change.path);if(expected!==undefined&&hash(before)!==expected)throw Error('Die Datei wurde zwischenzeitlich geändert. Dein vorhandener Stand bleibt erhalten.');let after=before;for(const r of change.replacements){if(typeof r.search!=='string'||!r.search||typeof r.replace!=='string'||r.replace.length>200000)throw Error('KI-Patch enthält ungültigen Suchtext.');const first=after.indexOf(r.search);if(first<0||after.indexOf(r.search,first+r.search.length)>=0)throw Error('KI-Patch ist nicht eindeutig auf den Quelltext anwendbar.');after=after.slice(0,first)+r.replace+after.slice(first+r.search.length);}if(after!==before){if(change.path.endsWith('.json'))JSON.parse(after);updates.push({path:change.path,file:real,before,after,beforeHash:hash(before),afterHash:hash(after)});}}
const entry={id:randomUUID(),requestId,noteId,summary:proposal.summary,createdAt:Date.now(),changes:updates.map(({file,...x})=>x)};if(!updates.length)return {entry,history:status(data),unchanged:true};await atomic(path.join(folder,project.id+'-'+entry.id+'.snapshot.json'),JSON.stringify(entry));await writeSet(updates,'after');const previous={...data,entries:[...data.entries]};data.entries=data.entries.slice(0,data.cursor);data.entries.push(entry);data.cursor=data.entries.length;try{await atomic(file,JSON.stringify(data));}catch(e){await writeSet(updates,'before');Object.assign(data,previous);throw e;}return {entry,history:status(data)};});},
async move(project,direction){return run(async()=>{const {file,data}=await read(project),undo=direction==='undo';if(!['undo','redo'].includes(direction))throw Error('Unbekannte Historienaktion.');if(undo?data.cursor===0:data.cursor===data.entries.length)throw Error(undo?'Nichts zum Zurücknehmen.':'Nichts zum Wiederholen.');const entry=data.entries[undo?data.cursor-1:data.cursor],updates=[];for(const item of entry.changes){const real=await resolve(project,item.path),current=await fs.readFile(real,'utf8'),expected=undo?item.afterHash:item.beforeHash;if(hash(current)!==expected)throw Error('Seit dieser Aktion gab es eine andere Änderung. Sie wird nicht überschrieben.');updates.push({...item,file:real});}await writeSet(updates,undo?'before':'after');data.cursor+=undo?-1:1;try{await atomic(file,JSON.stringify(data));}catch(e){await writeSet(updates,undo?'after':'before');throw e;}return {entry,summary:undo?'Letzte Änderung zurückgenommen.':'Letzte Änderung wiederholt.',history:status(data)};});}};}
export const sourceHash=hash;
