import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {createEditHistory,sourceHash} from './edit-history.mjs';import {runCodexPatch,CODEX_BIN} from './codex-patch-provider.mjs';
const exec=promisify(execFile),fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
export async function frontendSources(project){const root=await fs.realpath(project.root),files=new Map();let total=0;async function walk(dir,depth){for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.name.startsWith('.')||e.isSymbolicLink()||['node_modules','functions','assessment-functions','tools','docs','public','dev-projects','workstreams','games'].includes(e.name))continue;const file=path.join(dir,e.name),rel=path.relative(root,file).replaceAll(path.sep,'/');if(e.isDirectory()){if(depth<2&&['shared','i18n','src','styles','components'].includes(e.name))await walk(file,depth+1);continue;}if(!/\.(html|css|js|mjs|json|svg)$/.test(e.name)||/firebase-config|release\.json|package(-lock)?\.json|\.test\.|test-|firestore|storage.rules/.test(e.name))continue;const stat=await fs.stat(file);if(stat.size>1024*1024)continue;const source=await fs.readFile(file,'utf8');if(source.includes('\0'))continue;total+=stat.size;if(total>6*1024*1024||files.size>=160)fail('Projekt benötigt eine kleinere explizite Live-Dateiauswahl.');files.set(rel,source);}}await walk(root,0);return files;}
function publicJob(j){if(!j)return null;return {id:j.id,projectId:j.projectId,noteId:j.noteId,status:j.status,summary:j.summary,error:j.error,createdAt:j.createdAt,finishedAt:j.finishedAt,elapsedMs:j.finishedAt?j.finishedAt-j.createdAt:Date.now()-j.createdAt,files:j.files||[],governanceReceipt:j.governanceReceipt||null};}
function modelGovernance(note,job,jobs){const phase=note.phase||'live_patch',acceptanceHash=note.acceptance?createHash('sha256').update(note.acceptance).digest('hex'):'';const history=[...jobs.values()].filter(previous=>{if(previous.id===job.id||!previous.governanceReceipt)return false;const r=previous.governanceReceipt;return r.phase===phase&&(note.taskId?r.taskId===note.taskId:previous.noteId===note.id);}).sort((a,b)=>a.createdAt-b.createdAt).map(previous=>{const r=previous.governanceReceipt;return {model:r.requestedModel,effort:r.requestedEffort,acceptance:r.acceptanceHash,risk:r.risk,status:r.status==='completed'&&previous.status==='done'?'completed':r.status==='semantic_failed'?'semantic_failed':'unknown'};});const failure=note.failureKind?{kind:note.failureKind,evidence:note.failureEvidence,acceptance:acceptanceHash}:undefined;return {taskId:note.taskId??null,noteId:note.id,requestId:job.requestId,phase,risk:note.risk||'routine',reason:note.modelReason,authorization:note.modelAuthorization,model:note.model||undefined,effort:note.effort||undefined,lowEvidence:note.lowEvidence,acceptance:acceptanceHash||undefined,acceptanceHash:acceptanceHash||undefined,failure,securityStepComplete:note.securityStepComplete,history};}
export function createLiveEditor({dataDir,getProjects,taskStore,onEvent=()=>{},provider=runCodexPatch}){
 const folder=path.join(dataDir,'live-jobs'),history=createEditHistory(path.join(dataDir,'live-history')),jobs=new Map(),active=new Map(),queues=new Map();let initialized;
 async function init(){if(initialized)return initialized;initialized=(async()=>{await fs.mkdir(folder,{recursive:true,mode:0o700});for(const name of await fs.readdir(folder)){if(!/^[0-9a-f-]{36}\.json$/i.test(name))continue;const j=JSON.parse(await fs.readFile(path.join(folder,name),'utf8'));if(['queued','working'].includes(j.status)){j.status='error';j.error='Server neu gestartet. Dieser unterbrochene Auftrag wird nicht blind wiederholt.';}jobs.set(j.id,j);}})();return initialized;}
 const project=id=>{const p=getProjects().find(p=>p.id===id&&p.kind!=='native');if(!p)fail('Dieses Projekt ist noch nicht für Live-Bearbeitung angebunden.');return p;};
 async function persist(j){const file=path.join(folder,j.id+'.json'),tmp=file+'.tmp';await fs.writeFile(tmp,JSON.stringify(j),{mode:0o600});await fs.rename(tmp,file);onEvent({type:'live-job',projectId:j.projectId,job:publicJob(j)});}
 async function findNote(id){let cursor='';do{const page=await taskStore.list({cursor});const note=page.tasks.find(n=>n.id===id);if(note)return note;cursor=page.nextCursor||'';}while(cursor);fail('Hinweis nicht gefunden.',404);}
 async function run(j,p,note,controller){try{j.status='working';j.summary='KI bearbeitet deinen Auftrag …';await persist(j);if(note.screenshotUrl){const capture=await fs.readFile(path.join(taskStore.captureDir,note.id+'.png'));note={...note,screenshot:{mimeType:'image/png',base64:capture.toString('base64')}};}const sources=await frontendSources(p);if(!sources.size)fail('Keine bearbeitbaren Frontend-Dateien registriert.');const proposal=await provider({sources,note,project:p,signal:controller.signal,governance:modelGovernance(note,j,jobs),onGovernanceReceipt:async receipt=>{j.governanceReceipt=receipt;await persist(j);},onProgress:text=>{j.summary=text;onEvent({type:'live-job',projectId:p.id,job:publicJob(j)});}});if(proposal.governanceReceipt)j.governanceReceipt=proposal.governanceReceipt;if(controller.signal.aborted)throw Error('Auftrag abgebrochen.');const allowed=new Map([...sources].map(([name,source])=>[name,sourceHash(source)]));
 // Syntax-check proposed JavaScript as data. Never execute generated code in the server.
 for(const change of proposal.changes||[]){if(!allowed.has(change.path))continue;if(!/\.(js|mjs)$/.test(change.path))continue;let candidate=sources.get(change.path);for(const r of change.replacements||[]){if(typeof r.search==='string'&&typeof r.replace==='string')candidate=candidate.replace(r.search,r.replace);}const file=path.join(folder,j.id+'-syntax.mjs');try{await fs.writeFile(file,candidate,{mode:0o600});await exec(process.execPath,['--check',file],{timeout:6000});}catch{throw Error('Der erzeugte JavaScript-Patch ist syntaktisch ungültig. Vorhandener Code bleibt erhalten.');}finally{await fs.rm(file,{force:true});}}
 const result=await history.apply(p,proposal,{allowedFiles:allowed,noteId:note.id,requestId:j.requestId});j.status='done';j.summary=proposal.summary;j.files=result.entry.changes.map(c=>c.path);j.finishedAt=Date.now();await taskStore.update(note.id,{status:'preview',error:''});onEvent({type:'tasks',projectId:p.id});await persist(j);
 }catch(e){j.status='error';j.error=String(e.message).slice(0,1000);j.summary='Auftrag konnte nicht angewendet werden.';j.finishedAt=Date.now();await taskStore.update(note.id,{status:'error',error:j.error}).catch(()=>{});onEvent({type:'tasks',projectId:p.id});await persist(j);}finally{active.delete(p.id);drain(p.id);}}
 function drain(id){if(active.has(id))return;const next=queues.get(id)?.shift();if(!next)return;active.set(id,next.controller);void run(next.j,next.p,next.note,next.controller);}
 return {async submit({noteId,requestId}){await init();if(typeof requestId!=='string'||! /^[a-zA-Z0-9_-]{8,100}$/.test(requestId))fail('Live-Auftrags-ID ungültig.');const existing=[...jobs.values()].find(j=>j.requestId===requestId);if(existing){if(existing.noteId!==noteId)fail('Diese Live-Auftrags-ID gehört zu einem anderen Hinweis.',409);return publicJob(existing);}const note=await findNote(noteId),p=project(note.projectId);if((queues.get(p.id)?.length||0)>=5)fail('Bitte die wartenden Aufträge zuerst abarbeiten lassen.',409);const controller=new AbortController();const j={id:randomUUID(),requestId,noteId:note.id,projectId:p.id,status:'queued',createdAt:Date.now(),summary:active.has(p.id)?'Wartet auf den vorherigen Auftrag …':'Beginne mit deinem Auftrag …',error:'',files:[]};jobs.set(j.id,j);try{await taskStore.update(note.id,{status:'working',error:''});onEvent({type:'tasks',projectId:p.id});await persist(j);}catch(e){jobs.delete(j.id);throw e;}if(!queues.has(p.id))queues.set(p.id,[]);queues.get(p.id).push({j,p,note,controller});drain(p.id);return publicJob(j);},
 async state(projectId){await init();const p=project(projectId);let available=true;try{await fs.access(CODEX_BIN);}catch{available=false;}const recent=[...jobs.values()].filter(j=>j.projectId===projectId).sort((a,b)=>b.createdAt-a.createdAt);return {available,backend:'codex-cli',history:await history.state(p),activeJob:publicJob(recent.find(j=>['queued','working'].includes(j.status))),lastJob:publicJob(recent[0])};},
 async job(id){await init();const j=jobs.get(id);if(!j)fail('Live-Auftrag nicht gefunden.',404);return publicJob(j);},
 async move(projectId,direction){await init();const p=project(projectId);if(active.has(p.id))fail('KI bearbeitet dieses Projekt noch.',409);const result=await history.move(p,direction);if(result.entry.noteId){await taskStore.update(result.entry.noteId,{status:direction==='undo'?'waiting':'preview',error:''}).catch(()=>{});onEvent({type:'tasks',projectId});}onEvent({type:'live-history',projectId,summary:result.summary,history:result.history});return {summary:result.summary,history:result.history};},
 stop(){for(const q of queues.values())for(const item of q){item.j.status='error';item.j.error='Server wurde angehalten.';void persist(item.j);}queues.clear();for(const c of active.values())c.abort();}};
}
