// Isolated Workbench HTTP entry point; the shared review-preview server remains unchanged.
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';
import {createLiveEditor} from './live-editor.mjs';
import {appendWorkbenchAppBridge} from './app-bridge-source.mjs';
import {openReviewStore} from '../review-preview/data-store.mjs';import {createVisualTaskStore} from '../review-preview/visual-tasks.mjs';import {sourceFingerprint,testResult} from '../review-preview/fingerprint.mjs';import {loadProjects,defaultProjects,publicProjects,allowedOrigin} from './project-registry.mjs';import {scanProjects,changedProjects} from './watch.mjs';
const require=createRequire(import.meta.url);const {createReviewService}=require('../../functions/lib/review-mode.js');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),toolRoot=path.join(root,'tools/dev-workbench'),port=Number(process.env.REVIEW_PORT||8772),dataMode=process.env.REVIEW_DATA_MODE==='staging'?'staging':'fixtures',folder=process.env.REVIEW_DATA_DIR?path.resolve(process.env.REVIEW_DATA_DIR):path.join(root,'.review-local');await fs.mkdir(folder,{recursive:true,mode:0o700});await fs.chmod(folder,0o700);
const dataFile=path.join(folder,'notes.json'),registryFile=path.join(folder,'projects.json'),store=await openReviewStore(dataFile),visualTasks=createVisualTaskStore(path.join(folder,'visual-tasks.json')),service=createReviewService({store,projectId:'hausaufgabe-staging'});let projects=await loadProjects(registryFile,defaultProjects(root)),snapshot=await scanProjects(projects),build=await sourceFingerprint(root),clients=new Set(),running=false,scanning=false;
const liveEditor=createLiveEditor({dataDir:folder,getProjects:()=>projects,taskStore:visualTasks,onEvent:event=>publish(event)});
function publish(event){for(const c of clients)c.write(`data: ${JSON.stringify(event)}\n\n`);}
const timer=setInterval(async()=>{if(scanning)return;scanning=true;try{projects=await loadProjects(registryFile,defaultProjects(root));const next=await scanProjects(projects),event=changedProjects(snapshot,next,projects);snapshot=next;if(event){build=event.build;publish(event);}}catch(e){console.error('Workbench watcher: '+e.message);}finally{scanning=false;}},1200);
const heartbeat=setInterval(()=>{for(const c of clients)c.write(': heartbeat\n\n');},25000);
function json(response,status,value){response.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});response.end(JSON.stringify(value));}
async function body(request){const chunks=[];let bytes=0;for await(const c of request){bytes+=c.length;if(bytes>3*1024*1024)throw Object.assign(Error('Anfrage ist zu groß.'),{status:413});chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw Object.assign(Error('Anfrage enthält kein gültiges JSON.'),{status:400});}}
const baseCsp="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self'; font-src 'self' data:; object-src 'none'; base-uri 'self'";
const stagingCsp="default-src 'self'; script-src 'self' 'unsafe-inline' https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://firebasestorage.googleapis.com https://storage.googleapis.com; media-src 'self' data: blob: https://firebasestorage.googleapis.com https://storage.googleapis.com; connect-src 'self' https://*.googleapis.com https://*.cloudfunctions.net https://*.firebaseio.com wss://*.firebaseio.com; frame-src 'self' https://hausaufgabe-staging.firebaseapp.com https://accounts.google.com; font-src 'self' data:; object-src 'none'; base-uri 'self'";
const server=http.createServer(async(request,response)=>{try{
 if(!['127.0.0.1:'+port,'localhost:'+port].includes(request.headers.host)){json(response,403,{message:'Localhost only'});return;}
 const url=new URL(request.url,'http://127.0.0.1:'+port),origin=request.headers.origin;
 if(origin&&allowedOrigin(origin,port,projects)){response.setHeader('Access-Control-Allow-Origin',origin);response.setHeader('Vary','Origin');}
 if(request.method==='OPTIONS'){if(!origin||!allowedOrigin(origin,port,projects)){json(response,403,{message:'Origin nicht erlaubt.'});return;}response.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, PATCH','Access-Control-Allow-Headers':'Content-Type'});response.end();return;}
 if(['POST','PATCH'].includes(request.method)){
  if(!origin||!allowedOrigin(origin,port,projects)){json(response,403,{message:'Same-origin request required'});return;}
  const payload=await body(request);
  if(request.method==='POST'&&url.pathname==='/__dev/live/jobs'){json(response,202,{job:await liveEditor.submit(payload)});return;}
  const historyAction=url.pathname.match(/^\/__dev\/live\/(undo|redo)$/);if(request.method==='POST'&&historyAction){json(response,200,await liveEditor.move(payload.projectId,historyAction[1]));return;}
  if(request.method==='POST'&&url.pathname==='/__review/tasks'){if(!projects.some(p=>p.id===(payload.projectId||'gradecrew'))){json(response,400,{message:'Projekt ist nicht registriert.'});return;}const task=await visualTasks.create(payload);publish({type:'tasks',projectId:task.projectId});json(response,201,{task,receipt:{id:task.id,clientRequestId:task.clientRequestId,stored:true}});return;}
  const match=url.pathname.match(/^\/__review\/tasks\/([0-9a-f-]{36})$/i);if(request.method==='PATCH'&&match){const task=await visualTasks.update(match[1],payload);if(!task){json(response,404,{message:'Hinweis nicht gefunden.'});return;}publish({type:'tasks',projectId:task.projectId});json(response,200,{task});return;}
  if(url.pathname==='/__review/api'){json(response,200,await service.execute({uid:'local-admin',data:payload}));return;}
  if(request.method==='POST'&&url.pathname==='/__review/run'){
   if(payload.checkId!=='GC-REVIEW-AUTO'){json(response,400,{message:'Unknown check'});return;}if(running){json(response,409,{message:'Eine Prüfung läuft bereits.'});return;}running=true;const sourceBuild=await sourceFingerprint(root),runId=randomUUID();let output='';const child=spawn(process.execPath,['--experimental-vm-modules','--test','tools/ui/review-scenes.test.cjs','functions/test/review-mode.test.js','tools/ui/review-mode.test.cjs','tools/review-preview/server.test.mjs','tools/dev-workbench/store.test.mjs','tools/dev-workbench/browser-toolbar.test.mjs','tools/dev-workbench/watch.test.mjs'],{cwd:root,env:{...process.env},stdio:['ignore','pipe','pipe']});child.stdout.on('data',x=>output=(output+x).slice(-30000));child.stderr.on('data',x=>output=(output+x).slice(-30000));const timeout=setTimeout(()=>child.kill('SIGTERM'),90000),exit=await new Promise(resolve=>{child.once('error',()=>resolve(-1));child.once('close',code=>resolve(code??-1));});clearTimeout(timeout);running=false;const afterBuild=await sourceFingerprint(root),result={id:runId,checkId:payload.checkId,build:sourceBuild,result:testResult(exit,sourceBuild,afterBuild),method:'automated',evidence:`Lokale Regressionen · Lauf ${runId} · Exit ${exit}`,authorId:'local-admin',updatedAt:Date.now(),summary:output.slice(-3500)};await store.transaction(tx=>tx.set(`reviewChecks/${runId}`,result));await fs.writeFile(path.join(folder,runId+'.log'),output,{mode:0o600});json(response,200,result);return;
  }
  json(response,404,{message:'Unknown operation'});return;
 }
 if(request.method!=='GET'){json(response,405,{});return;}
 if(url.pathname==='/__dev/live/state'){json(response,200,await liveEditor.state(url.searchParams.get('projectId')||'gradecrew'));return;}
 const liveJob=url.pathname.match(/^\/__dev\/live\/jobs\/([0-9a-f-]{36})$/i);if(liveJob){json(response,200,{job:await liveEditor.job(liveJob[1])});return;}
 if(url.pathname==='/__dev/handbook'){const bytes=await fs.readFile(path.join(root,'output/pdf/GradeCrew-Entwicklungswerkzeug-Auftrag-220-Seiten.pdf'));response.writeHead(200,{'Content-Type':'application/pdf','Cache-Control':'no-store'});response.end(bytes);return;}
 if(url.pathname==='/__dev/projects'){json(response,200,{projects:publicProjects(projects).map(p=>p.id==='gradecrew'?{...p,dataMode:dataMode==='staging'?'staging':'fixtures'}:p),dataMode,localOnly:true});return;}
 if(url.pathname==='/__review/tasks'){if(origin&&!allowedOrigin(origin,port,projects)){json(response,403,{message:'Origin nicht erlaubt.'});return;}json(response,200,await visualTasks.list({cursor:url.searchParams.get('cursor')||'',limit:Number(url.searchParams.get('limit')||100),projectId:url.searchParams.get('projectId')||''}));return;}
 if(url.pathname==='/__review/events'){if(origin&&!allowedOrigin(origin,port,projects)){json(response,403,{message:'Origin nicht erlaubt.'});return;}response.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});response.write(': connected\n\n');clients.add(response);request.on('close',()=>clients.delete(response));return;}
 const capture=url.pathname.match(/^\/__review\/captures\/([0-9a-f-]{36})\.png$/i);if(capture){const data=await fs.readFile(path.join(visualTasks.captureDir,capture[1]+'.png'));response.writeHead(200,{'Content-Type':'image/png','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});response.end(data);return;}
 if(url.pathname==='/release.json'){json(response,200,{commit:build,version:'local-development',project:dataMode==='staging'?'hausaufgabe-staging':'isolated-fixtures',localUI:true});return;}
 if(url.pathname==='/firebase-config.js'){response.writeHead(200,{'Content-Type':'text/javascript','Cache-Control':'no-store'});response.end(dataMode==='staging'?await fs.readFile(path.join(root,'firebase-config.staging.js'),'utf8'):'export const firebaseConfig={projectId:"local-review"}; export const appEnvironment="local-review";');return;}
 let project=projects.find(p=>p.id==='gradecrew'),staticRoot=root,name=decodeURIComponent(url.pathname).replace(/^\//,'')||'index.html',isTool=false;
 if(url.pathname==='/__dev'||url.pathname==='/__dev/'){staticRoot=toolRoot;name='hub.html';isTool=true;}
 else if(url.pathname.startsWith('/__dev/assets/')){staticRoot=toolRoot;name=decodeURIComponent(url.pathname.slice('/__dev/assets/'.length));isTool=true;}
 else if(url.pathname.startsWith('/__project/')){const m=url.pathname.match(/^\/__project\/([a-z0-9-]+)(?:\/(.*))?$/);project=m&&projects.find(p=>p.id===m[1]&&p.kind!=='native');if(!project){json(response,404,{message:'Webprojekt nicht gefunden.'});return;}staticRoot=project.root;name=decodeURIComponent(m[2]||'')||project.entry||'index.html';if(!m[2]&& !url.pathname.endsWith('/')){response.writeHead(302,{Location:url.pathname+'/'});response.end();return;}}
 if(name.includes('..')||name.split('/').some(p=>p.startsWith('.'))||name==='functions/main.js'||(name.startsWith('functions/')&&name!=='functions/lib/review-checks.json')||! /\.(html|js|mjs|css|svg|webp|png|jpg|jpeg|json|wav|mp3|woff2|md)$/.test(name)){json(response,403,{});return;}
 const realRoot=await fs.realpath(staticRoot),real=await fs.realpath(path.join(staticRoot,name));if(!real.startsWith(realRoot+path.sep)||real.includes('node_modules')){json(response,403,{});return;}let content=await fs.readFile(real);const ext=path.extname(name),types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.md':'text/plain'};
 const homepage=!isTool&&project?.id==='gradecrew';
 if(homepage&&dataMode!=='staging'&&['.js','.mjs','.html'].includes(ext))content=content.toString().replace(/https:\/\/www\.gstatic\.com\/firebasejs\/[\d.]+\/firebase-[\w-]+\.js/g,'/tools/review-preview/firebase-fixture.mjs');
 if(homepage&&ext==='.js')content=Buffer.from(appendWorkbenchAppBridge(content.toString(),{homepage,dataMode,name}));
 if(ext==='.html'&&!isTool){const config={projectId:project.id,dataMode:homepage?(dataMode==='staging'?'staging':'fixtures'):'local',apiBase:'/__review/tasks'};const scripts=homepage?['/tools/review-preview/review-preview-client.mjs','/__dev/assets/client.mjs']:['/__dev/assets/client.mjs'];content=content.toString().replace('</head>',`<script type="application/json" id="gc-dev-config">${JSON.stringify(config).replace(/</g,'\\u003c')}</script>${scripts.map(src=>`<script type="module" src="${src}"></script>`).join('')}</head>`);}
 response.writeHead(200,{'Content-Type':(types[ext]||'application/octet-stream')+(['.html','.js','.mjs','.css','.json','.md'].includes(ext)?'; charset=utf-8':''),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':homepage&&dataMode==='staging'?stagingCsp:baseCsp});response.end(content);
 }catch(error){json(response,error.status||(error.code==='ENOENT'?404:400),{message:error.message});}});
server.on('error',e=>{console.error('Workbench start failed: '+e.message);clearInterval(timer);clearInterval(heartbeat);process.exitCode=1;});server.listen(port,'127.0.0.1',()=>{void fs.writeFile(path.join(folder,'server.pid'),String(process.pid),{mode:0o600});console.log(`GradeCrew Entwicklungszentrale: http://127.0.0.1:${port}/__dev · ${dataMode==='staging'?'STAGING-DATEN: Teständerungen speichern online':'lokale Beispieldaten'} · ${projects.length} Projekte · Notizen ${path.join(folder,'visual-tasks.json')}`);});
function stop(){liveEditor.stop();clearInterval(timer);clearInterval(heartbeat);for(const c of clients)c.end();server.close();}process.on('SIGTERM',stop);process.on('SIGINT',stop);
