import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
export const STATUSES=['waiting','working','preview','error','rejected','accepted'];
const CATEGORIES=['bug','design','text','function','idea'],PRIORITIES=['low','normal','high'],MAX_BYTES=4*1024*1024,MAX_TASKS=1000;
const fail=message=>{throw Object.assign(new Error(message),{status:400});};
const str=(v,max,label,required=false)=>{if(v==null&&!required)return '';if(typeof v!=='string'||v.trim().length>max||required&&!v.trim())fail(label+' ist ungültig.');return v.trim();};
const id=v=>{const x=str(v,64,'Projekt');if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(x))fail('Projekt ist ungültig.');return x;};
const number=(v,max)=>{if(!Number.isFinite(v)||v<0||v>max)fail('Bereich liegt außerhalb des Fensters.');return Math.round(v);};
function region(v){if(v==null)return null;if(typeof v!=='object'||Array.isArray(v))fail('Bereich ist ungültig.');const w=number(v.viewportWidth,10000),h=number(v.viewportHeight,10000),x=number(v.x,w),y=number(v.y,h),width=number(v.width,w),height=number(v.height,h);if(!w||!h||x+width>w+1||y+height>h+1)fail('Bereich liegt außerhalb des Fensters.');return {x,y,width,height,viewportWidth:w,viewportHeight:h};}
function screenshot(v){if(v==null)return null;if(v.mimeType!=='image/png'||typeof v.base64!=='string'||v.base64.length>2800000||!/^[A-Za-z0-9+/]*={0,2}$/.test(v.base64))fail('Bild muss ein PNG unter 2 MB sein.');const bytes=Buffer.from(v.base64,'base64');if(bytes.length>2*1024*1024||bytes.length<33||!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||bytes.toString('base64')!==v.base64||bytes.toString('ascii',12,16)!=='IHDR')fail('PNG ist ungültig.');const w=bytes.readUInt32BE(16),h=bytes.readUInt32BE(20);if(!w||!h||w>4096||h>4096||w*h>16000000)fail('PNG-Abmessungen sind zu groß.');return bytes;}
function normalize(v){if(!v||typeof v!=='object'||Array.isArray(v))fail('Hinweis ist ungültig.');const allowed=['text','category','priority','url','view','scene','target','region','viewport','projectId','source','clientRequestId','context','screenshot','taskId','phase','risk','model','effort','modelReason','modelAuthorization','lowEvidence','acceptance','failureKind','failureEvidence','securityStepComplete'];if(Object.keys(v).some(k=>!allowed.includes(k)))fail('Hinweis enthält nicht erlaubte Felder.');const category=v.category||'idea',priority=v.priority||'normal',source=v.source||'web';if(!CATEGORIES.includes(category)||!PRIORITIES.includes(priority)||!['web','canvas','native'].includes(source))fail('Hinweiskategorie ist ungültig.');let url='';if(v.url){let u;try{u=new URL(str(v.url,500,'URL'),'http://localhost');}catch{fail('URL ist ungültig.');}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)fail('URL ist ungültig.');url=u.pathname+u.search;}
const requestId=str(v.clientRequestId,100,'Client-ID');if(requestId&&!/^[a-zA-Z0-9_-]{8,100}$/.test(requestId))fail('Client-ID ist ungültig.');
let target=null;if(v.target){target={tag:str(v.target.tag,30,'Elementtyp'),selector:str(v.target.selector,500,'Elementpfad'),classes:str(v.target.classes,300,'Elementklassen'),text:str(v.target.text,160,'Elementtext'),rect:region(v.target.rect)};}
let viewport=null;if(v.viewport){viewport={width:number(v.viewport.width,10000),height:number(v.viewport.height,10000),devicePixelRatio:v.viewport.devicePixelRatio??1};if(viewport.devicePixelRatio<.5||viewport.devicePixelRatio>5)fail('Skalierung ist ungültig.');}
let context=null;if(v.context){if(typeof v.context!=='object'||Array.isArray(v.context)||Object.keys(v.context).some(k=>!['app','entity','checkpoint','scrollX','scrollY'].includes(k)))fail('Kontext ist ungültig.');context={app:str(v.context.app,120,'App'),entity:str(v.context.entity,160,'Spielobjekt'),checkpoint:str(v.context.checkpoint,4000,'Entwickler-Prüfpunkt'),scrollX:number(v.context.scrollX||0,100000),scrollY:number(v.context.scrollY||0,100000)};}
const taskId=str(v.taskId,100,'Task-ID');if(taskId&&!/^GC-[A-Z0-9]+(?:-[A-Z0-9]+)*$/.test(taskId))fail('Task-ID ist ungültig.');const phase=str(v.phase,40,'Phase');if(phase&&!['analysis','implementation','review','verification','handoff','live_patch'].includes(phase))fail('Phase ist ungültig.');const risk=v.risk||'';if(risk&&!['routine','complexity','authorized_high'].includes(risk))fail('Risikoeinstufung ist ungültig.');const model=v.model||'';if(model&&!['gpt-6-luna','gpt-6.1-sol'].includes(model))fail('Modellauswahl ist ungültig.');const effort=v.effort||'';if(effort&&!['low','medium','high'].includes(effort))fail('Denkaufwand ist ungültig.');const failureKind=v.failureKind||'';if(failureKind&&!['semantic','auth','dns','quota','unknown','infrastructure'].includes(failureKind))fail('Fehlerkategorie ist ungültig.');const securityStepComplete=v.securityStepComplete??false;if(typeof securityStepComplete!=='boolean')fail('Security-Schrittstatus ist ungültig.');const modelReason=str(v.modelReason,500,'Modellgrund'),modelAuthorization=str(v.modelAuthorization,200,'Modellfreigabe'),lowEvidence=str(v.lowEvidence,500,'Niedrigaufwand-Beleg'),acceptance=str(v.acceptance,1000,'Abnahmekriterien'),failureEvidence=str(v.failureEvidence,500,'Fehlerbeleg');
const bytes=screenshot(v.screenshot);const data={text:str(v.text,3000,'Hinweis',true),category,priority,url,view:str(v.view,100,'Ansicht'),scene:str(v.scene,40,'Szene'),projectId:id(v.projectId||'gradecrew'),source,clientRequestId:requestId,target,region:region(v.region),viewport,context,taskId:taskId||null,phase:phase||null,risk:risk||null,model:model||null,effort:effort||null,modelReason,modelAuthorization,lowEvidence,acceptance,failureKind:failureKind||null,failureEvidence,securityStepComplete};return {data,bytes,digest:createHash('sha256').update(JSON.stringify(data)).update(bytes||'').digest('hex')};}
export function createTaskStore(file){let serial=Promise.resolve();const captureDir=path.join(path.dirname(file),'captures');const transaction=operation=>{const pending=serial.catch(()=>{}).then(async()=>{let tasks=[];try{const b=await fs.readFile(file);if(b.length>MAX_BYTES)throw Error('Hinweisdatei ist zu groß.');tasks=JSON.parse(b);if(!Array.isArray(tasks)||tasks.length>MAX_TASKS||tasks.some(t=>!t||typeof t.id!=='string'||typeof t.text!=='string'||!STATUSES.includes(t.status)))throw Error('Hinweisdatei ist beschädigt.');}catch(e){if(e.code!=='ENOENT')throw e;}return operation(tasks);});serial=pending;return pending;};
async function persist(tasks){const content=JSON.stringify(tasks);if(Buffer.byteLength(content)>MAX_BYTES)throw Error('Hinweisdatei ist voll. Bitte gesicherte Hinweise archivieren.');await fs.mkdir(path.dirname(file),{recursive:true,mode:0o700});const tmp=file+'.'+randomUUID()+'.tmp';try{await fs.writeFile(tmp,content,{mode:0o600,flag:'wx'});await fs.rename(tmp,file);await fs.chmod(file,0o600);}finally{await fs.rm(tmp,{force:true}).catch(()=>{});}}
return {list({cursor='',limit=100,projectId=''}={}){return transaction(tasks=>{const size=Math.max(1,Math.min(100,Number.isInteger(limit)?limit:100));const ordered=tasks.filter(t=>!projectId||(t.projectId||'gradecrew')===projectId).sort((a,b)=>a.createdAt-b.createdAt||a.id.localeCompare(b.id));const start=cursor?ordered.findIndex(t=>t.id===cursor)+1:0;const page=ordered.slice(start,start+size).map(t=>({...t,projectId:t.projectId||'gradecrew',source:t.source||'web'}));return {tasks:page,nextCursor:start+size<ordered.length?page.at(-1).id:null,total:ordered.length};});},
async create(input){const {data,bytes,digest}=normalize(input);return transaction(async tasks=>{if(data.clientRequestId){const existing=tasks.find(t=>t.clientRequestId===data.clientRequestId&&t.projectId===data.projectId);if(existing){if(existing.payloadDigest!==digest)throw Object.assign(Error('Diese Client-ID wurde bereits für einen abweichenden Hinweis verwendet.'),{status:409});return {...existing};}}if(tasks.length>=MAX_TASKS)throw Error('Hinweisarchiv ist voll.');const task={...data,id:randomUUID(),createdAt:Date.now(),updatedAt:Date.now(),status:'waiting',error:'',payloadDigest:digest,screenshotUrl:''};let captureFile='';try{if(bytes){await fs.mkdir(captureDir,{recursive:true,mode:0o700});captureFile=path.join(captureDir,task.id+'.png');await fs.writeFile(captureFile,bytes,{mode:0o600,flag:'wx'});task.screenshotUrl='/__review/captures/'+task.id+'.png';}tasks.push(task);await persist(tasks);return {...task};}catch(e){if(captureFile)await fs.rm(captureFile,{force:true}).catch(()=>{});throw e;}});},
async update(taskId,patch){if(!/^[0-9a-f-]{36}$/i.test(taskId)||!patch||Object.keys(patch).some(k=>!['status','error'].includes(k))||!STATUSES.includes(patch.status))fail('Statusänderung ist ungültig.');return transaction(async tasks=>{const task=tasks.find(t=>t.id===taskId);if(!task)return null;task.status=patch.status;task.error=str(patch.error,1000,'Fehlertext');task.updatedAt=Date.now();await persist(tasks);return {...task};});},captureDir};}
