#include "IslandWorld.h"
#include "Camera/CameraComponent.h"
#include "Engine/Canvas.h"
#include "Engine/Engine.h"
#include "Engine/Font.h"
#include "CanvasItem.h"
#include "Kismet/GameplayStatics.h"
void AIslandHUD::Panel(float X,float Y,float W,float H,FLinearColor C){DrawRect(C,X,Y,W,H);}
void AIslandHUD::Text(const FString& S,float X,float Y,float Size,FLinearColor C){auto* F=GEngine->GetMediumFont();FCanvasTextItem T(FVector2D(X,Y),FText::FromString(S),F,C);T.Scale=FVector2D(Size/FMath::Max(1,F->GetMaxCharHeight()));T.EnableShadow(FLinearColor(0,0,0,.35));Canvas->DrawItem(T);}
void AIslandHUD::Wrap(const FString& S,float X,float Y,float Width,float Size){FString Line;float CY=Y;TArray<FString> Words;S.ParseIntoArrayWS(Words);for(const auto& Word:Words){FString Next=Line.IsEmpty()?Word:Line+TEXT(" ")+Word;float TW,TH;GetTextSize(Next,TW,TH,GEngine->GetMediumFont(),Size/FMath::Max(1,GEngine->GetMediumFont()->GetMaxCharHeight()));if(TW>Width&&!Line.IsEmpty()){Text(Line,X,CY,Size,FLinearColor(.92,.93,.84));CY+=Size*1.55f;Line=Word;}else Line=Next;}if(!Line.IsEmpty())Text(Line,X,CY,Size,FLinearColor(.92,.93,.84));}
void AIslandHUD::Button(const FString& S,float X,float Y,float W,float H,int Action){Panel(X,Y,W,H,FLinearColor(.17,.27,.23,.97));Text(S,X+20*Scale,Y+H*.25f,20*Scale,FLinearColor(.94,.93,.8));Buttons.Add({FBox2D(FVector2D(X,Y),FVector2D(X+W,Y+H)),Action});}
bool AIslandHUD::ClickAt(FVector2D P){auto* G=Cast<AIslandGameMode>(UGameplayStatics::GetGameMode(this));if(!G)return false;for(const auto& B:Buttons)if(B.Bounds.IsInside(P)){switch(B.Action){case 800:G->Focus=-1;break;case 801:G->SelectFocused();break;case 900:G->Paused=false;break;case 901:if(auto* Char=G->Player())Char->Camera->SetFieldOfView(Char->Camera->FieldOfView<80?85:75);return true;case 910:if(G->Near>=0)G->Interact(G->Near);return true;default:return false;}if(auto* C=Cast<AIslandController>(GetOwningPlayerController())){C->CancelInput();C->UpdateMode();}return true;}return false;}
void AIslandHUD::DrawHUD(){Super::DrawHUD();if(!Canvas)return;auto* G=Cast<AIslandGameMode>(UGameplayStatics::GetGameMode(this));if(!G)return;Buttons.Reset();float W=Canvas->SizeX,H=Canvas->SizeY;Scale=FMath::Clamp(FMath::Min(W/1440.f,H/900.f),.65f,2.f);float S=Scale;
 if(!G->Paused&&G->Focus<0){
  FString Goal,Help;
  if(!G->State.intro){Goal=FString::Printf(TEXT("1 · Finde zwei Verben · %d von 2 gewählt"),Island::CountBits(G->State.introMask));Help=TEXT("Was tut jemand? Klicke ein Wort oder drücke E. Der ganze Stein wird blau. Erneut klicken nimmt es zurück.");}
  else if(!G->State.verbs){Goal=FString::Printf(TEXT("2 · Verbweg · Reihe %d von 3"),Island::PathPromptRow(G->State));Help=G->State.pathFailed?TEXT("Der orange Stein passt noch nicht. Links steht Schritt zurück. Danach wähle in dieser Reihe ein anderes Wort."):!G->State.pathActive?TEXT("Beginne vorne bei Reihe 1. Klicke ein Verb oder drücke E. Ein Verb sagt, was jemand tut. Damit startest du den Weg."):TEXT("Gehe von vorne nach hinten. Wähle in jeder Reihe ein Verb: Was tut jemand? Klicke, drücke E oder stehe kurz auf dem Wort.");}
  else if(!G->State.sentence){Goal=TEXT("3 · Baue einen Satz aus vier Teilen");Help=TEXT("Öffne Satz beginnen. Klicke alle vier Teile in deiner Reihenfolge. Das Verb „öffnet“ gehört auf Platz 2.");}
  else if(!G->State.water){Goal=TEXT("4 · Fülle den Eimer bis 3/10 Liter");Help=TEXT("Nimm den 1-Liter-Eimer. Am Brunnen füllst du je 100 ml. Stelle 300 ml auf die Platte vor dem Tor.");}
  else if(!G->State.fractions){Goal=TEXT("5 · Finde einen Wasserweg für 1 Liter");Help=TEXT("Öffne die Bruchleitung. Verbinde Start und Ziel über einen Ast. Die drei Brüche zusammen müssen 1 ergeben.");}
  else if(!G->State.coast){Goal=TEXT("6 · Finde Teile für das Felsfenster");Help=G->State.coastReady?TEXT("Die Menge passt! Gehe die Treppe hoch. Am runden Standplatz hilft Blickhilfe. Richte die Formen aus und drücke E."):TEXT("Suche vier Reliefs am unteren Küstenweg. Öffne das Fundbuch. Wähle drei Anteile, die zusammen 1 ergeben.");}
  else {Goal=TEXT("Zum Turm!");Help=TEXT("Vier Inselrätsel sind gelöst. Öffne den Turm und verbinde die vier Signale.");}
  Panel(28*S,26*S,680*S,156*S,FLinearColor(.035,.10,.085,.90));Text(Goal,44*S,39*S,22*S,FLinearColor(.96,.96,.86));Wrap(Help,44*S,76*S,642*S,19*S);Text(TEXT("WASD bewegen · Maus schauen · E Aktion · Esc zurück"),44*S,153*S,15*S,FLinearColor(.78,.88,.83));
 }
 if(G->State.carrying){Panel(W-310*S,28*S,280*S,74*S,FLinearColor(.08,.17,.16,.85));Text(TEXT("Mess-Eimer · 1 L"),W-292*S,39*S,18*S,FLinearColor(.94,.93,.82));Text(FString::Printf(TEXT("%d/10 Liter  ·  %d ml"),G->State.tenths,G->State.tenths*100),W-292*S,68*S,20*S,FLinearColor(.66,.92,.88));}
 if(G->State.carrying&&!G->Paused&&G->Focus<0){float GX=W-260*S,GY=140*S;Panel(GX-20*S,GY-20*S,230*S,260*S,FLinearColor(.08,.17,.16,.88));Text(TEXT("Kapazität: 1 Liter"),GX,GY-5*S,16*S,FLinearColor(.94,.94,.84));for(int I=1;I<=10;++I){float Y=GY+35*S+(10-I)*19*S;Panel(GX,Y,35*S,14*S,I<=G->State.tenths?FLinearColor(.3,.7,.8):FLinearColor(.24,.32,.3));Text(FString::Printf(TEXT("%d/10"),I),GX+50*S,Y-1*S,14*S,FLinearColor(.94,.94,.84));}}
 if(G->Focus<0&&!G->Paused){DrawRect(FLinearColor(.96,.94,.8,.9),W*.5f-2,H*.5f-2,4,4);if(const auto* T=G->Target(G->Near)){bool Word=G->Near>=100&&G->Near<=208;Panel(W*.5f-340*S,H-128*S,680*S,Word?84*S:54*S,FLinearColor(.08,.15,.12,.90));Text((Word?TEXT("Klick / E · "):TEXT("E · "))+T->Label,W*.5f-322*S,H-112*S,19*S,FLinearColor(.97,.95,.82));if(Word)Text(T->Context,W*.5f-322*S,H-79*S,17*S,FLinearColor(.86,.92,.85));}}
 if(G->MessageTime>0&&G->Focus<0&&!G->Paused){Panel(W*.5f-370*S,H-246*S,740*S,100*S,FLinearColor(.08,.16,.13,.86));Wrap(G->Feedback,W*.5f-348*S,H-233*S,690*S,19*S);}
 auto* C=Cast<AIslandController>(GetOwningPlayerController());if(C&&C->TouchUsed&&G->Focus<0&&!G->Paused){Panel(30*S,H-140*S,120*S,105*S,FLinearColor(.1,.22,.17,.5));Text(TEXT("Bewegen"),45*S,H-95*S,15*S,FLinearColor::White);Button(TEXT("Aktion"),W-185*S,H-135*S,155*S,100*S,910);}
}
