#if WITH_EDITOR
#include "Misc/AutomationTest.h"
#include "Tests/AutomationEditorCommon.h"
#include "Editor.h"
#include "IslandWorld.h"
#include "IslandFocusWidget.h"
#include "Camera/CameraComponent.h"
#include "ProceduralMeshComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Engine/GameViewportClient.h"
#include "Widgets/SViewport.h"
#include "Framework/Application/SlateApplication.h"
#include "ImageUtils.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "EngineUtils.h"
namespace {
bool CaptureFox(UWorld* W,const TCHAR* File){auto* V=W->GetGameViewport();auto Widget=V?V->GetGameViewportWidget():TSharedPtr<SViewport>();if(!Widget.IsValid())return false;TArray<FColor> Pixels;FIntVector Size;if(!FSlateApplication::Get().TakeScreenshot(Widget.ToSharedRef(),Pixels,Size))return false;TArray64<uint8> Bytes;FImageUtils::PNGCompressImageArray(Size.X,Size.Y,Pixels,Bytes);return FFileHelper::SaveArrayToFile(Bytes,*(FPaths::ProjectDir()/TEXT("Reports")/File));}
}
class FFoxCheck:public IAutomationLatentCommand{
 FAutomationTestBase* T;double Start=FPlatformTime::Seconds();int Phase=0;FLinearColor StoneColor;
 public:explicit FFoxCheck(FAutomationTestBase* Test):T(Test){}bool Update()override{
 auto* W=GEditor?GEditor->PlayWorld.Get():nullptr;auto* G=W?Cast<AIslandGameMode>(W->GetAuthGameMode()):nullptr;if(!G){if(FPlatformTime::Seconds()-Start<40)return false;T->AddError(TEXT("Fox PIE unavailable"));return true;}
 auto* P=G->Player();auto* C=P?Cast<AIslandController>(P->Controller):nullptr;if(!C)return false;
 auto Look=[&](FVector At){P->SetActorLocation(At);C->SetControlRotation((G->Fox->GetActorLocation()+FVector(0,0,45)-P->Camera->GetComponentLocation()).Rotation());};
 auto Hold=[&](int Next){G->Paused=true;Start=FPlatformTime::Seconds();Phase=Next;};
 if(Phase==0){G->SaveSlot=TEXT("LerninselFoxAutomation");G->ResetDemo();T->TestNotNull(TEXT("Sentence garden has a real petrified fox actor"),G->Fox);if(!G->Fox)return true;T->TestTrue(TEXT("Fox has colored articulated body geometry"),G->FoxParts.Num()>=20&&G->FoxBody&&G->FoxHead&&G->FoxTail&&G->FoxLatch);if(G->FoxParts.Num()==0||!G->FoxParts[0].Material)return true;StoneColor=G->FoxParts[0].Material->K2_GetVectorParameterValue(TEXT("Tint"));
 G->State.intro=true;G->State.introMask=5;G->State.verbs=true;G->State.pathCount=3;G->State.path={{0,4,8}};P->SetActorLocation(G->Target(510)->Pos);G->Interact(510);for(int Part:{1,0,2,3})G->UIAction(5000+Part);G->UIAction(5012);T->TestTrue(TEXT("Wrong sentence leaves statue and gate unchanged"),!G->State.sentence&&G->FoxTime==0&&G->GateBlocks(3));G->UIAction(4000);Look(FVector(1740,-400,88));Hold(1);return false;}
 if(FPlatformTime::Seconds()-Start<1)return false;
 if(Phase==1){T->TestTrue(TEXT("Actual stone fox capture"),CaptureFox(W,TEXT("Fox-Stone.png")));G->Paused=false;P->SetActorLocation(G->Target(510)->Pos);G->Interact(510);G->UIAction(5010);for(int Part:{0,1,2,3})G->UIAction(5000+Part);G->UIAction(5012);T->TestTrue(TEXT("Correct sentence wakes fox and returns to world"),G->State.sentence&&G->Focus<0&&G->FoxTime==0);G->Tick(.8f);T->TestTrue(TEXT("Fox begins material transformation"),!G->FoxParts[0].Material->K2_GetVectorParameterValue(TEXT("Tint")).Equals(StoneColor,.001));T->TestTrue(TEXT("Waking cannot release door latch"),G->GateBlocks(3)&&!G->FoxRopeReleased());float FocusTime=G->FoxTime;C->HandleWindowFocus(false);G->Tick(1);T->TestTrue(TEXT("Lost window focus suspends fox and world animation"),G->Paused&&G->FoxTime==FocusTime&&G->GateBlocks(3));G->Paused=true;G->FoxTime=FocusTime;G->RefreshWorld(0);C->HandleWindowFocus(true);if(C->FocusWidget)C->FocusWidget->SetVisibility(ESlateVisibility::Collapsed);Look(FVector(1750,-390,88));Hold(2);float Time=G->FoxTime;FVector Position=G->Fox->GetActorLocation();G->Tick(5);T->TestTrue(TEXT("Pause freezes fox time and position"),G->FoxTime==Time&&G->Fox->GetActorLocation().Equals(Position));return false;}
 if(Phase==2){T->TestTrue(TEXT("Actual waking fox capture"),CaptureFox(W,TEXT("Fox-Waking.png")));G->Paused=false;G->RefreshWorld(2.48f);T->TestTrue(TEXT("Fox walk clears the sentence undo post with body margin"),FVector::Dist2D(G->Fox->GetActorLocation(),G->Target(511)->Pos)>70);G->RefreshWorld(.72f);T->TestTrue(TEXT("Fox actually walks through scene"),G->Fox->GetActorLocation().X>2200&&G->Fox->GetActorLocation().X<3010);T->TestTrue(TEXT("Walking fox still cannot open gate"),G->GateBlocks(3));Look(FVector(2450,-190,88));Hold(3);return false;}
 if(Phase==3){T->TestTrue(TEXT("Actual walking fox capture"),CaptureFox(W,TEXT("Fox-Walking.png")));G->Paused=false;G->RefreshWorld(2.9f);T->TestTrue(TEXT("Fox reaches actual rope before release"),G->Fox->GetActorLocation().X>=3000&&G->GateBlocks(3)&&!G->FoxRopeReleased());auto* Rope=G->FoxRopeSegments[0];FVector End=Rope->GetComponentLocation()+Rope->GetUpVector()*Rope->GetComponentScale().Z*50;FVector Mouth=G->Fox->GetActorTransform().TransformPosition(FVector(64,0,54));T->TestTrue(TEXT("Rendered rope endpoint touches authored mouth"),FVector::Dist(End,Mouth)<1);Look(FVector(2850,-250,88));Hold(4);return false;}
 if(Phase==4){T->TestTrue(TEXT("Actual fox rope grip capture"),CaptureFox(W,TEXT("Fox-Grip.png")));G->Paused=false;G->RefreshWorld(1.4f);T->TestTrue(TEXT("Pulling before8.4 seconds keeps real gate blocked"),G->GateBlocks(3)&&!G->FoxRopeReleased()&&G->Fox->GetActorLocation().X<3010);Look(FVector(2820,-150,88));Hold(5);return false;}
 if(Phase==5){T->TestTrue(TEXT("Actual fox pulling rope capture"),CaptureFox(W,TEXT("Fox-Pull.png")));G->Paused=false;G->RefreshWorld(.2f);T->TestTrue(TEXT("Rope releases before door finishes opening"),G->FoxRopeReleased()&&G->GateBlocks(3));P->SetActorLocation(FVector(3000,0,90));FHitResult Blocked;P->SetActorLocation(FVector(3220,0,90),true,&Blocked);T->TestTrue(TEXT("Part-open fox gate physically blocks player"),Blocked.bBlockingHit);G->RefreshWorld(1.5f);G->RefreshWorld(.8f);T->TestFalse(TEXT("Fox scene and complete swing release gate"),G->GateBlocks(3));P->SetActorLocation(FVector(3000,0,90));FHitResult Passed;P->SetActorLocation(FVector(3220,0,90),true,&Passed);T->TestFalse(TEXT("Fully opened fox doorway admits actual capsule"),Passed.bBlockingHit);if(Passed.bBlockingHit){T->AddInfo(FString::Printf(TEXT("Sweep obstruction actor=%s component=%s normal=%s penetration=%d"),*GetNameSafe(Passed.GetActor()),*GetNameSafe(Passed.GetComponent()),*Passed.Normal.ToString(),Passed.bStartPenetrating));P->SetActorLocation(FVector(3000,0,90));FHitResult Raised;P->SetActorLocation(FVector(3220,0,90),true,&Raised);T->AddInfo(FString::Printf(TEXT("Raised capsule sweep blocked=%d actor=%s normal=%s"),Raised.bBlockingHit,*GetNameSafe(Raised.GetActor()),*Raised.Normal.ToString()));}float Time=G->FoxTime;G->Apply(Island::Action::SentenceCheck);T->TestEqual(TEXT("Rechecking solved sentence never restarts fox"),G->FoxTime,Time);G->Save();G->FoxTime=0;T->TestTrue(TEXT("Solved scene save loads"),G->Load());T->TestTrue(TEXT("Solved reload restores living final fox"),G->State.sentence&&G->FoxTime>=10.6f&&G->Fox->GetActorLocation().Y>300);int Count=0;for(TActorIterator<AActor> A(W);A;++A)if(A->ActorHasTag(TEXT("LerninselFox")))++Count;T->TestEqual(TEXT("One fox exists after scene and reload"),Count,1);P->SetActorLocation(FVector(2600,80,90));C->SetControlRotation(FRotator(0,13,0));Hold(6);return false;}
 T->TestTrue(TEXT("Actual final fox and open gate capture"),CaptureFox(W,TEXT("Fox-Open.png")));auto Saved=Island::Serialize(G->State);auto* Original=G->Fox;C->UpdateMode();T->TestNotNull(TEXT("Pause offers fox replay for solved save"),C->FocusWidget->ButtonFor(9005));G->UIAction(9005);T->TestTrue(TEXT("Replay starts statue animation without clearing progress"),!G->Paused&&G->Focus<0&&G->FoxTime==0&&Island::Serialize(G->State)==Saved&&G->Fox==Original);T->TestTrue(TEXT("Replay safely resets sentence gate at viewing start"),G->GateBlocks(3)&&P->GetActorLocation().X<2000);G->Paused=false;return true;
 }};
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FIslandFox,"GradeCrew.Lerninsel.Fox",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FIslandFox::RunTest(const FString&){ADD_LATENT_AUTOMATION_COMMAND(FEditorLoadMap(TEXT("/Game/Maps/Lerninsel")));ADD_LATENT_AUTOMATION_COMMAND(FStartPIECommand(false));ADD_LATENT_AUTOMATION_COMMAND(FFoxCheck(this));ADD_LATENT_AUTOMATION_COMMAND(FEndPlayMapCommand());return true;}
#endif
