#if WITH_EDITOR
#include "Misc/AutomationTest.h"
#include "Tests/AutomationEditorCommon.h"
#include "Editor.h"
#include "IslandWorld.h"
#include "IslandFocusWidget.h"
#include "Kismet/GameplayStatics.h"
#include "Components/Button.h"
#include "Components/CanvasPanel.h"
#include "Framework/Application/SlateApplication.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/SWindow.h"
#include "Layout/WidgetPath.h"
#include "Engine/GameViewportClient.h"
#include "Widgets/SViewport.h"
#include "ImageUtils.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
namespace {bool CaptureFour(UWorld* W,const TCHAR* Name){auto* Client=W->GetGameViewport();auto Widget=Client?Client->GetGameViewportWidget():TSharedPtr<SViewport>();if(!Widget.IsValid())return false;TArray<FColor> Pixels;FIntVector Size;if(!FSlateApplication::Get().TakeScreenshot(Widget.ToSharedRef(),Pixels,Size))return false;TArray64<uint8> Data;FImageUtils::PNGCompressImageArray(Size.X,Size.Y,Pixels,Data);return FFileHelper::SaveArrayToFile(Data,*(FPaths::ProjectDir()/TEXT("Reports")/Name));}}
class FFourPlayCheck:public IAutomationLatentCommand{
 FAutomationTestBase* Test;double Start=FPlatformTime::Seconds();int Phase=0,SentenceClick=0;
 public:explicit FFourPlayCheck(FAutomationTestBase* T):Test(T){}bool Update()override{
 UWorld* W=GEditor?GEditor->PlayWorld.Get():nullptr;auto* G=W?Cast<AIslandGameMode>(W->GetAuthGameMode()):nullptr;if(!G){if(FPlatformTime::Seconds()-Start<40)return false;Test->AddError(TEXT("Four puzzle PIE absent"));return true;}
 auto* P=G->Player();auto* C=P?Cast<AIslandController>(P->GetController()):nullptr;if(!C)return false;
 if(Phase==0){G->SaveSlot=TEXT("LerninselFourAutomation");auto* Legacy=Cast<UIslandSave>(UGameplayStatics::CreateSaveGameObject(UIslandSave::StaticClass()));Legacy->Snapshot=TEXT("LI1 1 1 1 0 0 0 5 3 3 1 0 4 8");Legacy->Position=FVector(4800,0,88);Legacy->View=FRotator::ZeroRotator;UGameplayStatics::SaveGameToSlot(Legacy,G->SaveSlot,0);Test->TestTrue(TEXT("Native LI1 migration loads previous progress"),G->Load());Test->TestTrue(TEXT("Native migration preserves old gates and leaves new room unsolved"),G->State.verbs&&G->State.water&&!G->State.sentence);Test->TestEqual(TEXT("Changed geography migration chooses safe start"),P->GetActorLocation().X,-1600.0);G->ResetDemo();Legacy->Snapshot=FString(UTF8_TO_TCHAR(Island::Serialize(G->State).c_str()));Legacy->Position=FVector(1000,0,88);UGameplayStatics::SaveGameToSlot(Legacy,G->SaveSlot,0);Test->TestTrue(TEXT("Valid unfinished LI2 state loads"),G->Load());Test->TestEqual(TEXT("First unsolved intro gate bounds safe load"),P->GetActorLocation().X,-1600.0);G->ResetDemo();Test->TestNotNull(TEXT("Sentence room target exists"),G->Target(510));Test->TestNotNull(TEXT("Route terrace exists"),G->Target(600));Test->TestNotNull(TEXT("Coast find exists"),G->Target(700));Test->TestNotNull(TEXT("Finale exists"),G->Target(800));
 Test->TestFalse(TEXT("Later room unavailable before garden success"),G->CanInspect(510));Test->TestFalse(TEXT("Coast alignment does not bypass untouched tasks"),G->PreviewAligned());
 for(int id:{0,2}){P->SetActorLocation(G->Target(100+id)->Pos+FVector(0,0,80));G->Interact(100+id);G->SelectFocused();}P->SetActorLocation(G->Target(11)->Pos);G->Interact(11);P->SetActorLocation(G->Target(20)->Pos);G->Interact(20);for(int id:{0,4,8}){P->SetActorLocation(G->Target(200+id)->Pos+FVector(0,0,80));G->Tick(.31f);}P->SetActorLocation(G->Target(21)->Pos);G->Interact(21);
 P->SetActorLocation(G->Target(510)->Pos);G->Tick(0);C->Interact();Test->TestTrue(TEXT("Normal controller opens sentence trial"),G->State.sentenceActive&&G->Focus==510);Test->TestNotNull(TEXT("Required answers use native focus widget"),C->FocusWidget);Start=FPlatformTime::Seconds();Phase=1;return false;}
 if(FPlatformTime::Seconds()-Start<1)return false;
 auto Click=[&](int id){UButton* B=C->FocusWidget->ButtonFor(id);if(!B){Test->AddError(FString::Printf(TEXT("UI button missing%d"),id));return;}auto S=StaticCastSharedRef<SButton>(B->TakeWidget());FGeometry Geometry=S->GetCachedGeometry();FVector2D Point=Geometry.GetAbsolutePosition()+Geometry.GetAbsoluteSize()*.5;TSet<FKey> Held;Held.Add(EKeys::LeftMouseButton);FPointerEvent Press(FSlateApplication::CursorPointerIndex,Point,Point,Held,EKeys::LeftMouseButton,0,FModifierKeysState());FWidgetPath Path;FSlateApplication::Get().GeneratePathToWidgetUnchecked(S,Path);if(!Path.IsValid()){Test->AddError(FString::Printf(TEXT("No attached Slate path for current button%d"),id));return;}S->OnMouseEnter(Geometry,Press);FReply Down=S->OnMouseButtonDown(Geometry,Press);FSlateApplication::Get().ProcessReply(Path,Down,&Path,&Press);FPointerEvent Release(FSlateApplication::CursorPointerIndex,Point,Point,TSet<FKey>(),EKeys::LeftMouseButton,0,FModifierKeysState());FReply Up=S->OnMouseButtonUp(Geometry,Release);FSlateApplication::Get().ProcessReply(Path,Up,&Path,&Release);};
 if(Phase==1){if(SentenceClick<4){Click(5000+SentenceClick);if(G->State.sentenceCount!=SentenceClick+1){Test->AddError(FString::Printf(TEXT("Native sentence click%d did not reach its current widget"),SentenceClick));return true;}++SentenceClick;Start=FPlatformTime::Seconds();return false;}Click(5012);Test->TestTrue(TEXT("Native pointer press/release confirms sentence"),G->State.sentence);Test->TestTrue(TEXT("Sentence gate has blocker while animating"),G->GateBlocks(3));G->UIAction(4000);
 P->SetActorLocation(G->Target(401)->Pos);G->Interact(401);P->SetActorLocation(G->Target(400)->Pos);for(int i=0;i<3;++i){G->Interact(400);G->Tick(.7f);}P->SetActorLocation(G->Target(403)->Pos+FVector(0,0,80));G->Interact(403);Test->TestTrue(TEXT("Correct bucket milestone"),G->State.water);P->SetActorLocation(G->Target(600)->Pos);G->Interact(600);Start=FPlatformTime::Seconds();Phase=11;return false;}
 if(Phase==11){bool ValidPoints=true;auto Point=[&](int Id)->FVector2D{auto* B=C->FocusWidget->ButtonFor(Id);if(!B){Test->AddError(FString::Printf(TEXT("Pointer fixture lost button%d Focus%d Phase%d"),Id,G->Focus,Phase));ValidPoints=false;return FVector2D::ZeroVector;}auto Geometry=B->GetCachedGeometry();return Geometry.GetAbsolutePosition()+Geometry.GetAbsoluteSize()*.5;};FVector2D At=Point(6010);if(!ValidPoints)return true;TSet<FKey> Held;Held.Add(EKeys::LeftMouseButton);FPointerEvent Down(FSlateApplication::CursorPointerIndex,At,At,Held,EKeys::LeftMouseButton,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseMoveEvent(Down,false);auto Window=FSlateApplication::Get().FindWidgetWindow(C->FocusWidget->TakeWidget());FSlateApplication::Get().ProcessMouseButtonDownEvent(Window.IsValid()?Window->GetNativeWindow():nullptr,Down);
 FSlateApplication::Get().ReleaseAllPointerCapture();Test->TestFalse(TEXT("Slate capture loss clears route ownership"),C->FocusWidget->PointerOwned);int Before=G->State.routeCount;FVector2D HoverPoint=Point(6011);if(!ValidPoints)return true;FPointerEvent Hover(FSlateApplication::CursorPointerIndex,HoverPoint,At,TSet<FKey>(),EKeys::Invalid,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseMoveEvent(Hover,false);Test->TestEqual(TEXT("Hover after capture loss cannot add answers"),G->State.routeCount,Before);
 G->UIAction(6000);FString MainSlot=G->SaveSlot;G->SaveSlot=TEXT("LerninselNoChangeAutomation");UGameplayStatics::DeleteGameInSlot(G->SaveSlot,0);G->UIAction(6010);Test->TestFalse(TEXT("Unchanged route event does not write a save"),UGameplayStatics::DoesSaveGameExist(G->SaveSlot,0));G->SaveSlot=MainSlot;
 FSlateApplication::Get().ProcessMouseMoveEvent(Down,false);FSlateApplication::Get().ProcessMouseButtonDownEvent(Window.IsValid()?Window->GetNativeWindow():nullptr,Down);FPointerEvent RightUp(FSlateApplication::CursorPointerIndex,At,At,Held,EKeys::RightMouseButton,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseButtonUpEvent(RightUp);Test->TestTrue(TEXT("Right release cannot end a held left route drag"),C->FocusWidget->PointerOwned);
 G->UIAction(6000);FSlateApplication::Get().ProcessMouseMoveEvent(Down,false);FSlateApplication::Get().ProcessMouseButtonDownEvent(Window.IsValid()?Window->GetNativeWindow():nullptr,Down);FGeometry BodyGeometry=C->FocusWidget->Body->GetCachedGeometry();FVector2D Outside=BodyGeometry.GetAbsolutePosition()-FVector2D(25,25);FPointerEvent Leave(FSlateApplication::CursorPointerIndex,Outside,At,Held,EKeys::Invalid,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseMoveEvent(Leave,false);Test->TestFalse(TEXT("Leaving actual board interrupts held route"),C->FocusWidget->PointerOwned);G->UIAction(6000);FSlateApplication::Get().ProcessMouseMoveEvent(Down,false);FSlateApplication::Get().ProcessMouseButtonDownEvent(Window.IsValid()?Window->GetNativeWindow():nullptr,Down);
 for(int Id:{6011,6012,6013,6020}){FVector2D Next=Point(Id);if(!ValidPoints)return true;FPointerEvent Move(FSlateApplication::CursorPointerIndex,Next,At,Held,EKeys::Invalid,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseMoveEvent(Move,false);At=Next;}FPointerEvent Up(FSlateApplication::CursorPointerIndex,At,At,TSet<FKey>(),EKeys::LeftMouseButton,0,FModifierKeysState());FSlateApplication::Get().ProcessMouseButtonUpEvent(Up);Test->TestTrue(TEXT("Real native captured route drag reaches bounded goal"),G->State.routeCount==5&&!C->FocusWidget->PointerOwned);Click(6031);Test->TestTrue(TEXT("Route focus completes exact whole"),G->State.fractions);G->RefreshWorld(1.5f);Test->TestTrue(TEXT("Fraction gate waits until full calibrated water animation"),G->GateBlocks(4));G->UIAction(4000);
 for(int id=700;id<704;++id){P->SetActorLocation(G->Target(id)->Pos);G->Interact(id);}P->SetActorLocation(G->Target(710)->Pos);G->Interact(710);for(int id:{7000,7002,7003})G->UIAction(id);G->UIAction(7010);Test->TestTrue(TEXT("Found versus selected coast state"),G->State.foundMask==15&&G->State.coastMask==13&&G->State.coastReady&&!G->State.coast);Test->TestTrue(TEXT("Requested viewing help remains available after amount check"),G->CanInspect(711));G->ConfirmCoast();Test->TestFalse(TEXT("Correct sum from wrong place never completes"),G->State.coast);G->UIAction(4000);P->SetActorLocation(G->ObservationStand);C->SetControlRotation(G->ObservationView);Test->TestTrue(TEXT("Authored actual observation pose matches geometry"),G->PreviewAligned());G->ConfirmCoast();Test->TestTrue(TEXT("Pose and correct selection complete coast"),G->State.coast);
 P->SetActorLocation(G->Target(800)->Pos);G->Interact(800);G->UIAction(8000);Test->TestTrue(TEXT("Four main signals complete prototype finale"),G->State.finale);G->UIAction(4000);P->SetActorLocation(FVector(1540,0,88));C->SetControlRotation(FRotator(-8,0,0));Start=FPlatformTime::Seconds();Phase=2;return false;}
 if(Phase==2){Test->TestTrue(TEXT("Sentence courtyard actual capture"),CaptureFour(W,TEXT("Four-SentenceWorld.png")));P->SetActorLocation(G->Target(510)->Pos);G->Interact(510);Start=FPlatformTime::Seconds();Phase=3;return false;}
 if(Phase==3){Test->TestTrue(TEXT("Native sentence widget actual capture"),CaptureFour(W,TEXT("Four-SentenceUI.png")));G->UIAction(4000);P->SetActorLocation(G->Target(600)->Pos);G->Interact(600);Start=FPlatformTime::Seconds();Phase=4;return false;}
 if(Phase==4){auto* Bottom=C->FocusWidget->ButtonFor(6017);auto* Control=C->FocusWidget->ButtonFor(6030);auto BG=Bottom->GetPaintSpaceGeometry(),CG=Control->GetPaintSpaceGeometry();FBox2D BB(BG.GetAbsolutePosition(),BG.GetAbsolutePosition()+BG.GetAbsoluteSize()),CB(CG.GetAbsolutePosition(),CG.GetAbsolutePosition()+CG.GetAbsoluteSize());Test->TestFalse(TEXT("Route third row never overlaps undo/check controls"),BB.Intersect(CB));
 for(const auto& Edge:C->FocusWidget->PaintedEdges){auto AG=C->FocusWidget->ButtonFor(6010+Edge.From)->GetPaintSpaceGeometry(),ZG=C->FocusWidget->ButtonFor(6010+Edge.To)->GetPaintSpaceGeometry();FVector2D AC=AG.GetAbsolutePosition()+AG.GetAbsoluteSize()*.5,ZC=ZG.GetAbsolutePosition()+ZG.GetAbsoluteSize()*.5,Dir=(ZC-AC).GetSafeNormal();auto Border=[&](FVector2D Size){return FMath::Min(FMath::Abs(Dir.X)>0.001?Size.X*.5/FMath::Abs(Dir.X):100000.f,FMath::Abs(Dir.Y)>0.001?Size.Y*.5/FMath::Abs(Dir.Y):100000.f);};Test->TestTrue(TEXT("Rendered route edge starts beside actual button in paint space"),FVector2D::Distance(Edge.Start,AC+Dir*(Border(AG.GetAbsoluteSize())+3))<8);}
 Test->TestTrue(TEXT("Native route graph actual capture"),CaptureFour(W,TEXT("Four-RouteUI.png")));G->UIAction(4000);P->SetActorLocation(FVector(6720,-400,88));C->SetControlRotation(FRotator(-8,20,0));Start=FPlatformTime::Seconds();Phase=5;return false;}
 if(Phase==5){Test->TestTrue(TEXT("Coast finds actual capture"),CaptureFour(W,TEXT("Four-CoastFinds.png")));P->SetActorLocation(G->ObservationStand);C->SetControlRotation(G->ObservationView);Start=FPlatformTime::Seconds();Phase=6;return false;}
 if(Phase==6){Test->TestTrue(TEXT("Actual projection window capture"),CaptureFour(W,TEXT("Four-CoastWindow.png")));P->SetActorLocation(FVector(11680,-350,88));C->SetControlRotation(FRotator(15,25,0));Start=FPlatformTime::Seconds();Phase=7;return false;}
 Test->TestTrue(TEXT("Four signal tower capture"),CaptureFour(W,TEXT("Four-Tower.png")));return true;
 }};
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FIslandFour,"GradeCrew.Lerninsel.FourPuzzles",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FIslandFour::RunTest(const FString&){ADD_LATENT_AUTOMATION_COMMAND(FEditorLoadMap(TEXT("/Game/Maps/Lerninsel")));ADD_LATENT_AUTOMATION_COMMAND(FStartPIECommand(false));ADD_LATENT_AUTOMATION_COMMAND(FFourPlayCheck(this));ADD_LATENT_AUTOMATION_COMMAND(FEndPlayMapCommand());return true;}
#endif
