#include "IslandFocusWidget.h"
#include "IslandWorld.h"
#include "Blueprint/WidgetTree.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Components/Border.h"
#include "Components/SizeBox.h"
#include "Components/ScaleBox.h"
#include "Kismet/GameplayStatics.h"
#include "Framework/Application/SlateApplication.h"
#include "Camera/CameraComponent.h"
#include "Rendering/DrawElements.h"
AIslandGameMode* UIslandFocusWidget::Game()const{return GetWorld()?Cast<AIslandGameMode>(GetWorld()->GetAuthGameMode()):nullptr;}
void UIslandUICommand::Run(){auto* G=Owner?Owner->Game():nullptr;if(G&&G->Focus==ExpectedFocus&&G->Paused==ExpectedPause)G->UIAction(Command);}
TSharedRef<SWidget> UIslandFocusWidget::RebuildWidget(){if(!WidgetTree)WidgetTree=NewObject<UWidgetTree>(this);auto* Scale=WidgetTree->ConstructWidget<UScaleBox>();Scale->SetStretch(EStretch::ScaleToFit);auto* Size=WidgetTree->ConstructWidget<USizeBox>();Size->SetWidthOverride(1040);Size->SetHeightOverride(740);auto* Border=WidgetTree->ConstructWidget<UBorder>();Border->SetBrushColor(FLinearColor(.022,.055,.04,.98));Border->SetPadding(FMargin(24));Body=WidgetTree->ConstructWidget<UCanvasPanel>();Border->SetContent(Body);Size->SetContent(Border);Scale->SetContent(Size);WidgetTree->RootWidget=Scale;SetIsFocusable(true);Refresh();return Super::RebuildWidget();}
void UIslandFocusWidget::Text(const FString& S,float X,float Y,float Width,float FontSize){auto* T=WidgetTree->ConstructWidget<UTextBlock>();T->SetText(FText::FromString(S));T->SetColorAndOpacity(FSlateColor(FLinearColor(.94,.94,.84)));auto Font=T->GetFont();Font.Size=FontSize;T->SetFont(Font);T->SetAutoWrapText(true);auto* Slot=Body->AddChildToCanvas(T);Slot->SetPosition(FVector2D(X,Y));Slot->SetSize(FVector2D(Width,100));}
void UIslandFocusWidget::Button(const FString& S,int Code,float X,float Y,float Width,float Height){auto* B=WidgetTree->ConstructWidget<UButton>();B->SetBackgroundColor(FLinearColor(.2,.34,.27));auto* T=WidgetTree->ConstructWidget<UTextBlock>();T->SetText(FText::FromString(S));auto F=T->GetFont();F.Size=22;T->SetFont(F);T->SetColorAndOpacity(FSlateColor(FLinearColor(.96,.95,.84)));T->SetJustification(ETextJustify::Center);B->SetContent(T);auto* Slot=Body->AddChildToCanvas(B);Slot->SetPosition(FVector2D(X,Y));Slot->SetSize(FVector2D(Width,Height));auto* C=NewObject<UIslandUICommand>(this);C->Owner=this;C->Command=Code;auto* G=Game();C->ExpectedFocus=G?G->Focus:-1;C->ExpectedPause=G&&G->Paused;Commands.Add(C);B->OnClicked.AddDynamic(C,&UIslandUICommand::Run);Buttons.Add(Code,B);}
UButton* UIslandFocusWidget::ButtonFor(int Id)const{auto* Found=Buttons.Find(Id);return Found?*Found:nullptr;}
void UIslandFocusWidget::NativeTick(const FGeometry& Geometry,float Dt){Super::NativeTick(Geometry,Dt);auto* G=Game();if(!G)return;FString Next=FString::Printf(TEXT("%d %d "),G->Focus,G->Paused)+UTF8_TO_TCHAR(Island::Serialize(G->State).c_str())+G->Feedback;if(!PointerOwned&&Next!=Signature){Signature=Next;Refresh();}}
void UIslandFocusWidget::Refresh(){if(!Body)return;auto* G=Game();if(!G)return;Body->ClearChildren();Buttons.Reset();Commands.Reset();
 if(G->Paused){Text(TEXT("Eine Pause auf der Insel"),40,35,900,34);Text(TEXT("Bestätigte Lösungen bleiben erhalten. Eine unterbrochene Portion zählt nicht."),40,120,900);Button(TEXT("Weiter erkunden"),9000,40,250,900);Button(TEXT("Sichtfeld 75 / 85 Grad"),9001,40,335,900);return;}
 const auto* Target=G->Target(G->Focus);Text(Target?Target->Label:TEXT("Inselrätsel"),32,22,920,32);Text(G->Feedback,32,545,920,20);
 if(G->Focus==510){Text(TEXT("Baue einen Satz, der etwas erzählt. Klicke alle vier Teile in deiner Reihenfolge. Das Verb „öffnet“ gehört auf Platz 2."),32,86,920);Text(TEXT("Beispiel: Morgen sucht die Eule den Brunnen. · sucht = Verb"),32,158,920,20);Text(G->SentenceText(),32,206,920,27);Text(TEXT("Dein Satz: Platz 1 → Platz 2: Verb → Platz 3 → Platz 4"),32,258,920,20);const TCHAR* Words[]={TEXT("heute"),TEXT("öffnet"),TEXT("der Fuchs"),TEXT("den Eingang")};for(int I=0;I<4;++I){bool Used=false;for(int K=0;K<G->State.sentenceCount;++K)Used|=G->State.sentenceParts[K]==I;Button(Words[I],5000+I,32+I*240,310,222,80);if(auto* B=ButtonFor(5000+I))B->SetBackgroundColor(Used?FLinearColor(.25,.52,.72):FLinearColor(.2,.34,.27));}Button(TEXT("Neu beginnen"),5010,32,430,285);Button(TEXT("Letzten Teil zurück"),5011,336,430,285);Button(TEXT("Satz prüfen"),5012,640,430,285);}
 else if(G->Focus==600){Text(TEXT("Fülle genau 1 Liter. Verbinde Start und Ziel über einen Ast. Addiere seine drei Brüche: Zusammen müssen sie 1 ergeben."),32,80,920);Button(TEXT("Start"),6010,20,265,130);const TCHAR* Values[]={TEXT("1/2"),TEXT("3/10"),TEXT("1/5"),TEXT("1/2"),TEXT("1/5"),TEXT("1/10"),TEXT("3/10"),TEXT("1/5"),TEXT("1/5")};for(int I=0;I<9;++I){bool Used=false;for(int K=0;K<G->State.routeCount;++K)Used|=G->State.route[K]==I+1;Button((Used?TEXT("• "):TEXT(""))+FString(Values[I]),6011+I,210+(I%3)*190,155+(I/3)*110,150,64);}Button(TEXT("Ziel"),6020,810,265,130);Button(TEXT("Linie neu"),6000,32,462,280);Button(TEXT("Kante zurück"),6030,337,462,280);Button(TEXT("Menge prüfen"),6031,642,462,280);}
 else if(G->Focus==710){Text(TEXT("Finde vier Reliefs unten am Küstenweg. Wähle hier drei Anteile, die zusammen 1 ergeben. Danach geht es zur Aussicht."),32,86,920);const TCHAR* Values[]={TEXT("1/10"),TEXT("1/5"),TEXT("2/5"),TEXT("1/2")};for(int I=0;I<4;++I){FString S=(G->State.foundMask&(1<<I))?FString(Values[I]):TEXT("Noch nicht gefunden");if(G->State.coastMask&(1<<I))S=TEXT("✓ ")+S;Button(S,7000+I,32+I*240,252,220,95);}Text(FString::Printf(TEXT("Ausgewählt: %d von 3 · Summe %d/10"),Island::CountBits(G->State.coastMask),Island::CoastTenths(G->State.coastMask)),32,370,900,26);Button(TEXT("Menge prüfen"),7010,32,438,438);Button(TEXT("Hinweis zur Aussicht"),7011,490,438,438);}
 else if(G->Focus==800){Text(G->State.finale?TEXT("Prototypabschnitt abgeschlossen. Vier von acht Hauptsignalen leuchten. Weitere Inselgebiete folgen."):TEXT("Verben, Satzweg, Bruchwasser und Felsfenster verbinden diesen Abschnitt mit dem Turm."),32,120,920,30);Button(TEXT("Vier Signale bestätigen"),8000,32,300,920);}
 else if(G->Focus==820||G->Focus==821){const bool Math=G->Focus==821;Text(Math?TEXT("Zusatz: Welcher Anteil ergänzt 1/6 + 1/4 zu einem Ganzen?"):TEXT("Zusatz: Welche Wortart hat Laufen im Satz Das Laufen macht Spaß?"),32,115,920,29);const TCHAR* Grammar[]={TEXT("Verb"),TEXT("Adjektiv"),TEXT("Nomen"),TEXT("Adverb")};const TCHAR* Fractions[]={TEXT("1/2"),TEXT("1/3"),TEXT("7/12"),TEXT("5/12")};for(int I=0;I<4;++I)Button(Math?Fractions[I]:Grammar[I],(Math?8210:8200)+I,32+I*240,300,220,85);}
 else {Text(Target?Target->Context:TEXT(""),32,118,920,30);bool Word=(G->Focus>=100&&G->Focus<=208);if(G->Focus>=500&&G->Focus<=503)Button(TEXT("Diesen Satzteil nehmen"),5000+G->Focus-500,32,350,920,82);if(Word)Button(TEXT("Auswahl bestätigen / zurücknehmen"),4001,32,350,920,82);}
 Button(TEXT("Zur Insel zurück · Esc"),4000,32,600,920,58);
}
int UIslandFocusWidget::NodeAt(FVector2D P)const{for(int Id=6010;Id<=6020;++Id)if(auto* B=ButtonFor(Id)){auto S=B->GetCachedWidget();if(S.IsValid()&&S->GetCachedGeometry().IsUnderLocation(P))return Id;}return -1;}
FReply UIslandFocusWidget::BeginRoutePointer(const FPointerEvent& E){auto* G=Game();if(!G||G->Focus!=600||G->Paused)return FReply::Unhandled();int Id=NodeAt(E.GetScreenSpacePosition());if(Id<0)return FReply::Unhandled();if(PointerOwned)return FReply::Handled();PointerOwned=true;PointerId=E.IsTouchEvent()?E.GetPointerIndex():-1;G->UIAction(Id);return FReply::Handled().CaptureMouse(TakeWidget());}
FReply UIslandFocusWidget::MoveRoutePointer(const FPointerEvent& E){if(!PointerOwned||(E.IsTouchEvent()?E.GetPointerIndex():-1)!=PointerId)return FReply::Unhandled();if((!E.IsTouchEvent()&&!E.IsMouseButtonDown(EKeys::LeftMouseButton))||!Body||!Body->GetCachedGeometry().IsUnderLocation(E.GetScreenSpacePosition())){CancelPointer();return FReply::Handled().ReleaseMouseCapture();}if(auto* G=Game()){int Id=NodeAt(E.GetScreenSpacePosition());if(Id>=0)G->UIAction(Id);}return FReply::Handled();}
FReply UIslandFocusWidget::EndRoutePointer(const FPointerEvent& E){if(!E.IsTouchEvent()&&E.GetEffectingButton()!=EKeys::LeftMouseButton)return FReply::Unhandled();if(!PointerOwned||(E.IsTouchEvent()?E.GetPointerIndex():-1)!=PointerId)return FReply::Unhandled();PointerOwned=false;PointerId=-2;return FReply::Handled().ReleaseMouseCapture();}
void UIslandFocusWidget::CancelPointer(){PointerOwned=false;PointerId=-2;if(FSlateApplication::IsInitialized()&&HasMouseCapture())FSlateApplication::Get().ReleaseAllPointerCapture();}
FReply UIslandFocusWidget::NativeOnPreviewMouseButtonDown(const FGeometry& G,const FPointerEvent& E){if(E.IsTouchEvent()&&PointerOwned&&E.GetPointerIndex()!=PointerId)return FReply::Handled();if(E.IsTouchEvent()||E.GetEffectingButton()==EKeys::LeftMouseButton){auto R=BeginRoutePointer(E);if(R.IsEventHandled())return R;}return Super::NativeOnPreviewMouseButtonDown(G,E);}
FReply UIslandFocusWidget::NativeOnMouseMove(const FGeometry& G,const FPointerEvent& E){auto R=MoveRoutePointer(E);return R.IsEventHandled()?R:Super::NativeOnMouseMove(G,E);}
FReply UIslandFocusWidget::NativeOnMouseButtonUp(const FGeometry& G,const FPointerEvent& E){auto R=EndRoutePointer(E);return R.IsEventHandled()?R:Super::NativeOnMouseButtonUp(G,E);}
FReply UIslandFocusWidget::NativeOnTouchStarted(const FGeometry& G,const FPointerEvent& E){auto R=BeginRoutePointer(E);return R.IsEventHandled()?R:Super::NativeOnTouchStarted(G,E);}
FReply UIslandFocusWidget::NativeOnTouchMoved(const FGeometry& G,const FPointerEvent& E){auto R=MoveRoutePointer(E);return R.IsEventHandled()?R:Super::NativeOnTouchMoved(G,E);}
FReply UIslandFocusWidget::NativeOnTouchEnded(const FGeometry& G,const FPointerEvent& E){auto R=EndRoutePointer(E);return R.IsEventHandled()?R:Super::NativeOnTouchEnded(G,E);}

int32 UIslandFocusWidget::NativePaint(const FPaintArgs& Args,const FGeometry& Geometry,const FSlateRect& Cull,FSlateWindowElementList& Draw,int32 Layer,const FWidgetStyle& Style,bool Enabled)const{int32 Top=Super::NativePaint(Args,Geometry,Cull,Draw,Layer,Style,Enabled);auto* G=Game();PaintedEdges.Reset();if(!G||G->Focus!=600)return Top;for(int From=0;From<10;++From)for(int To=1;To<=10;++To){if(!Island::RouteStepAllowed(From,To))continue;auto* A=ButtonFor(6010+From);auto* B=ButtonFor(6010+To);if(!A||!B)continue;auto GA=A->GetPaintSpaceGeometry(),GB=B->GetPaintSpaceGeometry();FVector2D AP=GA.GetAbsolutePosition()+GA.GetAbsoluteSize()*.5,BP=GB.GetAbsolutePosition()+GB.GetAbsoluteSize()*.5,D=(BP-AP).GetSafeNormal();if(D.IsNearlyZero())continue;auto Edge=[&](FVector2D Size){return FMath::Min(FMath::Abs(D.X)>0.001?Size.X*.5/FMath::Abs(D.X):100000.f,FMath::Abs(D.Y)>0.001?Size.Y*.5/FMath::Abs(D.Y):100000.f);};AP+=D*(Edge(GA.GetAbsoluteSize())+3);BP-=D*(Edge(GB.GetAbsoluteSize())+3);bool Chosen=false;for(int I=1;I<G->State.routeCount;++I)Chosen|=G->State.route[I-1]==From&&G->State.route[I]==To;TArray<FVector2D> Points={Geometry.AbsoluteToLocal(AP),Geometry.AbsoluteToLocal(BP)};FLinearColor Color=Chosen?(G->State.fractions?FLinearColor(.35,.85,.7):FLinearColor(.86,.67,.3)):FLinearColor(.32,.42,.34);PaintedEdges.Add({From,To,Geometry.LocalToAbsolute(Points[0]),Geometry.LocalToAbsolute(Points[1])});FSlateDrawElement::MakeLines(Draw,Top+1,Geometry.ToPaintGeometry(),Points,ESlateDrawEffect::None,Color,true,Chosen?6.f:3.f);}return Top+1;}

void UIslandFocusWidget::NativeOnMouseCaptureLost(const FCaptureLostEvent& E){bool Was=PointerOwned;PointerOwned=false;PointerId=-2;Super::NativeOnMouseCaptureLost(E);if(Was)if(auto* G=Game())G->Notify(TEXT("Linie unterbrochen. Der letzte bestätigte Knoten bleibt erhalten. Beginne einen neuen bewussten Druck."));}
