#include "IslandWorld.h"
#include "Camera/CameraComponent.h"
#include "Engine/Canvas.h"
#include "Engine/Engine.h"
#include "Engine/Font.h"
#include "CanvasItem.h"
#include "Kismet/GameplayStatics.h"
void AIslandHUD::Panel(float X,float Y,float W,float H,FLinearColor C){DrawRect(C,X,Y,W,H);}
void AIslandHUD::Text(const FString& S,float X,float Y,float Size,FLinearColor C){auto* F=GEngine->GetMediumFont();FCanvasTextItem T(FVector2D(X,Y),FText::FromString(S),F,C);T.Scale=FVector2D(Size/FMath::Max(1,F->GetMaxCharHeight()));T.EnableShadow(FLinearColor(0,0,0,.35));Canvas->DrawItem(T);}
void AIslandHUD::Wrap(const FString& S,float X,float Y,float Width,float Size){FString Line;float CY=Y;TArray<FString> Words;S.ParseIntoArrayWS(Words);for(const auto& Word:Words){FString Next=Line.IsEmpty()?Word:Line+TEXT(" ")+Word;float TW,TH;GetTextSize(Next,TW,TH,GEngine->GetMediumFont(),Size/FMath::Max(1,GEngine->GetMediumFont()->GetMaxCharHeight()));if(TW>Width&&!Line.IsEmpty()){Text(Line,X,CY,Size,FLinearColor(.92,.93,.84));CY+=Size*1.55f;Line=Word;}else Line=Next;}if(!Line.IsEmpty())Text(Line,X,CY,Size,FLinearColor(.92,.93,.84));}
void AIslandHUD::Button(const FString& S,float X,float Y,float W,float H,int Action){Panel(X,Y,W,H,FLinearColor(.17,.27,.23,.97));Text(S,X+20*Scale,Y+H*.25f,20*Scale,FLinearColor(.94,.93,.8));Buttons.Add({FBox2D(FVector2D(X,Y),FVector2D(X+W,Y+H)),Action});}
bool AIslandHUD::ClickAt(FVector2D P){auto* G=Cast<AIslandGameMode>(UGameplayStatics::GetGameMode(this));if(!G)return false;for(const auto& B:Buttons)if(B.Bounds.IsInside(P)){switch(B.Action){case 800:G->Focus=-1;break;case 801:G->SelectFocused();break;case 900:G->Paused=false;break;case 901:if(auto* Char=G->Player())Char->Camera->SetFieldOfView(Char->Camera->FieldOfView<80?85:75);return true;case 910:if(G->Near>=0)G->Interact(G->Near);return true;default:return false;}if(auto* C=Cast<AIslandController>(GetOwningPlayerController())){C->CancelInput();C->UpdateMode();}return true;}return false;}
void AIslandHUD::DrawHUD(){Super::DrawHUD();if(!Canvas)return;auto* G=Cast<AIslandGameMode>(UGameplayStatics::GetGameMode(this));if(!G)return;Buttons.Reset();float W=Canvas->SizeX,H=Canvas->SizeY;Scale=FMath::Clamp(FMath::Min(W/1440.f,H/900.f),.65f,2.f);float S=Scale;
 if(G->Clock<16&&!G->Paused&&G->Focus<0){Panel(28*S,26*S,545*S,46*S,FLinearColor(.08,.15,.12,.75));Text(TEXT("WASD · Mausblick · E untersuchen · Esc Pause"),42*S,39*S,18*S,FLinearColor(.94,.94,.84));}
 if(G->State.pathActive&&G->Focus<0){Panel(28*S,90*S,520*S,62*S,FLinearColor(.08,.15,.12,.83));Text(FString::Printf(TEXT("Verbweg · Reihe %d von 3"),FMath::Min(3,G->State.pathCount+1)),44*S,102*S,20*S,FLinearColor(.95,.94,.83));Text(G->State.pathFailed?TEXT("Schritt am Randstein zurücknehmen"):TEXT("Gehe mittig auf ein Verb. Beginne vorne."),44*S,128*S,15*S,FLinearColor(.82,.9,.8));}
 if(!G->State.intro&&G->Focus<0&&G->Clock>16){Text(FString::Printf(TEXT("Verbprobe · %d von 2 ausgewählt"),Island::CountBits(G->State.introMask)),30*S,30*S,18*S,FLinearColor(.96,.94,.82));}
 if(G->State.carrying){Panel(W-310*S,28*S,280*S,74*S,FLinearColor(.08,.17,.16,.85));Text(TEXT("Mess-Eimer · 1 L"),W-292*S,39*S,18*S,FLinearColor(.94,.93,.82));Text(FString::Printf(TEXT("%d/10 Liter  ·  %d ml"),G->State.tenths,G->State.tenths*100),W-292*S,68*S,20*S,FLinearColor(.66,.92,.88));}
 if(G->State.carrying&&!G->Paused&&G->Focus<0){float GX=W-260*S,GY=140*S;Panel(GX-20*S,GY-20*S,230*S,260*S,FLinearColor(.08,.17,.16,.88));Text(TEXT("Kapazität: 1 Liter"),GX,GY-5*S,16*S,FLinearColor(.94,.94,.84));for(int I=1;I<=10;++I){float Y=GY+35*S+(10-I)*19*S;Panel(GX,Y,35*S,14*S,I<=G->State.tenths?FLinearColor(.3,.7,.8):FLinearColor(.24,.32,.3));Text(FString::Printf(TEXT("%d/10"),I),GX+50*S,Y-1*S,14*S,FLinearColor(.94,.94,.84));}}
 if(G->Focus<0&&!G->Paused){DrawRect(FLinearColor(.96,.94,.8,.9),W*.5f-2,H*.5f-2,4,4);if(const auto* T=G->Target(G->Near)){Panel(W*.5f-310*S,H-112*S,620*S,54*S,FLinearColor(.08,.15,.12,.83));Text(TEXT("E · ")+T->Label,W*.5f-290*S,H-96*S,19*S,FLinearColor(.97,.95,.82));}}
 if(G->MessageTime>0&&G->Focus<0&&!G->Paused){Panel(W*.5f-370*S,H-202*S,740*S,72*S,FLinearColor(.08,.16,.13,.86));Wrap(G->Feedback,W*.5f-348*S,H-187*S,690*S,19*S);}
 auto* C=Cast<AIslandController>(GetOwningPlayerController());if(C&&C->TouchUsed&&G->Focus<0&&!G->Paused){Panel(30*S,H-140*S,120*S,105*S,FLinearColor(.1,.22,.17,.5));Text(TEXT("Bewegen"),45*S,H-95*S,15*S,FLinearColor::White);Button(TEXT("Aktion"),W-185*S,H-135*S,155*S,100*S,910);}
}
