// Generated by Tools/generate_tasks.py; edit Content/Tasks/tasks.json.
#pragma once
#include <array>
#include <cstdint>
#include <string>
#include <vector>
namespace Island {
struct TaskDefinition { int Id; const char* Title; const char* Type; const char* Instruction; const char* Goal; const char* Variants; std::array<const char*,3> Hints; const char* HiddenClue; const char* ClueLocation; std::vector<int> Prerequisites; const char* FollowUp; const char* CompletionFlag; };
inline const std::array<TaskDefinition,9>& TaskDefinitions() {
 static const std::array<TaskDefinition,9> Tasks = {{
  {100,"Zwei Verben finden","Wortarten","Finde zwei Wörter, die sagen, was jemand tut. Klicke die Wörter an; der ganze Stein wird blau.","Zwei Verben markieren","Direktklick oder E; erneuter Klick nimmt die Wahl zurück.",{{"Was tut jemand gerade?","Ein Verb beschreibt eine Handlung.","„läuft“ und „springt“ sind Verben. Suche passende Wörter."}},"Fußspuren zeigen zu den Tun-Wörtern.","Steinweg am Startgarten",{},"Das erste Tor öffnet sich.","intro"},
  {200,"Der Verbweg","Wortarten und Reihenfolge","Gehe von Reihe 1 bis Reihe 3. Wähle in jeder Reihe genau ein Verb: Was tut jemand?","Drei Verben in Reihenfolge wählen","Direktklick, E oder kurz auf den Wortsteinen stehen.",{{"Beginne ganz vorne bei Reihe 1.","Ein Verb sagt, was jemand tut.","Suche je ein Tun-Wort in Reihe 1, 2 und 3."}},"Kleine Blattspuren zeigen von vorne nach hinten.","Boden vor Reihe 1",{100},"Das Tor zum Satzgarten öffnet sich.","verbs"},
  {300,"Der Satz für den Fuchs","Satzbau","Lege die vier Wortteile zu einem Satz. Das Verb „öffnet“ gehört auf Platz 2.","Einen vollständigen Satz legen","Wortteile lassen sich zurücknehmen und neu ordnen.",{{"Lies die Wortteile laut in deiner Reihenfolge.","Im Aussagesatz steht das Verb meistens auf Platz 2.","„Heute öffnet der Fuchs den Eingang.“"}},"Vier Pfotenabdrücke führen vom Satzplatz zum versteinerten Fuchs.","Satzhof beim Fuchs",{200},"Der Fuchs wacht auf, läuft zum Tor, zieht am Seil und löst den Riegel.","sentence"},
  {400,"300 ml im Eimer","Messen und Brüche","Fülle denselben 1-Liter-Eimer bis 3/10. Jeder kleine Schritt sind 1/10 Liter = 100 ml.","300 ml auf die Platte stellen","Wasser lässt sich einfüllen und wieder ablassen.",{{"Ein Liter hat zehn gleich große Zehntel.","3/10 Liter sind 300 ml.","Fülle dreimal 100 ml ein und stelle den Eimer auf die Platte."}},"Drei blaue Rillen leiten vom Hahn zur Platte.","Eimerterrasse",{300},"Die Tür zur zweiten Wasserprobe öffnet sich.","water"},
  {500,"Ein ganzer Liter","Messen und Brüche","Hol denselben Messbecher von der ersten Probe. Fülle ihn hier bis 1 Liter und gieße ihn in das Becken.","1000 ml einfüllen und ausgießen","100 oder 200 ml einfüllen; je 100 ml ablassen; unbegrenzt versuchen.",{{"Der Becher fasst genau 1 Liter.","Die Skala zählt in Zehnteln: 10/10 sind 1 Liter.","Fülle bis zur 10/10-Linie und gieße dann ins Becken."}},"Die zehn Rillen am Becher passen zu den zehn Linien am Becken.","Messbecher und Zielbecken",{400},"Das Wasserbecken hebt das nächste Tor.","fractions"},
  {600,"Alles eine Frage der Perspektive","Rätsel und Beobachten","Stell dich auf die runde Bodenmarkierung. Schau dich um, bis die drei Bögen einen geschlossenen Ring bilden. Drücke E.","Drei getrennte Bögen als einen Ring erkennen","Vom Standpunkt aus langsam nach links/rechts schauen und neu versuchen.",{{"Der Ring ist nicht von überall zu sehen.","Suche die runde Markierung vor der Aussicht.","Stelle dich mitten auf den Ring und richte die Bögen mit Maus oder Finger aus."}},"Drei Kerben auf der Markierung zeigen in Richtung der Bögen.","Runde Aussichtskante",{500},"Die Ringform aktiviert das vierte Signal und öffnet den Weg.","coast"},
  {700,"Vier Signale","Erkunden","Du hast vier Signale auf der Insel geweckt. Geh zum Turm und drücke E, um sie zu verbinden.","Den Turmabschnitt abschließen","Bei Bedarf in Ruhe zurückgehen und die offenen Wege prüfen.",{{"Achte auf die vier grünen Lichtlinien.","Jede Linie beginnt an einem gelösten Tor.","Folge den Linien zum Turm und prüfe das große Zeichen."}},"Vier eingelassene Lichtlinien treffen sich am Turm.","Hauptweg und Signalturm",{600},"Der erste Inselabschnitt ist abgeschlossen.","finale"},
  {820,"Wortarten-Zusatz","Zusatz und Sprache","Lies den Satz: „Das Laufen macht Spaß.“ Welche Wortart ist „Laufen“ hier?","Nomen erkennen","Zusatzfrage; Hauptweg bleibt offen.",{{"Schau auf den Artikel davor.","Ein Artikel kann vor einem Nomen stehen.","„Das“ zeigt hier: Laufen ist ein Nomen."}},"Ein kleiner Artikelstein steht vor dem Satz.","Zusatzplatz im Satzgarten",{200},"Ein kleines Zusatzlicht geht an.","bonus-words"},
  {821,"Bruch-Zusatz","Zusatz und Brüche","Welcher Bruch ergänzt 1/6 + 1/4 zu einem Ganzen?","7/12 auswählen","Zusatzfrage; Hauptweg bleibt offen.",{{"Suche einen gemeinsamen Nenner.","1/6 sind 2/12, 1/4 sind 3/12.","Zusammen sind das 5/12. Es fehlen 7/12."}},"Zwölf kleine Kerben umrunden den Zusatzstein.","Zusatzplatz bei der Wasserterrasse",{500},"Ein kleines Zusatzlicht geht an.","bonus-fractions"},
 }};
 return Tasks;
}
inline bool TaskDefinitionsValid() {
 const auto& tasks=TaskDefinitions();
 for(std::size_t i=0;i<tasks.size();++i){const auto& t=tasks[i];if(t.Id<=0||!t.Title||!t.Type||!t.Instruction||!t.Goal||!t.Variants||!t.HiddenClue||!t.ClueLocation||!t.FollowUp||!t.CompletionFlag)return false;for(const char* h:t.Hints)if(!h||!*h)return false;for(std::size_t j=i+1;j<tasks.size();++j)if(t.Id==tasks[j].Id)return false;}
 return true;
}
enum class TaskStage { Locked, Available, Active, Solved };
inline int TaskIndex(int id){const auto& tasks=TaskDefinitions();for(std::size_t i=0;i<tasks.size();++i)if(tasks[i].Id==id)return static_cast<int>(i);return -1;}
inline std::uint64_t TaskBit(int id){const int i=TaskIndex(id);return i<0?0:(std::uint64_t{1}<<i);}
inline TaskStage TaskStageFor(int id,std::uint64_t solved,std::uint64_t active=0){const int i=TaskIndex(id);if(i<0)return TaskStage::Locked;const std::uint64_t bit=std::uint64_t{1}<<i;if(solved&bit)return TaskStage::Solved;for(int dep:TaskDefinitions()[i].Prerequisites){const auto d=TaskBit(dep);if(!d||!(solved&d))return TaskStage::Locked;}return active&bit?TaskStage::Active:TaskStage::Available;}
}
