const test=require('node:test'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const path=require('node:path');
let factory;
async function fixture(overrides={}){
 if(!factory){try{({createAccountController:factory}=await import('../../admin-account-actions.mjs'));}catch(_){factory=()=>({render(){},reset(){}});}}
 const dom=new JSDOM('<div id="root"></div>'),root=dom.window.document.querySelector('#root');let uid='a',calls=[],refreshed=0;
 const rows=[{id:'a',role:'admin',status:'active',displayName:'Own admin'},{id:'b',role:'admin',status:'active',displayName:'Visible admin'},{id:'t',role:'teacher',status:'active',displayName:'Visible teacher',email:'teacher@example.invalid'}];
 const call=async(name,data)=>{calls.push({name,data});if(name==='previewAdminAccountAction')return {operationId:'00000000-0000-0000-0000-000000000000',targets:data.targets.map(id=>({id,label:rows.find(x=>x.id===id)?.displayName,code:'allowed'})),extent:'Tests, Abgaben und Ergebnisse bleiben erhalten.'};return {status:'complete',outcomes:rows.filter(x=>x.id!=='a').map(x=>({id:x.id,code:'complete'}))};};
 const controller=factory({root,getSession:()=>uid,call:overrides.call||call,refresh:async()=>refreshed++,open:()=>{},formatDate:()=>'-'});controller.render(rows,{allUsers:rows});
 return {dom,root,rows,controller,calls,setUid:x=>uid=x,refreshed:()=>refreshed};
}
const flush=()=>new Promise(r=>setImmediate(r));
const click=(f,selector)=>{const el=f.root.querySelector(selector);assert.ok(el,selector);el.click();return el;};
test('filtered select-all includes only visible accounts and prunes hidden selection',async()=>{const f=await fixture();click(f,'[data-select-all]');assert.equal(f.root.querySelector('[data-selected-count]').textContent,'2 ausgewählt');f.controller.render([f.rows[2]],{allUsers:f.rows});assert.equal(f.root.querySelector('[data-selected-count]').textContent,'1 ausgewählt');click(f,'[data-bulk-action="delete"]');await flush();assert.deepEqual(f.calls[0].data.targets,['t']);});
test('row actions use Öffnen, native Rolle select, Löschen in that order and protect self',async()=>{const f=await fixture();const row=f.root.querySelector('[data-account-id="t"]');const controls=[...row.querySelector('[data-account-actions]').children];assert.equal(controls[0].textContent,'Öffnen');assert.equal(controls[1].tagName,'SELECT');assert.equal(controls[2].textContent,'Löschen');assert.equal(f.root.querySelector('[data-account-id="a"] [data-row-action="delete"]').disabled,true);assert.equal(f.root.querySelector('[data-account-id="a"] input').disabled,true);});
test('destructive preview names targets and preserved school data; cancel never executes',async()=>{const f=await fixture();click(f,'[data-account-id="t"] [data-row-action="delete"]');await flush();const d=f.root.querySelector('dialog');assert.ok(d?.hasAttribute('open'));assert.match(d.textContent,/Visible teacher/);assert.match(d.textContent,/Tests, Abgaben und Ergebnisse bleiben/);click(f,'[data-cancel]');await flush();assert.equal(f.calls.length,1);assert.equal(f.root.querySelector('dialog'),null);});
test('native keyboard select change previews a role action and excludes test promotion',async()=>{const f=await fixture();const select=f.root.querySelector('[data-account-id="t"] select');select.value='admin';select.dispatchEvent(new f.dom.window.Event('change'));await flush();assert.equal(f.calls[0].data.action,'role');assert.equal(f.calls[0].data.value,'admin');f.controller.reset();f.controller.render([{...f.rows[2],isTestAccount:true}],{allUsers:f.rows});assert.equal(f.root.querySelector('select[data-row-role] option[value="admin"]').disabled,true);});
test('account switch invalidates pending preview and clears identities and selection',async()=>{let done;const f=await fixture({call:()=>new Promise(r=>done=r)});click(f,'[data-select-all]');click(f,'[data-bulk-action="delete"]');f.setUid('different');f.controller.reset();done({operationId:'op',targets:[{id:'t',label:'Old private identity',code:'allowed'}],extent:'private'});await flush();assert.equal(f.root.querySelector('dialog'),null);assert.equal(f.root.textContent.includes('Old private identity'),false);});
test('double confirm starts once and no success is shown before execution settles',async()=>{let complete,calls=0;const f=await fixture({call:async name=>{if(name==='previewAdminAccountAction')return{operationId:'op',targets:[{id:'t',label:'T',code:'allowed'}],extent:'school records preserved'};calls++;return new Promise(r=>complete=r);}});click(f,'[data-account-id="t"] [data-row-action="delete"]');await flush();click(f,'[data-confirm]');click(f,'[data-confirm]');await flush();assert.equal(calls,1);assert.equal(f.root.textContent.includes('1 Konto gelöscht'),false);complete({status:'complete',outcomes:[{id:'t',code:'complete'}]});await flush();assert.match(f.root.textContent,/1 Konto gelöscht/);});
test('partial deletion retains same operation for explicit retry and reports failure',async()=>{let executions=0,ids=[];const f=await fixture({call:async(name,data)=>{if(name==='previewAdminAccountAction')return{operationId:'same',targets:[{id:'t',label:'T',code:'allowed'}],extent:'school records preserved'};ids.push(data.operationId);executions++;return{status:executions===1?'partial':'complete',outcomes:[{id:'t',code:executions===1?'failed':'complete'}]};}});click(f,'[data-account-id="t"] [data-row-action="delete"]');await flush();click(f,'[data-confirm]');await flush();assert.match(f.root.textContent,/nicht vollständig/);assert.match(f.root.textContent,/T: nicht vollständig abgeschlossen/);click(f,'[data-retry]');await flush();assert.deepEqual(ids,['same','same']);assert.match(f.root.textContent,/1 Konto gelöscht/);});
test('blocked last-admin and active-exam targets cannot be committed from confirmation',async()=>{const f=await fixture({call:async()=>({operationId:'blocked',targets:[{id:'b',label:'B',code:'last-admin'},{id:'t',label:'T',code:'active-exam'}],extent:'preserved'})});click(f,'[data-account-id="t"] [data-row-action="delete"]');await flush();assert.equal(f.root.querySelector('[data-confirm]').disabled,true);assert.match(f.root.textContent,/Letzter aktiver Admin|laufenden veröffentlichten Test/);});
test('reloaded pending deletion can resume its durable server operation without starting a new preview',async()=>{const f=await fixture();f.controller.render([{...f.rows[2],accountDeletionId:'durable-op',status:'deleting'}],{allUsers:[f.rows[0],{...f.rows[2],accountDeletionId:'durable-op',status:'deleting'}]});click(f,'[data-resume-operation]');await flush();assert.equal(f.calls.length,1);assert.equal(f.calls[0].name,'executeAdminAccountAction');assert.equal(f.calls[0].data.operationId,'durable-op');});
