const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE_PATH||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const url=process.env.PIZZA_URL||'http://127.0.0.1:4187';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PIZZA_BROWSER_CHANNEL||'chrome'});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('#start').click();
 await page.locator('#station-oven').click();
 await page.waitForFunction(()=>document.querySelector('#carry').textContent.includes('frische Pizza'));
 await page.locator('#station-board').click();
 await page.locator('#cut-dialog').waitFor({state:'visible'});
 const box=await page.locator('#pizza-svg').boundingBox();
 const cut=async(x1,y1,x2,y2)=>{await page.mouse.move(box.x+box.width*x1,box.y+box.height*y1);await page.mouse.down();await page.mouse.move(box.x+box.width*x2,box.y+box.height*y2,{steps:12});await page.mouse.up();};
 await cut(.5,.04,.5,.96);await cut(.04,.5,.96,.5);
 assert.equal(await page.locator('#pizza-svg .slice').count(),4);
 await page.locator('#pizza-svg .slice').nth(0).click();
 await page.locator('#pizza-svg .slice').nth(1).click();
 await page.locator('#plate').click();
 await page.locator('#order-1').click();
 await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('1 / 4'));
 assert.match(await page.locator('#feedback').textContent(),/Viertel/);
 assert.equal(await page.locator('.order-card').count(),2);
 await page.locator('#help-button').click();
 const before=JSON.parse(await page.evaluate(()=>localStorage.getItem('gc-pizza-v1'))).orders[0].patience;
 await page.waitForTimeout(1100);
 const after=JSON.parse(await page.evaluate(()=>localStorage.getItem('gc-pizza-v1'))).orders[0].patience;
 assert.equal(after,before);
 await page.locator('#help-close').click();
 await page.locator('#station-oven').click();await page.waitForFunction(()=>document.querySelector('#carry').textContent.includes('frische Pizza'));await page.locator('#station-board').click();
 await page.locator('#cut-dialog').waitFor({state:'visible'});
 await page.locator('summary').click();await page.locator('#angle-cut').click();
 await page.reload();await page.locator('#resume').click();
 assert.equal(await page.locator('#pizza-svg .slice').count(),2);
 await page.locator('#pizza-svg .slice').nth(0).focus();await page.waitForTimeout(700);
 assert.equal(await page.evaluate(()=>document.activeElement?.dataset.index),'0','Slice keyboard focus must survive patience refresh');
 await page.locator('#cut-close').click();
 assert.equal(errors.length,0,errors.join('\n'));
 fs.mkdirSync('reports',{recursive:true});await page.screenshot({path:'reports/desktop.png',fullPage:true});
 const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 const mobile=await touch.newPage();await mobile.goto(url);await mobile.locator('#start').tap();
 await mobile.locator('#station-oven').tap();await mobile.waitForFunction(()=>document.querySelector('#carry').textContent.includes('frische Pizza'));await mobile.locator('#station-board').tap();
 await mobile.locator('#cut-dialog').waitFor({state:'visible'});
 await mobile.locator('summary').tap();await mobile.locator('#angle-cut').tap();assert.equal(await mobile.locator('#pizza-svg .slice').count(),2);
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.screenshot({path:'reports/mobile.png',fullPage:true});
 console.log('PASS: ordinary cold start, four real slices, equivalent delivery, two orders, paused help, reload/continue, narrow touch layout, zero runtime errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
