"use strict";
const { randomBytes, randomUUID } = require("node:crypto");
const { FieldValue } = require("firebase-admin/firestore");
const { hash,token,fail,text,cleanName,cleanSummary,officialConfig } = require("./common");
module.exports=function makeHighscore(db){
  async function leaderboard(boardId,limit=20){const s=await db.collection("fehlerjagdBoards").doc(boardId).collection("scores").orderBy("score","desc").limit(Math.min(30,Math.max(1,limit))).get();return s.docs.map((d,i)=>{const v=d.data();return{rank:i+1,name:text(v.name,24),score:Number(v.score||0),correct:Number(v.correct||0),total:Number(v.total||0)}});}
  async function publicBoard(p){const {boardId}=officialConfig(p.grade,p.focus);return{leaderboard:await leaderboard(boardId)}}
  async function createHighscoreAttempt(p){const name=cleanName(p.name),key=String(p.playerKey||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,64);if(key.length<8)fail("player_key_invalid","Spielerkennung ungültig.");const {boardId,config}=officialConfig(p.grade,p.focus),attemptId=randomUUID(),attemptToken=token(),seed=randomBytes(4).readUInt32BE(0),startsAtMs=Date.now(),endsAtMs=startsAtMs+120000;await db.collection("fehlerjagdAttempts").doc(attemptId).create({attemptId,tokenHash:hash(attemptToken),playerKeyHash:hash(key),name,boardId,config,seed,status:"running",startsAtMs,endsAtMs,createdAt:FieldValue.serverTimestamp()});return{attemptId,attemptToken,boardId,config,seed,startsAtMs,endsAtMs,leaderboard:await leaderboard(boardId)}}
  async function finishHighscoreAttempt(p){const ref=db.collection("fehlerjagdAttempts").doc(String(p.attemptId||"").slice(0,80)),s=await ref.get();if(!s.exists)fail("attempt_not_found","Highscore-Versuch nicht gefunden.",404);const a=s.data();if(hash(p.attemptToken)!==a.tokenHash)fail("attempt_forbidden","Highscore-Versuch ungültig.",403);if(a.status!=="running")fail("attempt_finished","Versuch wurde bereits gespeichert.",409);if(Date.now()<Number(a.endsAtMs)-5000)fail("attempt_too_early","Der Versuch läuft noch.",409);const sum=cleanSummary(p.summary),scoreRef=db.collection("fehlerjagdBoards").doc(a.boardId).collection("scores").doc(a.playerKeyHash.slice(0,40));let personalBest=false;await db.runTransaction(async tx=>{const old=await tx.get(scoreRef);if(!old.exists||sum.score>Number(old.data()?.score||-Infinity)){personalBest=true;tx.set(scoreRef,{name:a.name,...sum,updatedAt:FieldValue.serverTimestamp()});}tx.update(ref,{status:"finished",summary:sum,finishedAt:FieldValue.serverTimestamp()});});return{personalBest,leaderboard:await leaderboard(a.boardId)}}
  return{leaderboard:publicBoard,createHighscoreAttempt,finishHighscoreAttempt};
};
