"use strict";
const { randomBytes, randomUUID } = require("node:crypto");
const { FieldValue } = require("firebase-admin/firestore");
const { hash,token,fail,text,cleanName,cleanConfig,cleanSummary } = require("./common");
const MAX_PLAYERS=30,ROOM_TTL=6*60*60*1000;
module.exports=function makeRooms(db){
  async function getRoom(code){code=String(code||"").replace(/\D/g,"").slice(0,6);if(code.length!==6)fail("room_code_invalid","Bitte einen 6-stelligen Rundencode eingeben.");const ref=db.collection("fehlerjagdRooms").doc(code),snap=await ref.get();if(!snap.exists)fail("room_not_found","Diese Runde wurde nicht gefunden.",404);const room=snap.data();if(Number(room.expiresAtMs||0)<Date.now())fail("room_expired","Diese Runde ist abgelaufen.",410);return{code,ref,room};}
  async function createRoom(p){const config=cleanConfig(p.config),hostToken=token(),now=Date.now();for(let i=0;i<30;i++){const code=String(Math.floor(100000+Math.random()*900000)),ref=db.collection("fehlerjagdRooms").doc(code);try{await ref.create({code,seed:randomBytes(4).readUInt32BE(0),config,status:"waiting",hostTokenHash:hash(hostToken),playerCount:0,createdAtMs:now,startsAtMs:null,endsAtMs:null,expiresAtMs:now+ROOM_TTL,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return{code,hostToken,config,maxPlayers:MAX_PLAYERS};}catch(e){if(![6,"6","ALREADY_EXISTS","already-exists"].includes(e?.code))throw e;}}fail("room_code_unavailable","Kein freier Rundencode verfügbar.",503);}
  async function joinRoom(p){const name=cleanName(p.name),{code,ref}=await getRoom(p.code),playerId=randomUUID(),playerToken=token(),pr=ref.collection("players").doc(playerId);let config,seed;await db.runTransaction(async tx=>{const s=await tx.get(ref),r=s.data();if(r.status!=="waiting")fail("room_started","Die Runde wurde bereits gestartet.",409);if(Number(r.playerCount||0)>=MAX_PLAYERS)fail("room_full","Die Runde ist voll.",409);config=r.config;seed=r.seed;tx.create(pr,{id:playerId,name,tokenHash:hash(playerToken),status:"ready",score:0,correct:0,total:0,bestStreak:0,joinedAtMs:Date.now(),updatedAt:FieldValue.serverTimestamp()});tx.update(ref,{playerCount:Number(r.playerCount||0)+1,updatedAt:FieldValue.serverTimestamp()});});return{code,playerId,playerToken,name,config,seed,maxPlayers:MAX_PLAYERS};}
  async function startRoom(p){const {code,ref,room}=await getRoom(p.code);if(hash(p.hostToken)!==room.hostTokenHash)fail("host_forbidden","Lehrerzugriff ungültig.",403);if(room.status!=="waiting")fail("room_started","Runde bereits gestartet.",409);const startsAtMs=Date.now()+5000,endsAtMs=startsAtMs+room.config.durationSec*1000;await ref.update({status:"running",startsAtMs,endsAtMs,updatedAt:FieldValue.serverTimestamp()});return{code,startsAtMs,endsAtMs};}
  async function roomState(p){const {code,ref,room:raw}=await getRoom(p.code);let room=raw;if(room.status==="running"&&Date.now()>=Number(room.endsAtMs||Infinity)){await ref.update({status:"finished",updatedAt:FieldValue.serverTimestamp()}).catch(()=>{});room={...room,status:"finished"};}const host=hash(p.hostToken)===room.hostTokenHash;const can=host||room.config.leaderboardMode==="live"||(room.config.leaderboardMode==="after"&&room.status==="finished");let players=[];if(host||can){const s=await ref.collection("players").get();players=s.docs.map(d=>{const v=d.data();return{id:d.id,name:text(v.name,24),status:v.status||"ready",score:Number(v.score||0),correct:Number(v.correct||0),total:Number(v.total||0),joinedAtMs:Number(v.joinedAtMs||0)}}).sort((a,b)=>b.score-a.score||b.correct-a.correct||a.joinedAtMs-b.joinedAtMs);}return{code,status:room.status,seed:room.seed,config:room.config,playerCount:Number(room.playerCount||0),maxPlayers:MAX_PLAYERS,startsAtMs:room.startsAtMs,endsAtMs:room.endsAtMs,players:host?players:[],leaderboard:can?players.slice(0,30):[]};}
  async function submitLive(p){const {ref,room}=await getRoom(p.code),id=String(p.playerId||"").slice(0,80),pr=ref.collection("players").doc(id),s=await pr.get();if(!s.exists)fail("player_not_found","Teilnahme nicht gefunden.",404);const pl=s.data();if(hash(p.playerToken)!==pl.tokenHash)fail("player_forbidden","Spielerzugriff ungültig.",403);const sum=cleanSummary(p.summary),finished=Boolean(p.finished)||Date.now()>=Number(room.endsAtMs||Infinity);await pr.update({...sum,status:finished?"finished":"running",updatedAt:FieldValue.serverTimestamp()});return{saved:true};}
  return{createRoom,joinRoom,startRoom,roomState,submitLive};
};
