import AppKit
import Foundation
import CoreGraphics

let navy = NSColor(calibratedRed: 0.13, green: 0.15, blue: 0.19, alpha: 1)
let green = NSColor(calibratedRed: 0.14, green: 0.64, blue: 0.49, alpha: 1)
final class SelectionView: NSView {
    var start: NSPoint?; var rect = NSRect.zero; var done: ((NSRect) -> Void)?; var cancelled: (() -> Void)?
    override var acceptsFirstResponder: Bool { true }
    override func mouseDown(with event: NSEvent) { start = convert(event.locationInWindow, from: nil); rect = .zero }
    override func mouseDragged(with event: NSEvent) { guard let a = start else { return }; let raw = convert(event.locationInWindow, from: nil); let b = NSPoint(x:max(0,min(bounds.width,raw.x)),y:max(0,min(bounds.height,raw.y))); rect = NSRect(x: min(a.x,b.x), y: min(a.y,b.y), width: abs(a.x-b.x), height: abs(a.y-b.y)); needsDisplay = true }
    override func mouseUp(with event: NSEvent) { guard start != nil else { return }; mouseDragged(with:event); if rect.width >= 8 && rect.height >= 8 { done?(rect) } else { cancelled?() }; start=nil }
    override func keyDown(with event: NSEvent) { if event.keyCode == 53 { cancelled?() } }
    override func draw(_ dirtyRect: NSRect) { NSColor(calibratedWhite:0,alpha:0.025).setFill();bounds.fill();if !rect.isEmpty { NSColor.systemBlue.withAlphaComponent(0.13).setFill();rect.fill();NSColor.systemBlue.setStroke();let p=NSBezierPath(rect:rect);p.lineWidth=2;p.stroke() } }
}
final class InputPanel:NSPanel { override var canBecomeKey:Bool { true } }
final class App: NSObject, NSApplicationDelegate {
    var launcher:NSPanel!, menu:NSPanel?, note:NSPanel?, selection:NSPanel?, statusItem:NSStatusItem!
    var textView:NSTextView?, noteStatus:NSTextField?, saveButton:NSButton?, projectPopup:NSPopUpButton?
    var projects:[(String,String)] = [("gradecrew","Homepage"),("werkzeug-test","Werkzeug-Prüffläche")]
    var projectID = UserDefaults.standard.string(forKey:"GCProject") ?? "werkzeug-test"
    var capturedData:Data?, selectedRect:NSRect?, selectedScreen:NSScreen?, foreground="", pending:[String:Any]?, sending=false
    var outbox:[[String:Any]]=[]; var outboxError=""; var flushing=false; var retryTimer:Timer?
    let base = URL(string:"http://127.0.0.1:8772")!
    let dataDir:URL = {
        if let i=CommandLine.arguments.firstIndex(of:"--data-dir"),CommandLine.arguments.count>i+1{return URL(fileURLWithPath:CommandLine.arguments[i+1],isDirectory:true)}
        return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support/GradeCrewWorkbench",isDirectory:true)
    }()
    var outboxURL:URL { dataDir.appendingPathComponent("native-outbox.json") }
    func applicationDidFinishLaunching(_ notification:Notification) {
        NSApp.setActivationPolicy(.accessory)
        do {try FileManager.default.createDirectory(at:dataDir,withIntermediateDirectories:true,attributes:[.posixPermissions:0o700]);if FileManager.default.fileExists(atPath:outboxURL.path){let b=try Data(contentsOf:outboxURL);guard let v=try JSONSerialization.jsonObject(with:b) as? [[String:Any]] else { throw NSError(domain:"Outbox",code:1) };outbox=v}} catch {outboxError="Lokale Ablage kann nicht gelesen werden. Vorhandene Datei bleibt erhalten."}
        let screen=NSScreen.main ?? NSScreen.screens[0]
        launcher=panel(NSRect(x:screen.visibleFrame.minX+12,y:screen.visibleFrame.minY+12,width:34,height:34))
        let button=NSButton(frame:NSRect(x:0,y:0,width:34,height:34));button.isBordered=false;button.image=NSImage(systemSymbolName:"arrow.right.to.line",accessibilityDescription:"Entwicklungswerkzeug");button.contentTintColor = .white;button.target=self;button.action=#selector(toggleMenu);launcher.contentView?.addSubview(button);launcher.orderFrontRegardless()
        statusItem=NSStatusBar.system.statusItem(withLength:NSStatusItem.squareLength);statusItem.button?.image=NSImage(systemSymbolName:"rectangle.dashed",accessibilityDescription:"GradeCrew Entwickler");let sm=NSMenu();sm.addItem(withTitle:"Werkzeug anzeigen",action:#selector(showTool),keyEquivalent:"");sm.addItem(withTitle:"Visuelle Hinweise öffnen",action:#selector(openHub),keyEquivalent:"");sm.addItem(NSMenuItem.separator());sm.addItem(withTitle:"Werkzeug beenden",action:#selector(quit),keyEquivalent:"");for i in sm.items{i.target=self};statusItem.menu=sm
        URLSession.shared.dataTask(with:base.appendingPathComponent("__dev/projects")){data,_,_ in guard let data=data,let json=try? JSONSerialization.jsonObject(with:data) as? [String:Any],let ps=json["projects"] as? [[String:Any]] else{return};let entries=ps.compactMap{p -> (String,String)? in guard let id=p["id"] as? String,let label=p["label"] as? String else{return nil};return(id,label)};DispatchQueue.main.async {if !entries.isEmpty{self.projects=entries;if !entries.contains(where:{$0.0==self.projectID}){self.projectID=entries.first(where:{$0.0=="werkzeug-test"})?.0 ?? entries[0].0}}}}.resume()
        flush();retryTimer=Timer.scheduledTimer(withTimeInterval:15,repeats:true){_ in self.flush()}
    }
    func panel(_ rect:NSRect)->NSPanel {let p=NSPanel(contentRect:rect,styleMask:[.borderless,.nonactivatingPanel],backing:.buffered,defer:false);p.level = .statusBar;p.isOpaque=false;p.backgroundColor = .clear;p.hasShadow=true;p.collectionBehavior=[.canJoinAllSpaces,.fullScreenAuxiliary];p.contentView?.wantsLayer=true;p.contentView?.layer?.backgroundColor=navy.cgColor;p.contentView?.layer?.cornerRadius=10;return p}
    func label(_ value:String,_ frame:NSRect)->NSTextField {let t=NSTextField(labelWithString:value);t.frame=frame;t.textColor = .white;t.font = .systemFont(ofSize:12);t.lineBreakMode = .byWordWrapping;return t}
    func actionButton(_ title:String,_ y:CGFloat,_ selector:Selector)->NSButton {let b=NSButton(title:title,target:self,action:selector);b.frame=NSRect(x:10,y:y,width:244,height:30);b.bezelStyle = .rounded;b.contentTintColor = .white;return b}
    @objc func showTool(){launcher.orderFrontRegardless()}
    @objc func toggleMenu(){if let n=note,n.isVisible{n.makeKeyAndOrderFront(nil);return};if let m=menu,m.isVisible{m.orderOut(nil);return};let f=launcher.frame;menu=panel(NSRect(x:f.minX,y:f.maxY+8,width:264,height:274));guard let v=menu?.contentView else{return};v.addSubview(label("Werkzeug",NSRect(x:12,y:244,width:240,height:20)));let popup=NSPopUpButton(frame:NSRect(x:10,y:207,width:244,height:26));for p in projects{popup.addItem(withTitle:p.1)};if let index=projects.firstIndex(where:{$0.0==projectID}){popup.selectItem(at:index)};popup.target=self;popup.action=#selector(projectChanged);projectPopup=popup;v.addSubview(popup);v.addSubview(actionButton("Bereich markieren",168,#selector(mark)));v.addSubview(actionButton("Screenshot-Fenster aufnehmen",132,#selector(capture)));v.addSubview(actionButton("Zur ganzen Ansicht etwas sagen",96,#selector(pageNote)));v.addSubview(actionButton("Visuelle Hinweise öffnen",60,#selector(openHub)));v.addSubview(label("Die Leiste verschwindet während der Auswahl.",NSRect(x:12,y:14,width:240,height:38)));menu?.orderFrontRegardless()}
    @objc func projectChanged(){guard let p=projectPopup else{return};let i=p.indexOfSelectedItem;if i>=0&&i<projects.count{projectID=projects[i].0;UserDefaults.standard.set(projectID,forKey:"GCProject")}}
    @objc func mark(){beginSelection(withImage:false)}
    @objc func capture(){beginSelection(withImage:true)}
    func beginSelection(withImage:Bool){menu?.orderOut(nil);launcher.orderOut(nil);foreground=NSWorkspace.shared.frontmostApplication?.localizedName ?? "Native App";capturedData=nil;pending=nil;selectedRect=nil;let screen=NSScreen.screens.first(where:{$0.frame.contains(NSEvent.mouseLocation)}) ?? NSScreen.main ?? NSScreen.screens[0];selectedScreen=screen;let p=InputPanel(contentRect:screen.frame,styleMask:[.borderless],backing:.buffered,defer:false);p.level = .screenSaver;p.isOpaque=false;p.backgroundColor = .clear;p.collectionBehavior=[.canJoinAllSpaces,.fullScreenAuxiliary];let view=SelectionView(frame:NSRect(origin:.zero,size:screen.frame.size));view.done={rect in self.selectedRect=rect;p.orderOut(nil);self.selection=nil;if withImage{self.takeImage(rect,screen:screen)}else{self.openNote()}};view.cancelled={p.orderOut(nil);self.selection=nil;self.launcher.orderFrontRegardless()};p.contentView=view;p.makeFirstResponder(view);selection=p;NSApp.activate(ignoringOtherApps:true);p.makeKeyAndOrderFront(nil)}
    @objc func pageNote(){menu?.orderOut(nil);foreground=NSWorkspace.shared.frontmostApplication?.localizedName ?? "Native App";capturedData=nil;selectedRect=nil;selectedScreen=nil;pending=nil;openNote()}
    func takeImage(_ rect:NSRect,screen:NSScreen){let global=rect.offsetBy(dx:screen.frame.minX,dy:screen.frame.minY);let primaryTop=NSScreen.screens.first?.frame.maxY ?? screen.frame.maxY;let captureRect="\(Int(global.minX)),\(Int(primaryTop-global.maxY)),\(Int(global.width)),\(Int(global.height))";let tmp=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString+".png");DispatchQueue.global().async{Thread.sleep(forTimeInterval:0.15);let proc=Process();proc.executableURL=URL(fileURLWithPath:"/usr/sbin/screencapture");proc.arguments=["-x","-R"+captureRect,tmp.path];proc.standardError=Pipe();var captureError="";do{try proc.run();proc.waitUntilExit();if proc.terminationStatus==0,let raw=try? Data(contentsOf:tmp){self.capturedData=self.shrink(raw)}else{captureError="Bildschirmaufnahme nicht erlaubt oder abgebrochen. Hinweis kann ohne Bild gespeichert werden."}}catch{captureError="Aufnahme fehlgeschlagen. Hinweis kann ohne Bild gespeichert werden."};try? FileManager.default.removeItem(at:tmp);DispatchQueue.main.async{self.openNote();if !captureError.isEmpty{self.noteStatus?.stringValue=captureError}}}}
    func shrink(_ raw:Data)->Data? {guard let img=NSImage(data:raw) else{return nil};let size=img.size,scale=min(1,1200/max(size.width,size.height));guard let rep=NSBitmapImageRep(bitmapDataPlanes:nil,pixelsWide:max(1,Int(size.width*scale)),pixelsHigh:max(1,Int(size.height*scale)),bitsPerSample:8,samplesPerPixel:4,hasAlpha:true,isPlanar:false,colorSpaceName:.deviceRGB,bytesPerRow:0,bitsPerPixel:0) else{return nil};NSGraphicsContext.saveGraphicsState();NSGraphicsContext.current=NSGraphicsContext(bitmapImageRep:rep);img.draw(in:NSRect(x:0,y:0,width:CGFloat(rep.pixelsWide),height:CGFloat(rep.pixelsHigh)));NSGraphicsContext.restoreGraphicsState();let result=rep.representation(using:.png,properties:[:]);return (result?.count ?? 0)<=2*1024*1024 ? result:nil}
    func openNote(){launcher.orderFrontRegardless();let screen=selectedScreen ?? NSScreen.main ?? NSScreen.screens[0],height:CGFloat=capturedData==nil ? 270:410;let f=screen.visibleFrame;note=panel(NSRect(x:f.midX-180,y:f.midY-height/2,width:360,height:height));note?.styleMask.insert(.titled);note?.title="Auftrag";guard let v=note?.contentView else{return};v.addSubview(label("Was soll hier geändert werden?",NSRect(x:16,y:height-35,width:330,height:23)));var textY:CGFloat=102;if let data=capturedData,let image=NSImage(data:data){let iv=NSImageView(frame:NSRect(x:16,y:height-185,width:328,height:135));iv.image=image;iv.imageScaling = .scaleProportionallyUpOrDown;v.addSubview(iv);textY=height-292};let scroll=NSScrollView(frame:NSRect(x:16,y:textY,width:328,height:96));scroll.hasVerticalScroller=true;let tv=NSTextView(frame:NSRect(x:0,y:0,width:328,height:96));tv.isRichText=false;tv.font = .systemFont(ofSize:13);tv.textColor = .white;tv.backgroundColor=NSColor(calibratedWhite:0.1,alpha:1);tv.string="";scroll.documentView=tv;v.addSubview(scroll);textView=tv;let st=label(outboxError.isEmpty ? "Projekt: \(projects.first(where:{$0.0==projectID})?.1 ?? projectID)":outboxError,NSRect(x:16,y:45,width:328,height:48));noteStatus=st;v.addSubview(st);let cancel=NSButton(title:"Schließen",target:self,action:#selector(closeNote));cancel.frame=NSRect(x:16,y:12,width:95,height:29);cancel.bezelStyle = .rounded;v.addSubview(cancel);let save=NSButton(title:"Auftrag speichern",target:self,action:#selector(saveNote));save.frame=NSRect(x:128,y:12,width:216,height:29);save.bezelStyle = .rounded;save.contentTintColor=green;saveButton=save;v.addSubview(save);NSApp.activate(ignoringOtherApps:true);note?.makeKeyAndOrderFront(nil);note?.makeFirstResponder(tv)}
    @objc func closeNote(){note?.orderOut(nil);note=nil;launcher.orderFrontRegardless()}
    func saveOutbox() throws {if !outboxError.isEmpty{throw NSError(domain:outboxError,code:1)};let b=try JSONSerialization.data(withJSONObject:outbox,options:[.sortedKeys]);try b.write(to:outboxURL,options:.atomic);try FileManager.default.setAttributes([.posixPermissions:0o600],ofItemAtPath:outboxURL.path)}
    @objc func saveNote(){if sending{return};let text=textView?.string.trimmingCharacters(in:.whitespacesAndNewlines) ?? "";if text.isEmpty||text.count>3000{noteStatus?.stringValue="Bitte einen kurzen Hinweis bis 3000 Zeichen schreiben.";return};if pending==nil{var p:[String:Any]=["text":text,"projectId":projectID,"source":"native","clientRequestId":UUID().uuidString,"view":foreground,"context":["app":foreground,"entity":"","scrollX":0,"scrollY":0]];if let r=selectedRect,let screen=selectedScreen{p["region"]=["x":r.minX,"y":screen.frame.height-r.maxY,"width":r.width,"height":r.height,"viewportWidth":screen.frame.width,"viewportHeight":screen.frame.height]};if let image=capturedData{p["screenshot"]=["mimeType":"image/png","base64":image.base64EncodedString()]};outbox.append(p);do{try saveOutbox();pending=p;textView?.isEditable=false}catch{outbox.removeLast();noteStatus?.stringValue="Lokales Sichern fehlgeschlagen. Text bleibt im Fenster.";return}}
        guard let p=pending else{return};sending=true;saveButton?.isEnabled=false;post(p){ok,error in DispatchQueue.main.async{self.sending=false;self.saveButton?.isEnabled=true;if ok{self.outbox.removeAll{($0["clientRequestId"] as? String)==(p["clientRequestId"] as? String)};try? self.saveOutbox();self.pending=nil;self.noteStatus?.stringValue="Auf dem lokalen Server gespeichert.";self.saveButton?.title="Gespeichert";self.saveButton?.isEnabled=false}else{self.noteStatus?.stringValue="Lokal gesichert. Serverabgleich offen: \(error)";self.saveButton?.title="Serverabgleich wiederholen"}}}}
    func post(_ payload:[String:Any],completion:@escaping(Bool,String)->Void){var r=URLRequest(url:base.appendingPathComponent("__review/tasks"));r.httpMethod="POST";r.timeoutInterval=12;r.setValue(base.absoluteString,forHTTPHeaderField:"Origin");r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=try? JSONSerialization.data(withJSONObject:payload);URLSession.shared.dataTask(with:r){data,response,error in if let error=error{completion(false,error.localizedDescription);return};let result=(data.flatMap{try? JSONSerialization.jsonObject(with:$0)}) as? [String:Any];let success=(response as? HTTPURLResponse)?.statusCode==201 && (result?["task"] as? [String:Any])?["id"] != nil;completion(success,result?["message"] as? String ?? "Speicherbestätigung fehlt")}.resume()}
    func flush(){if outbox.isEmpty || !outboxError.isEmpty || flushing || sending{return};flushing=true;let p=outbox[0];post(p){ok,_ in DispatchQueue.main.async{self.flushing=false;if ok{self.outbox.removeAll{($0["clientRequestId"] as? String)==(p["clientRequestId"] as? String)};try? self.saveOutbox();self.flush()}}}}
    @objc func openHub(){menu?.orderOut(nil);NSWorkspace.shared.open(base.appendingPathComponent("__dev"))}
    @objc func quit(){NSApp.terminate(nil)}
}
let app=NSApplication.shared;let delegate=App();app.delegate=delegate;app.run()
