(() => {
  'use strict';

  const API_URL = 'https://europe-west1-hausaufgabe-staging.cloudfunctions.net/fehlerjagdApi';
  const PLAYER_KEY = 'gradecrew-fehlerjagd-player-v1';
  const NAME_KEY = 'gradecrew-fehlerjagd-name-v1';
  const BEST_PREFIX = 'gradecrew-fehlerjagd-best-v1:';
  const { SKILLS, GRADE_HINTS, LEVEL_LABEL, availableSkills, createEngine } = window.FehlerjagdDeutsch;

  const $ = id => document.getElementById(id);
  const views = ['homeView','setupView','highscoreView','joinView','teacherView','waitingView','gameView','resultView'].map($);
  const el = {};
  [
    'homeView','setupView','highscoreView','joinView','teacherView','waitingView','gameView','resultView','quickJoinCode','quickJoinBtn','setupForm','setupEyebrow','setupTitle','setupSubtitle','curriculumHint','skillChoices','rulesHint','teacherRules','leaderboardMode','wrongPenalty','lockSeconds','speedBonus','streakBonus','showSolution','scorePreview','setupError','setupSubmit','highscoreName','highscoreGrade','highscoreFocus','highscoreError','startHighscoreBtn','refreshBoardBtn','boardLabel','highscoreBoard','joinCode','joinName','joinError','joinBtn','teacherSummary','roomCode','qrBox','copyLinkBtn','playerCount','roomBadge','playerList','teacherRulesSummary','startLiveBtn','newLiveBtn','liveBoardStatus','liveBoard','waitingName','waitingCode','countdown','roundLabel','playerLabel','roundCodeLabel','timerFill','timer','correctCount','streakCount','scoreCount','taskNumber','taskSkill','taskInstruction','taskPrompt','taskContext','answers','multiSubmit','penaltyLock','penaltyTime','feedback','resultSummary','resultCorrect','resultAccuracy','resultStreak','resultScore','skillProfile','resultBoardCard','resultBoard','resultActionText','sameRoundBtn','newRoundBtn','homeBtn','debugDump'
  ].forEach(id => el[id] = $(id));

  const state = {
    mode: 'practice', config: null, seed: 0, engine: null, task: null, selectedMulti: new Set(),
    roomCode: null, hostToken: null, playerId: null, playerToken: null, playerName: '',
    attemptId: null, attemptToken: null, boardId: null,
    startedAt: 0, endsAt: 0, timerId: null, pollId: null, progressId: null, lockId: null, countdownId: null,
    questionStartedAt: 0, questionIndex: 0, locked: false, finished: false,
    correct: 0, total: 0, streak: 0, bestStreak: 0, score: 0, events: [], skillStats: {}
  };

  function show(view) { views.forEach(v => v.hidden = v !== view); window.scrollTo({ top: 0, behavior: 'instant' }); }
  function stopAsync() { [state.timerId,state.pollId,state.progressId,state.lockId,state.countdownId].forEach(clearInterval); state.timerId=state.pollId=state.progressId=state.lockId=state.countdownId=null; }
  function randomSeed() { if (crypto?.getRandomValues) { const a=new Uint32Array(1); crypto.getRandomValues(a); return a[0]; } return Math.floor(Math.random()*0xffffffff)>>>0; }
  function playerKey() { let k=localStorage.getItem(PLAYER_KEY); if(!k){k=crypto?.randomUUID?.().replace(/-/g,'')||`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;localStorage.setItem(PLAYER_KEY,k);} return k; }
  async function api(action,payload={}) { const c=new AbortController(); const t=setTimeout(()=>c.abort(),12000); try { const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload}),signal:c.signal}); const b=await r.json().catch(()=>null); if(!r.ok||!b?.ok) throw new Error(b?.error?.message||`Backend ${r.status}`); return b.data; } catch(e){ if(e?.name==='AbortError') throw new Error('Die Verbindung zum Fehlerjagd-Backend dauert zu lange.'); throw e; } finally {clearTimeout(t);} }

  function grade() { return document.querySelector('input[name="grade"]:checked')?.value || '9'; }
  function level() { return document.querySelector('input[name="level"]:checked')?.value || 'n2'; }
  function durationSec() { return Number(document.querySelector('input[name="duration"]:checked')?.value||3)*60; }
  function selectedSkills() { return [...document.querySelectorAll('input[name="skill"]:checked:not(:disabled)')].map(i=>i.value); }
  function scoring() { return { correctPoints:100, wrongPenalty:Number(el.wrongPenalty.value), lockSeconds:Number(el.lockSeconds.value), speedBonus:el.speedBonus.checked, streakBonus:el.streakBonus.checked, showSolution:el.showSolution.checked, allowNegative:true }; }

  function renderSkills() {
    const g=grade(); const avail=new Set(availableSkills(g));
    el.skillChoices.replaceChildren();
    Object.entries(SKILLS).forEach(([id,m])=>{
      const lab=document.createElement('label'); lab.className='skillTile'+(avail.has(id)?'':' isDisabled');
      const input=document.createElement('input'); input.type='checkbox';input.name='skill';input.value=id;input.checked=avail.has(id);input.disabled=!avail.has(id);
      const span=document.createElement('span'); const b=document.createElement('b'); b.textContent=m.label; const small=document.createElement('small');small.textContent=m.desc;span.append(b,small);lab.append(input,span);el.skillChoices.append(lab);
    });
    el.curriculumHint.textContent=GRADE_HINTS[g]||'';
  }
  function updateScorePreview(){const p=[];p.push(Number(el.wrongPenalty.value)?`−${el.wrongPenalty.value} falsch`:'keine Minuspunkte');p.push(Number(el.lockSeconds.value)?`${el.lockSeconds.value} s Sperre`:'keine Sperre');if(el.speedBonus.checked)p.push('Zeitbonus');if(el.streakBonus.checked)p.push('Serienbonus');el.scorePreview.textContent=p.join(' · ');}
  function gatherConfig(){const skills=selectedSkills();if(!skills.length)throw new Error('Bitte mindestens einen Kompetenzbereich auswählen.');return{version:1,grade:grade(),skills,level:level(),durationSec:durationSec(),scoring:scoring(),leaderboardMode:state.mode==='liveTeacher'?el.leaderboardMode.value:'hidden'};}
  function configLabel(c){const names=c.skills.length<=2?c.skills.map(s=>SKILLS[s]?.short||s).join(' + '):`${c.skills.length} Bereiche`;return `Jgst. ${c.grade==='qa'?'Quali':c.grade} · ${names} · ${LEVEL_LABEL[c.level]} · ${Math.round(c.durationSec/60)} min`;}
  function ruleLabel(c){const s=c.scoring;return `+100 richtig · ${s.wrongPenalty?`−${s.wrongPenalty} falsch`:'keine Minuspunkte'} · ${s.lockSeconds?`${s.lockSeconds} s Sperre`:'keine Sperre'}${s.speedBonus?' · Zeitbonus':''}${s.streakBonus?' · Serienbonus':''}`;}

  function openSetup(mode){stopAsync();state.mode=mode;const live=mode==='liveTeacher';el.teacherRules.hidden=!live;el.setupEyebrow.textContent=live?'LIVE MIT LEHRKRAFT':'ÜBEN';el.setupTitle.textContent=live?'Live-Runde konfigurieren':'Training konfigurieren';el.setupSubtitle.textContent=live?'Jahrgang, Kompetenzen und Spielregeln festlegen. Danach entsteht der QR-Code.':'Stelle dein persönliches Deutsch-Training zusammen.';el.rulesHint.textContent=live?'Diese Regeln gelten für alle Teilnehmenden.':'Für dein persönliches Training.';el.setupSubmit.textContent=live?'Live-Runde erstellen':'Training starten';el.setupError.textContent='';renderSkills();show(el.setupView);}
  function openJoin(code=''){stopAsync();el.joinCode.value=String(code).replace(/\D/g,'').slice(0,6);el.joinName.value=el.joinName.value||localStorage.getItem(NAME_KEY)||'';el.joinError.textContent='';show(el.joinView);(el.joinCode.value.length===6?el.joinName:el.joinCode).focus();}
  function openHighscore(){stopAsync();el.highscoreName.value=el.highscoreName.value||localStorage.getItem(NAME_KEY)||'';el.highscoreError.textContent='';show(el.highscoreView);refreshBoard();}

  function resetGame(seed){clearInterval(state.timerId);clearInterval(state.progressId);clearInterval(state.lockId);state.seed=seed>>>0;state.engine=createEngine({...state.config,seed:state.seed});state.task=null;state.selectedMulti.clear();state.startedAt=0;state.endsAt=0;state.questionStartedAt=0;state.questionIndex=0;state.locked=false;state.finished=false;state.correct=0;state.total=0;state.streak=0;state.bestStreak=0;state.score=0;state.events=[];state.skillStats={};}
  function practiceBestKey(c){return `${BEST_PREFIX}${c.grade}:${c.level}:${c.durationSec}:${[...c.skills].sort().join(',')}`;}
  function beginGame(startAt,endAt){state.startedAt=startAt;state.endsAt=endAt;el.roundLabel.textContent=configLabel(state.config);el.playerLabel.textContent=state.mode==='practice'?'Üben':state.playerName||(state.mode==='highscore'?'Highscore':'Live');el.roundCodeLabel.textContent=state.roomCode||(state.mode==='highscore'?'HIGHSCORE':'SOLO');updateCounters();show(el.gameView);updateTimer();state.timerId=setInterval(updateTimer,200);if(state.mode==='livePlayer')state.progressId=setInterval(()=>submitLive(false),1800);nextTask();}
  function startPractice(config,seed=randomSeed()){state.mode='practice';state.config=config;state.roomCode=null;state.playerName='';resetGame(seed);const now=Date.now();beginGame(now,now+config.durationSec*1000);}

  function nextTask(){if(state.finished||Date.now()>=state.endsAt){finishGame();return;}state.locked=false;el.penaltyLock.hidden=true;state.questionIndex++;state.task=state.engine.next();state.selectedMulti.clear();state.questionStartedAt=Date.now();renderTask();}
  function renderTask(){const t=state.task;el.taskNumber.textContent=`Aufgabe ${state.questionIndex}`;el.taskSkill.textContent=SKILLS[t.skill]?.label||t.skill;el.taskInstruction.textContent=t.instruction;el.taskPrompt.textContent=t.prompt;el.taskContext.textContent=t.context||'';el.taskContext.hidden=!t.context;el.feedback.textContent='';el.feedback.className='feedback';el.answers.replaceChildren();el.multiSubmit.hidden=t.type!=='multi';
    if(t.type==='single')t.options.forEach((opt,i)=>{const b=document.createElement('button');b.type='button';b.className='answerBtn';b.dataset.value=opt;b.innerHTML=`<span class="answerKey">${i+1}</span><span></span>`;b.lastElementChild.textContent=opt;b.addEventListener('click',()=>answerSingle(opt,b));el.answers.append(b);});
    else t.options.forEach((opt,i)=>{const b=document.createElement('button');b.type='button';b.className='answerBtn';b.dataset.key=opt.key;b.innerHTML=`<span class="answerKey">${i+1}</span><span></span>`;b.lastElementChild.textContent=opt.label;b.addEventListener('click',()=>{if(state.locked)return;if(state.selectedMulti.has(opt.key)){state.selectedMulti.delete(opt.key);b.classList.remove('selected');}else{state.selectedMulti.add(opt.key);b.classList.add('selected');}});el.answers.append(b);});
  }
  function scoreDelta(correct){const s=state.config.scoring;if(!correct)return-s.wrongPenalty;const ms=Date.now()-state.questionStartedAt;const speed=s.speedBonus?Math.max(0,50-Math.floor(ms/180)):0;const streak=s.streakBonus?Math.min(60,Math.max(0,state.streak-1)*6):0;return 100+speed+streak;}
  function recordResult(correct,delta,detail){state.total++;if(correct){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);}else state.streak=0;state.score+=delta;const skill=state.task.skill;const stat=state.skillStats[skill]||(state.skillStats[skill]={total:0,correct:0});stat.total++;if(correct)stat.correct++;state.events.push({n:state.questionIndex,taskId:state.task.id,skill,correct,delta,score:state.score,detail,latencyMs:Date.now()-state.questionStartedAt});updateCounters();}
  function answerSingle(value,button){if(state.locked||state.finished)return;state.locked=true;const ok=value===state.task.correct;const delta=scoreDelta(ok);recordResult(ok,delta,value);for(const b of el.answers.querySelectorAll('.answerBtn')){b.disabled=true;if(state.config.scoring.showSolution&&b.dataset.value===state.task.correct)b.classList.add('correct');}if(!ok)button.classList.add('wrong');showFeedback(ok,delta);afterAnswer(ok);}
  function answerMulti(){if(state.locked||state.finished)return;const needed=state.task.options.filter(o=>o.correct).map(o=>o.key);const selected=[...state.selectedMulti];const ok=needed.length===selected.length&&needed.every(k=>state.selectedMulti.has(k));state.locked=true;const delta=scoreDelta(ok);recordResult(ok,delta,selected);for(const b of el.answers.querySelectorAll('.answerBtn')){b.disabled=true;const o=state.task.options.find(x=>x.key===b.dataset.key);if(state.config.scoring.showSolution&&o?.correct)b.classList.add('correct');if(state.selectedMulti.has(b.dataset.key)&&!o?.correct)b.classList.add('wrong');}el.multiSubmit.disabled=true;showFeedback(ok,delta);afterAnswer(ok);}
  function showFeedback(ok,delta){const explain=state.config.scoring.showSolution?` ${state.task.explanation}`:'';el.feedback.textContent=ok?`Richtig · +${delta} Punkte.${explain}`:`Nicht ganz · ${delta} Punkte.${explain}`;el.feedback.className=`feedback ${ok?'good':'bad'}`;}
  function afterAnswer(ok){const lock=!ok?state.config.scoring.lockSeconds:0;if(lock>0)startLock(lock);else setTimeout(()=>{el.multiSubmit.disabled=false;nextTask();},ok?450:750);}
  function startLock(seconds){let r=seconds;el.penaltyLock.hidden=false;el.penaltyTime.textContent=r;clearInterval(state.lockId);state.lockId=setInterval(()=>{r--;el.penaltyTime.textContent=Math.max(0,r);if(r<=0){clearInterval(state.lockId);state.lockId=null;el.multiSubmit.disabled=false;nextTask();}},1000);}
  function updateCounters(){el.correctCount.textContent=state.correct;el.streakCount.textContent=state.streak;el.scoreCount.textContent=state.score;}
  function updateTimer(){const left=Math.max(0,state.endsAt-Date.now());el.timer.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.ceil((left%60000)/1000)).padStart(2,'0')}`;const total=Math.max(1,state.endsAt-state.startedAt);el.timerFill.style.width=`${Math.max(0,Math.min(100,left/total*100))}%`;if(left<=0)finishGame();}
  function summary(){return{total:state.total,correct:state.correct,bestStreak:state.bestStreak,score:state.score};}

  async function finishGame(){if(state.finished)return;state.finished=true;clearInterval(state.timerId);clearInterval(state.progressId);clearInterval(state.lockId);state.timerId=state.progressId=state.lockId=null;const s=summary();const accuracy=s.total?Math.round(s.correct/s.total*100):0;el.resultCorrect.textContent=`${s.correct} / ${s.total}`;el.resultAccuracy.textContent=`${accuracy} %`;el.resultStreak.textContent=s.bestStreak;el.resultScore.textContent=s.score;el.resultSummary.textContent=`${configLabel(state.config)} · ${accuracy}% richtig.`;renderSkillProfile();el.resultBoardCard.hidden=true;
    if(state.mode==='practice'){const key=practiceBestKey(state.config);const before=Number(localStorage.getItem(key)||0);if(s.score>before)localStorage.setItem(key,String(s.score));el.resultActionText.textContent=s.score>before?'Neuer persönlicher Rekord. Noch einmal?':`Persönlicher Rekord: ${Math.max(before,s.score)} Punkte.`;}
    if(state.mode==='livePlayer'){await submitLive(true).catch(()=>{});try{const room=await api('roomState',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken});if(room.leaderboard?.length){el.resultBoardCard.hidden=false;renderBoard(el.resultBoard,room.leaderboard);}}catch{}el.resultActionText.textContent='Die Live-Runde ist beendet.';}
    if(state.mode==='highscore'){try{const r=await api('finishHighscoreAttempt',{attemptId:state.attemptId,attemptToken:state.attemptToken,summary:s});el.resultBoardCard.hidden=false;renderBoard(el.resultBoard,r.leaderboard||[]);el.resultActionText.textContent=r.personalBest?'Neuer persönlicher Highscore!':'Versuch gespeichert.';}catch(e){el.resultActionText.textContent=`Highscore konnte nicht gespeichert werden: ${e.message}`;}}
    el.debugDump.textContent=JSON.stringify({mode:state.mode,config:state.config,seed:state.seed,events:state.events},null,2);show(el.resultView);
  }
  function renderSkillProfile(){el.skillProfile.replaceChildren();const rows=Object.entries(state.skillStats).sort((a,b)=>(a[1].correct/a[1].total)-(b[1].correct/b[1].total));if(!rows.length){el.skillProfile.textContent='Noch keine auswertbaren Aufgaben.';return;}rows.forEach(([id,s])=>{const p=Math.round(s.correct/s.total*100);const row=document.createElement('div');row.className='skillRow';row.innerHTML=`<span></span><div class="skillBar"><i style="width:${p}%"></i></div><b>${p}%</b>`;row.firstElementChild.textContent=SKILLS[id]?.short||id;el.skillProfile.append(row);});}
  function renderBoard(target,rows=[]){target.replaceChildren();if(!rows.length){const li=document.createElement('li');li.className='empty';li.textContent='Noch keine Einträge.';target.append(li);return;}rows.forEach((r,i)=>{const li=document.createElement('li');li.innerHTML=`<span class="rank">${r.rank||i+1}</span><span class="name"></span><span class="score">${r.score} P</span>`;li.querySelector('.name').textContent=r.name;target.append(li);});}

  async function createLive(config){el.setupSubmit.disabled=true;el.setupError.textContent='';try{const r=await api('createRoom',{config});state.mode='liveTeacher';state.config=r.config;state.roomCode=r.code;state.hostToken=r.hostToken;el.roomCode.textContent=r.code;el.teacherSummary.textContent=configLabel(r.config);el.teacherRulesSummary.textContent=ruleLabel(r.config);renderQr(r.code);show(el.teacherView);startTeacherPoll();}catch(e){el.setupError.textContent=e.message;}finally{el.setupSubmit.disabled=false;}}
  function renderQr(code){el.qrBox.replaceChildren();const url=new URL(location.href);url.search='';url.searchParams.set('join',code);if(window.QRCode)new QRCode(el.qrBox,{text:url.toString(),width:100,height:100,correctLevel:QRCode.CorrectLevel.M});}
  function startTeacherPoll(){clearInterval(state.pollId);pollTeacher();state.pollId=setInterval(pollTeacher,1000);}
  async function pollTeacher(){try{const r=await api('roomState',{code:state.roomCode,hostToken:state.hostToken});el.playerCount.textContent=`${r.playerCount} / ${r.maxPlayers} bereit`;el.roomBadge.textContent=r.status==='waiting'?'WARTET':r.status==='running'?'LÄUFT':'FERTIG';el.roomBadge.classList.toggle('live',r.status==='running');renderPlayers(r.players||[]);renderBoard(el.liveBoard,r.leaderboard||[]);el.liveBoardStatus.textContent=r.status==='waiting'?'erscheint ab dem Start':r.status==='running'?'aktueller Stand':'Endstand';if(r.status==='finished')clearInterval(state.pollId);}catch{} }
  function renderPlayers(rows){el.playerList.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='Noch niemand beigetreten.';el.playerList.append(p);return;}rows.forEach(p=>{const d=document.createElement('div');d.className='playerRow';const s=document.createElement('strong');s.textContent=p.name;const st=document.createElement('span');st.textContent=p.status==='finished'?'fertig':p.status==='running'?`${p.score} P`:'bereit';d.append(s,st);el.playerList.append(d);});}
  async function startLive(){el.startLiveBtn.disabled=true;try{await api('startRoom',{code:state.roomCode,hostToken:state.hostToken});await pollTeacher();}catch(e){alert(e.message);}finally{el.startLiveBtn.disabled=false;}}
  async function joinLive(){const code=el.joinCode.value.replace(/\D/g,'').slice(0,6);const name=el.joinName.value.trim();el.joinError.textContent='';if(code.length!==6){el.joinError.textContent='Bitte einen 6-stelligen Code eingeben.';return;}if(!name){el.joinError.textContent='Bitte ein Kürzel oder einen kurzen Namen eingeben.';return;}el.joinBtn.disabled=true;try{const r=await api('joinRoom',{code,name});localStorage.setItem(NAME_KEY,name);state.mode='livePlayer';state.roomCode=r.code;state.playerId=r.playerId;state.playerToken=r.playerToken;state.playerName=r.name;state.config=r.config;state.seed=r.seed;el.waitingName.textContent=`${name}, du bist bereit.`;el.waitingCode.textContent=code;show(el.waitingView);startPlayerPoll();}catch(e){el.joinError.textContent=e.message;}finally{el.joinBtn.disabled=false;}}
  function startPlayerPoll(){clearInterval(state.pollId);pollPlayer();state.pollId=setInterval(pollPlayer,900);}
  async function pollPlayer(){try{const r=await api('roomState',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken});if(r.status==='running'){clearInterval(state.pollId);state.pollId=null;state.config=r.config;resetGame(r.seed);startCountdownTo(r.startsAtMs,r.endsAtMs);}else if(r.status==='finished'){clearInterval(state.pollId);el.waitingName.textContent='Diese Runde ist bereits beendet.';}}catch{} }
  function startCountdownTo(startAt,endAt){const tick=()=>{const ms=startAt-Date.now();if(ms<=0){clearInterval(state.countdownId);el.countdown.hidden=true;beginGame(startAt,endAt);return;}el.countdown.hidden=false;el.countdown.textContent=Math.max(1,Math.ceil(ms/1000));};tick();state.countdownId=setInterval(tick,150);}
  async function submitLive(finished){if(!state.roomCode||!state.playerId)return;return api('submitLive',{code:state.roomCode,playerId:state.playerId,playerToken:state.playerToken,summary:summary(),finished});}

  function focusLabel(f){return{mix:'Mix',spelling:'Rechtschreibung',grammar:'Grammatik',qa:'Quali-Mix'}[f]||f;}
  async function refreshBoard(){const g=el.highscoreGrade.value,f=el.highscoreFocus.value;el.boardLabel.textContent=`Jgst. ${g==='qa'?'Quali':g} · ${focusLabel(f)}`;try{const r=await api('leaderboard',{grade:g,focus:f});renderBoard(el.highscoreBoard,r.leaderboard||[]);}catch{renderBoard(el.highscoreBoard,[]);} }
  async function startHighscore(){const name=el.highscoreName.value.trim();if(!name){el.highscoreError.textContent='Bitte ein Kürzel oder einen kurzen Namen eingeben.';return;}el.startHighscoreBtn.disabled=true;el.highscoreError.textContent='';try{const r=await api('createHighscoreAttempt',{name,playerKey:playerKey(),grade:el.highscoreGrade.value,focus:el.highscoreFocus.value});localStorage.setItem(NAME_KEY,name);state.mode='highscore';state.playerName=name;state.attemptId=r.attemptId;state.attemptToken=r.attemptToken;state.boardId=r.boardId;state.config=r.config;resetGame(r.seed);beginGame(r.startsAtMs,r.endsAtMs);}catch(e){el.highscoreError.textContent=e.message;}finally{el.startHighscoreBtn.disabled=false;}}

  document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{const m=b.dataset.open;if(m==='practice')openSetup('practice');else if(m==='live')openSetup('liveTeacher');else openHighscore();}));
  document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>{stopAsync();show(el.homeView);}));
  document.querySelectorAll('input[name="grade"]').forEach(i=>i.addEventListener('change',renderSkills));
  [el.wrongPenalty,el.lockSeconds,el.speedBonus,el.streakBonus].forEach(x=>x.addEventListener('change',updateScorePreview));
  el.setupForm.addEventListener('submit',e=>{e.preventDefault();try{const c=gatherConfig();if(state.mode==='liveTeacher')createLive(c);else startPractice(c);}catch(err){el.setupError.textContent=err.message;}});
  el.quickJoinCode.addEventListener('input',()=>el.quickJoinCode.value=el.quickJoinCode.value.replace(/\D/g,'').slice(0,6));
  el.quickJoinBtn.addEventListener('click',()=>openJoin(el.quickJoinCode.value));
  el.joinCode.addEventListener('input',()=>el.joinCode.value=el.joinCode.value.replace(/\D/g,'').slice(0,6));
  el.joinBtn.addEventListener('click',joinLive);el.startLiveBtn.addEventListener('click',startLive);el.newLiveBtn.addEventListener('click',()=>openSetup('liveTeacher'));
  el.copyLinkBtn.addEventListener('click',async()=>{const u=new URL(location.href);u.search='';u.searchParams.set('join',state.roomCode);await navigator.clipboard?.writeText(u.toString());el.copyLinkBtn.textContent='Link kopiert';setTimeout(()=>el.copyLinkBtn.textContent='Beitrittslink kopieren',1200);});
  el.multiSubmit.addEventListener('click',answerMulti);
  el.highscoreGrade.addEventListener('change',refreshBoard);el.highscoreFocus.addEventListener('change',refreshBoard);el.refreshBoardBtn.addEventListener('click',refreshBoard);el.startHighscoreBtn.addEventListener('click',startHighscore);
  el.homeBtn.addEventListener('click',()=>{stopAsync();show(el.homeView);});
  el.sameRoundBtn.addEventListener('click',()=>{if(state.mode==='practice')startPractice(state.config,state.seed);else if(state.mode==='highscore')openHighscore();else show(el.homeView);});
  el.newRoundBtn.addEventListener('click',()=>{if(state.mode==='practice')startPractice(state.config,randomSeed());else if(state.mode==='highscore')openHighscore();else show(el.homeView);});
  document.addEventListener('keydown',e=>{if(el.gameView.hidden||state.locked||state.finished)return;const n=Number(e.key);if(n<1||n>4)return;const b=el.answers.querySelectorAll('.answerBtn')[n-1];b?.click();});

  renderSkills();updateScorePreview();
  const join=new URLSearchParams(location.search).get('join');if(join)openJoin(join);
})();
