#include "../Source/Bruchpizzeria/LearningCampaign.h"
#include <iostream>
int main(){int checks=0,failed=0;auto check=[&](bool ok,const char* text){++checks;if(!ok){++failed;std::cerr<<"FAIL: "<<text<<'\n';}};using namespace PizzaRules;
 PortionRepair repair(Rational(3,8),Rational(1,2));
 check(repair.Parts==8&&repair.Count()==4&&repair.TargetCount()==3,"half is four eighths against order of three eighths");
 check(!repair.Correct()&&repair.Difference()==-1,"one excess eighth is identified");repair.Toggle(3);check(repair.Correct(),"taking one of four eighths back corrects actual portion");repair.Toggle(9);check(repair.Correct(),"out of range click cannot alter portion");
 PortionRepair missing(Rational(3,4),Rational(1,8));check(missing.Parts==8&&missing.Difference()==5,"three quarters need five more eighths after one eighth delivered");missing.ShowStep();check(missing.Count()==6&&missing.Correct(),"help reveals same whole pizza with six eighths");
 PortionRepair whole(Rational(1),Rational(1,2));check(whole.Parts==2&&whole.Difference()==1,"whole order compares against same whole with two halves");
 PortionRepair add(Rational(3,8),Rational(1,2),Rational(1,4),Rational(1,8));check(add.Parts==8&&add.TargetCount()==3,"arithmetic operands use common eighth pieces");
 check(!PortionRepair(Rational(1,3),Rational(1,2)).Supported,"unsupported denominator never silently labels false slices");
 for(int level=1;level<=10;++level){const auto p=CampaignLevel(level);for(int serial=0;serial<12;++serial){const auto o=CampaignOrder(level,serial);check(o.Amount.Valid&&o.Amount.Num>0&&o.Amount.Num<=o.Amount.Den&&8%o.Amount.Den==0&&o.Amount.Den<=p.MaxDen,"every campaign order is physically servable using up to eighths");check(serial%4==3||o.Op==' ',"arithmetic never turns every guest into an equation");}check(p.Guests>=1&&p.Guests<=3&&p.Ovens>=1&&p.Ovens<=3&&p.Goal>=3,"campaign has usable station and completion limits");}
 for(int level=1;level<=10;++level){const auto layout=CampaignLayout(level);for(int earlier=1;earlier<level;++earlier){const auto other=CampaignLayout(earlier);bool differs=false;for(int i=0;i<13;++i)differs|=layout.Stations[i].X!=other.Stations[i].X||layout.Stations[i].Y!=other.Stations[i].Y;check(differs,"every level has its own actual station arrangement");}for(int i=0;i<13;++i)check(std::abs(layout.Stations[i].X)<=610&&std::abs(layout.Stations[i].Y)<=430,"stations stay inside traversable kitchen bounds");}
 bool hasMinus=false;for(int i=0;i<CampaignLevel(10).Goal;++i)hasMinus|=CampaignOrder(10,i).Op=='-';check(hasMinus,"level ten reaches a minus order before its shift ends");
 bool teachesSeven=false;for(int i=0;i<CampaignLevel(5).Goal;++i)teachesSeven|=Equal(CampaignOrder(5,i).Amount,Rational(7,8));check(teachesSeven,"eighth introduction actually reaches seven eighths within its playable shift");
 const auto first=CampaignLevel(1);check(first.Guests==1&&first.RoundSeconds==0&&first.Patience==0,"first kitchen learns without clock pressure");check(CampaignOrder(1,0).Amount.Den==2,"first guest requests concrete half");check(CampaignLevel(3).Guests==1&&CampaignLevel(3).RoundSeconds==0,"new quarters reduce kitchen load again");check(CampaignLevel(5).MaxDen==8&&CampaignLevel(5).RoundSeconds==0,"eighth introduction is calm");check(CampaignLevel(6).Ovens==2&&CampaignLevel(10).Ovens==2,"parallel ovens unlock after relevant learning introductions");check(CampaignOrder(8,3).Op=='+'&&CampaignOrder(9,3).Op=='+'&&CampaignOrder(10,7).Op=='-',"operations enter campaign in concept order");check(CampaignLevel(-7).Number==1&&CampaignLevel(999).Number==10,"invalid level selection stays in bounded catalog");
 std::cout<<checks<<" campaign/repair checks, "<<failed<<" failures\n";return failed?1:0;}
